[msg MSG_14]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time hanging[n]out with Kenji.[n][w][e]

[msg MSG_15 [Kenji]]
[s][bup 22 162 65535 0]Dude, I just got the greatest plan from[n]that manga I was reading! I'm totally[n]gonna get Ms. Kanou this way.[n][w][e]
[s]Ya wanna hear it? Huh? Do ya? Do ya?[n][w][e]

[msg MSG_16]
[s]> Kenji is acting like a child...[n][w][e]

[msg MSG_17 [Kenji]]
[s][bup 22 161 65535 0]So, this is what I'm gonna say to her...[n][w][e]
[s][bup 22 164 65535 0]"Uh... Teacher, me don't get this..."[n][w][e]
[s][bup 22 161 65535 0]Then, she'll say...[n][w][e]
[s][bup 22 162 65535 0]"Oh, don't worry, Kenji-kun.[n]I'll help you. We'll do it together,[n]step by step."[n][w][e]

[msg MSG_18 [ ]]
[s]> Kenji is acting out his plan for you.[n][w][e]

[msg MSG_19 [Kenji]]
[s][bup 22 162 65535 0][f 6 1 1 0 22 11]Well. whaddya think? Isn't that a great[n]plan!?[n][w][e]

[sel SEL020 top]
[s]"That's not gonna work."[e]
[s]"Yeah, it's perfect!" +2[e]
[s]"Think of something else." +3[e]

[msg MSG_21 [Kenji]]
[s][bup 22 163 65535 0]What!? Why? It totally worked in[n]the manga![n][w][e]

[msg MSG_22 [ ]]
[s]> Kenji seems flustered...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_23 [Kenji]]
[s][bup 22 162 65535 0]I know, right? Okay, I'm totally gonna[n]do it![n][w][e]

[msg MSG_24 [ ]]
[s][f 5 13 0 15 22]> Kenji seems excited.[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_25 [Kenji]]
[s][bup 22 162 65535 0]Oh, okay... Thanks for the advice, man![n][w][e]

[msg MSG_26 [ ]]
[s][f 5 13 0 30 22]> Kenji seems happy.[n][w][e]
[s]> Your friendship has grown stronger.[n][w][e]

[msg MSG_27 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_14_02]
[s]> Iwatodai strip mall,[n]Beef Bowl Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Kenji.[n][w][e]

[msg MSG_15_02 [Kenji]]
[s][bup 22 162 65535 0]Damn... That was good...[n][w][e]

[msg MSG_16_02]
[s]> Kenji is staring off into the[n]distance...[n][w][e]

[msg MSG_17_02 [Kenji]]
[s][bup 22 161 65535 0]Well, dude... I've made up my mind...[n][w][e]

[msg MSG_18_02 [ ]]
[s]> Kenji seems serious.[n][w][e]

[msg MSG_19_02 [Kenji]]
[s][bup 22 163 65535 0][f 6 1 1 0 22 11]That was the last beef bowl I'm ever[n]gonna eat![n][w][e]

[sel SEL020_02 top]
[s]"......"[e]
[s]"Why?"[e]
[s]"Don't be an idiot."[e]

[msg MSG_21_02 [Kenji]]
[s][bup 22 161 65535 0]Dude, I don't think I should be eating[n]beef bowls when I'm goin' out with[n]an "adult" like Emiri...[n][w][e]
[s]I've thought a lot about this, man...[n]So don't try to talk me outta it.[n][w][e]

[msg MSG_22_02 [ ]]
[s][f 5 13 0 15 22]> Kenji is staring off into the[n]distance...[n][w][e]
[s]> You learned something new about him[n]today...[n][w][e]

[msg MSG_23_02 [Kenji]]
[s][bup 22 162 65535 0]Because...[n][w][e]
[s]I wanna be an adult, like Emiri...[n][w][e]
[s]Pretty cool, huh?[n][w][e]

[msg MSG_24_02 [ ]]
[s][f 5 13 0 30 22]> Kenji has a smile on his face.[n][w][e]
[s]> You became a lot closer to Kenji[n]today...[n][w][e]

[msg MSG_25_02 [Kenji]]
[s][bup 22 163 65535 0]C'mon, dude, I'm serious here...[n]At least ask me why![n][w][e]

[msg MSG_26_02 [ ]]
[s]> Kenji seems bored.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_27_02 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_84]
[s]> Iwatodai strip mall,[n]Sweet Shop...[n][w][e]
[s]> You're having a good time with[n]Yukari.[n][w][e]

[msg MSG_85 [Yukari]]
[s][bup 2 2 65535 0][f 6 1 1 0 2 6]Mmmm... That was sooo good![n][w][e]
[s]Nothing beats strawberry rice cake[n]with red beans![n][w][e]

[msg MSG_88]
[s]> Yukari seems to be enjoying her[n]day off...[n][w][e]

[msg MSG_89 [Yukari]]
[s][bup 2 1 65535 0]By the way, [f 4 2]-kun...[n][w][e]

[msg MSG_90 [ ]]
[s]> Yukari seems kinda nervous...[n][w][e]

[msg MSG_91 [Yukari]]
[s][bup 2 1 65535 0]Do YOU like strawberry rice cake[n]with red beans?[n][w][e]

[sel SEL092 top]
[s]"Not really."[e]
[s]"I love it."[e]
[s]"Never tried it."[e]

[msg MSG_93 [Yukari]]
[s][bup 2 1 65535 0]Wha!? But, it's so good![n][w][e]
[s]...I guess everybody's tastes are[n]different.[n][w][e]

[msg MSG_94 [ ]]
[s]> Yukari seems disappointed.[n][w][e]

[msg MSG_95 [Yukari]]
[s][bup 2 2 65535 0]Isn't it amazing!?[n][w][e]
[s]I just love the outer skin![n][w][e]
[s]Wow, even our tastes are similar...[n][w][e]

[msg MSG_96 [ ]]
[s][f 5 13 0 15 2]> Yukari seems excited...[n][w][e]

[msg MSG_97 [Yukari]]
[s][bup 2 1 65535 0]Are you serious!? That's crazy.[n][w][e]
[s]I think you're the first person[n]I've met who's never tried it...[n][w][e]

[msg MSG_98 [ ]]
[s]> Yukari seems a bit uneasy...[n][w][e]

[msg MSG_99 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to[n]the dorm.[n][w][e]

[msg MSG_84_02]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time with[n]Yukari.[n][w][e]

[msg MSG_85_02 [Yukari]]
[s][bup 2 2 65535 0][f 6 1 1 0 2 1]Wow, it's already getting dark out...[n][w][e]
[s]I didn't realize we were in there so[n]long.[n][w][e]

[msg MSG_88_02]
[s]> Yukari seems to be enjoying herself.[n][w][e]

[msg MSG_89_02 [Yukari]]
[s][bup 2 1 65535 0]Have you ever noticed how many manga[n]are about high school students who[n]get drawn into some kind of battle?[n][w][e]
[s]Maybe they'll make a manga about us...[n][w][e]

[msg MSG_90_02 [ ]]
[s]> Yukari has a troubled look on her[n]face.[n][w][e]

[msg MSG_91_02 [Yukari]]
[s][bup 2 1 65535 0]But, no one knows about us, huh...[n][w][e]

[sel SEL092_02 top]
[s]"You look like a hero."[e]
[s]"Of course not."[e]
[s]"Some people do."[e]

[msg MSG_93_02 [Yukari]]
[s][bup 2 5 65535 0]What's that s'posed to mean?[n][w][e]
[s]Just because I'm in the Archery Club?[n][w][e]
[s]Sure, my arms are pretty strong...[n][w][e]
[s][bup 2 3 65535 0]...but it's not something I want[n]people to notice![n][w][e]

[msg MSG_94_02 [ ]]
[s]> Yukari seems mad.[n][w][e]
[s]> Your relationship seems to be stuck[n]in a rut.[n][w][e]

[msg MSG_95_02 [Yukari]]
[s][bup 2 2 65535 0]R-Right.[n][w][e]
[s]I'm thinking too much, huh...[n][w][e]
[s]I guess I'll just have to think of it[n]as a secret.[n][w][e]

[msg MSG_96_02 [ ]]
[s][f 5 13 0 15 2]> Yukari seems happy.[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_97_02 [Yukari]]
[s][bup 2 2 65535 0]Like who...?[n][w][e]
[s]You mean like Officer Kurosawa?[n][w][e]
[s]That reminds me... I hate to say this,[n]especially since he's been helping us,[n]but...[n][w][e]
[s]Don'tcha think he's kinda scary[n]looking? Especially his eyes. Don't[n]tell anyone I said that, though.[n][w][e]
[s]Well, it's nice to know that at least[n]someone knows what we've been doing.[n][w][e]

[msg MSG_98_02 [ ]]
[s][f 5 13 0 30 2]> You understand Yukari a little[n]better now.[n][w][e]
[s]> Today, the two of you became a lot[n]closer.[n][w][e]

[msg MSG_99_02 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_100]
[s]> Iwatodai strip mall,[n]Sweet Shop...[n][w][e]
[s]> You're having a good time with[n]Fuuka.[n][w][e]

[msg MSG_101 [Fuuka]]
[s][bup 6 1 65535 0]The anmitsu tastes absolutely[n]wonderful.[n][w][e]
[s][bup 6 2 65535 0]Mmm... The sweet taste of[n]the azuki bean paste...[n]I think I'm hooked![n][w][e]

[msg MSG_102]
[s]> Fuuka seems to be enjoying her[n]day off...[n][w][e]

[msg MSG_103 [Fuuka]]
[s][bup 6 1 65535 0]By the way, [f 4 2]-kun...[n][w][e]

[msg MSG_104 [ ]]
[s]> Fuuka seems serious.[n][w][e]

[msg MSG_105 [Fuuka]]
[s][bup 6 1 65535 0]Do you like sweets?[n][w][e]

[sel SEL106 top]
[s]"I love them."[e]
[s]"No, not really."[e]
[s]"Never thought about it."[e]

[msg MSG_107 [Fuuka]]
[s][bup 6 2 65535 0]Really? So do I.[n][w][e]
[s]That makes me happy. *giggle*[n][w][e]
[s]People say sugar makes you fat,[n]but it actually has some health[n]benefits...[n][w][e]
[s]In fact, glucose is like fuel[n]for your brain.[n][w][e]
[s]It's like when you get hungry[n]because you've been using your[n]mind all day...[n][w][e]
[s]The glucose in your body is being[n]used up and your blood sugar is low.[n][w][e]
[s]And, did you know...[n][w][e]

[msg MSG_108 [ ]]
[s][f 5 13 0 30 6]> Fuuka seems to be having fun.[n][w][e]
[s]> Your relationship with her[n]has grown dramatically...[n][w][e]

[msg MSG_109 [Fuuka]]
[s][bup 6 1 65535 0]Oh...[n][w][e]
[s]That's too bad...[n]I love sweets...[n][w][e]
[s]And, I thought that if you had[n]similar tastes in food, I could[n]make you lunch sometime, but...[n][w][e]
[s]*sigh* I guess everyone's different.[n][w][e]

[msg MSG_110 [ ]]
[s]> Fuuka seems a little sad...[n][w][e]
[s]> Your relationship with her seems to[n]be stuck in a rut...[n][w][e]

[msg MSG_111 [Fuuka]]
[s][bup 6 1 65535 0][f 4 2]-kun, are you[n]the type of person who doesn't[n]have a favorite type of food?[n][w][e]
[s]Well, that's how I am.[n][w][e]
[s]You know how some people go crazy[n]over sweets?[n][w][e]
[s]I could never understand why[n]they do that...[n][w][e]
[s][bup 6 2 65535 0]*giggle* I guess we're alike[n]in that way.[n][w][e]

[msg MSG_112 [ ]]
[s][f 5 13 0 15 6]> Fuuka smiled.[n][w][e]
[s]> You seem to understand her[n]a little better now...[n][w][e]

[msg MSG_113 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to[n]the dorm.[n][w][e]

[msg MSG_100_02]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_101_02 [Fuuka]]
[s][bup 6 1 65535 0]What a beautiful day![n][w][e]
[s]I'm surprised there are so many[n]people here today...[n][w][e]
[s]I thought only Port Island got this[n]crowded.[n][w][e]
[s]You know, I've only been coming here[n]since I moved into the dorms,[n]but I really like it.[n][w][e]
[s]It's so close to us. We should come[n]here more often.[n][w][e]

[msg MSG_102_02]
[s]> Fuuka seems to be enjoying herself.[n][w][e]

[msg MSG_103_02 [Fuuka]]
[s][bup 6 1 65535 0]Um, [f 4 2]-kun...[n][w][e]

[msg MSG_104_02 [ ]]
[s]> Fuuka seems nervous...[n][w][e]

[msg MSG_105_02 [Fuuka]]
[s][bup 6 1 65535 0]What do you usually do on[n]your days off?[n][w][e]

[sel SEL106_02 top]
[s]"Stay in my room."[e]
[s]"Spend time with friends."[e]
[s]"Um, I don't remember."[e]

[msg MSG_107_02 [Fuuka]]
[s][bup 6 5 65535 0]Oh, so you like staying inside,[n]huh?[n][w][e]
[s]I didn't know that...[n][w][e]
[s][bup 6 2 65535 0]I like to be indoors. too.[n][w][e]
[s]...Well, I guess you could probably[n]tell that by looking at me...[n][w][e]
[s]I'm happy we have that in common...[n][w][e]

[msg MSG_108_02 [ ]]
[s][f 5 13 0 15 6]> Fuuka seems uneasy.[n][w][e]
[s]> Today, you learned something new[n]about Fuuka...[n][w][e]

[msg MSG_109_02 [Fuuka]]
[s][bup 6 2 65535 0]You seem to have a lot of friends.[n][w][e]
[s]I don't really have that many...[n][w][e]
[s]*sigh* I wish you and I could[n]spend more time together,[n][f 4 2]-kun...[n][w][e]

[msg MSG_110_02 [ ]]
[s][f 5 13 0 30 6]> Fuuka seems embarrassed.[n][w][e]
[s]> Today, you became a lot closer[n]to Fuuka...[n][w][e]

[msg MSG_111_02 [Fuuka]]
[s][bup 6 1 65535 0]...Oh.[n][w][e]
[s]......[n][w][e]
[s]Um...[n][w][e]
[s]I'm sorry... Was I not supposed[n]to ask you that...?[n][w][e]

[msg MSG_112_02 [ ]]
[s]> Fuuka is worried she said[n]something wrong.[n][w][e]
[s]> Your relationship seems to be stuck[n]in a rut.[n][w][e]

[msg MSG_113_02 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decided to go back to[n]the dorm.[n][w][e]

[msg MSG_100_03]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time with[n]Fuuka.[n][w][e]

[msg MSG_101_03 [Fuuka]]
[s][bup 6 1 65535 0][f 6 1 1 0 6 11]Have you ever read "The Titanium Chef,"[n][f 4 2]-kun?[n][w][e]
[s]I've been wondering how it was going[n]to end...[n][w][e]
[s]I'm relieved now that I was finally[n]able to finish it.[n][w][e]
[s]I'm amazed how good the food in a[n]manga can look.[n][w][e]

[msg MSG_102_03]
[s]> Fuuka seems to be enjoying herself.[n][w][e]

[msg MSG_103_03 [Fuuka]]
[s][bup 6 1 65535 0]By the way, [f 4 2]-kun...[n][w][e]

[msg MSG_104_03 [ ]]
[s]> Fuuka seems a bit nervous.[n][w][e]

[msg MSG_105_03 [Fuuka]]
[s][bup 6 1 65535 0]Have you ever filleted a fish before?[n][w][e]

[sel SEL106_03 top]
[s]"Yeah, I'm not too bad."[e]
[s]"Never tried it."[e]
[s]"I don't like fish."[e]

[msg MSG_107_03 [Fuuka]]
[s][bup 6 2 65535 0]Wow, really?[n][w][e]
[s]I can't stand touching raw fish![n]They're so slimy! And stinky too![n][w][e]
[s]Plus, I'm clumsy with a knife...[n][w][e]
[s]You'll have to teach me how to do it[n]the right way, [f 4 2]-kun.[n][w][e]

[msg MSG_108_03 [ ]]
[s][f 5 13 0 30 6]> Fuuka seems impressed.[n][w][e]
[s]> Today, the two of you became a lot[n]closer.[n][w][e]

[msg MSG_109_03 [Fuuka]]
[s][bup 6 1 65535 0]...Not even once?[n][w][e]
[s]But, I thought you were in Home[n]Economics, [f 4 2]-kun...[n][w][e]
[s][bup 6 4 65535 0]*sigh* I was hoping you'd be able[n]to help me, since I'm clumsy with[n]a knife.[n][w][e]
[s]How am I going to get better at[n]cooking if I can't even fillet a[n]fish?[n][w][e]

[msg MSG_110_03 [ ]]
[s]> Fuuka seems depressed.[n][w][e]
[s]> Your relationship seems to be stuck[n]in a rut.[n][w][e]

[msg MSG_111_03 [Fuuka]]
[s][bup 6 1 65535 0]...Oh, really?[n][w][e]
[s]Well, these days, I guess there are[n]plenty of other things to choose from.[n][w][e]

[msg MSG_112_03 [ ]]
[s][f 5 13 0 15 6]> Fuuka is laughing uncomfortably.[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_113_03 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_114]
[s]> Iwatodai strip mall,[n]Beef Bowl Shop...[n][w][e]
[s]> You're having a good time with[n]Mitsuru.[n][w][e]

[msg MSG_115 [Mitsuru]]
[s][bup 4 1 65535 0]I'm sorry for making you come to a[n]place like this on your day off.[n][w][e]
[s]It probably doesn't mean that much[n]to you...[n][w][e]
[s]But for me, it's a treat...[n][w][e]
[s]I never thought something as simple[n]as beef and white rice would taste[n]so good.[n][w][e]

[msg MSG_116]
[s]> Mitsuru seems to be enjoying[n]herself.[n][w][e]

[msg MSG_117 [Mitsuru]]
[s][bup 4 1 65535 0]There is one thing that's worrying me,[n]though...[n][w][e]

[msg MSG_118 [ ]]
[s]> Mitsuru seems a little nervous.[n][w][e]

[msg MSG_119 [Mitsuru]]
[s][bup 4 1 65535 0]Don't women normally refrain from[n]eating this kind of food?[n][w][e]
[s]...Or is it just my imagination?[n][w][e]

[sel SEL120 top]
[s]"You're imagining it."[e]
[s]"It's possible."[e]
[s]"Don't worry about it."[e]

[msg MSG_121 [Mitsuru]]
[s][bup 4 1 65535 0]I-I see. If you say so...[n][w][e]

[msg MSG_122 [ ]]
[s]> Mitsuru still seems worried.[n][w][e]
[s]> Your relationship seems to be stuck[n]in a rut.[n][w][e]

[msg MSG_123 [Mitsuru]]
[s][bup 4 2 65535 0]That's what I thought.[n][w][e]
[s]...W-Well, I'm in good company, so I[n]might as well enjoy my meal.[n][w][e]
[s]In fact, from now on, I'm going to[n]enjoy every meal without worrying[n]about such things.[n][w][e]

[msg MSG_124 [ ]]
[s][f 5 13 0 15 4]> Mitsuru seems happy.[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_125 [Mitsuru]]
[s][bup 4 1 65535 0]Y-You're right.[n][w][e]
[s]I'm overthinking things.[n][w][e]
[s][bup 4 4 65535 0]But lately, I've begun to realize[n]what a sheltered life I lead.[n][w][e]
[s][bup 4 2 65535 0]I want to change that...[n]So thank you, [f 4 1].[n][w][e]

[msg MSG_126 [ ]]
[s][f 5 13 0 30 4]> Mitsuru seems happy.[n][w][e]
[s]> Today, the two of you grew much[n]closer.[n][w][e]

[msg MSG_127 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_114_02]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time with[n]Mitsuru.[n][w][e]

[msg MSG_115_02 [Mitsuru]]
[s][bup 4 2 65535 0]I didn't realize how many different[n]types of manga there are...[n][w][e]

[msg MSG_116_02]
[s]> Mitsuru seems to be enjoying[n]herself.[n][w][e]

[msg MSG_117_02 [Mitsuru]]
[s][bup 4 1 65535 0]I have a question...[n][w][e]

[msg MSG_118_02 [ ]]
[s]> Mitsuru has a curious look on her[n]face.[n][w][e]

[msg MSG_119_02 [Mitsuru]]
[s][bup 4 1 65535 0]Why do people go to manga cafes?[n][w][e]
[s]You can't borrow any of the books,[n]like at a library...[n][w][e]
[s]...and you have to pay admission[n]to get in.[n][w][e]
[s]Since manga aren't that expensive,[n]why don't people just buy them?[n][w][e]

[sel SEL120_02 top]
[s]"It's a nice environment."[e]
[s]"It's a little cheaper."[e]
[s]"Lack of storage space."[e]

[msg MSG_121_02 [Mitsuru]]
[s][bup 4 2 65535 0]I see...[n][w][e]
[s]Well, they do let you eat in here,[n]and it's open late.[n][w][e]

[msg MSG_122_02 [ ]]
[s][f 5 13 0 15 4]> Mitsuru seems to understand.[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_123_02 [Mitsuru]]
[s][bup 4 1 65535 0]I suppose that's true.[n][w][e]
[s]But, there's something nice about[n]owning a book, especially one you[n]really love.[n][w][e]
[s][bup 4 2 65535 0]In that case, it's worth buying no[n]matter what the price.[n][w][e]

[msg MSG_124_02 [ ]]
[s]> Mitsuru seems to have made up her[n]mind.[n][w][e]
[s]> Your relationship seems to be stuck[n]in a rut.[n][w][e]

[msg MSG_125_02 [Mitsuru]]
[s][bup 4 2 65535 0]That's understandable.[n][w][e]
[s]From that perspective, the cafe is[n]like your own personal library.[n][w][e]
[s]Even though you can't borrow the[n]manga, you can read them whenever[n]you want.[n][w][e]
[s]That's an interesting way to look at it.[n][w][e]

[msg MSG_126_02 [ ]]
[s][f 5 13 0 30 4]> Mitsuru seems somewhat impressed.[n][w][e]
[s]> Today, the two of you became a lot[n]closer.[n][w][e]

[msg MSG_127_02 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_142]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_143 [Yuko]]
[s][bup 31 161 65535 0]I know we see each other all the time[n]at school, but it's nice to spend time[n]together like this...[n][w][e]

[msg MSG_144]
[s]> Yuko seems to be checking you out.[n][w][e]

[msg MSG_145 [Yuko]]
[s][bup 31 161 65535 0]You have pretty good taste in clothes,[n][f 4 2].[n][w][e]
[s]Kaz always wears a jersey, even when[n]he's not at practice...[n][w][e]

[msg MSG_146 [ ]]
[s]> Yuko seems to look a little[n]different today.[n][w][e]

[msg MSG_147 [Yuko]]
[s][bup 31 161 65535 0]What about me?[n][w][e]

[sel SEL148 top]
[s]"You look cute."[e]
[s]"You look sexy."[e]
[s]"You look smart."[e]

[msg MSG_149 [Yuko]]
[s][bup 31 161 65535 0]Cute, huh?[n][w][e]
[s]Isn't that what you'd say about a little[n]kid?[n][w][e]
[s][bup 31 162 65535 0]Oh, well. I'll take it as a compliment.[n][w][e]

[msg MSG_150 [ ]]
[s][f 5 13 0 15 31]> Yuko seems amused.[n][w][e]
[s]> You learned something new about her[n]today.[n][w][e]

[msg MSG_151 [Yuko]]
[s][bup 31 163 65535 0]Hey... Are you being sarcastic?[n][w][e]
[s]I know I'm a tomboy, but you don't[n]have to make fun of me...[n][w][e]

[msg MSG_152 [ ]]
[s]> Yuko seems upset.[n][w][e]
[s]> Your relationship seems to be stuck[n]in a rut.[n][w][e]

[msg MSG_153 [Yuko]]
[s][bup 31 162 65535 0]For real?[n][w][e]
[s]I didn't want you to get the wrong[n]impression, after what I said about[n]my test the other day.[n][w][e]
[s]I... How should I say this? I may not[n]have the best grades, but I'm not[n]stupid.[n][w][e]

[msg MSG_154 [ ]]
[s][f 5 13 0 30 31]> Yuko seems happy.[n][w][e]
[s]> Today, you two became a lot closer.[n][w][e]

[msg MSG_155 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_156]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time with[n]Chihiro.[n][w][e]

[msg MSG_157 [Chihiro]]
[s][bup 25 161 65535 0]Sorry to make you wait so long...[n][w][e]
[s]Once I start reading, I can't stop.[n][w][e]

[msg MSG_158]
[s]> Chihiro seems to feel guilty.[n][w][e]

[msg MSG_159 [Chihiro]]
[s][bup 25 161 65535 0]This was the only place I could think[n]of where it doesn't cost much and we[n]can relax.[n][w][e]

[msg MSG_160 [ ]]
[s]> Chihiro is averting her gaze.[n][w][e]

[msg MSG_161 [Chihiro]]
[s][bup 25 161 65535 0]But, maybe this place wasn't such[n]a good idea.[n][w][e]
[s]There's not much point in getting[n]together if all we're going to do[n]is read, right?[n][w][e]

[sel SEL162 top]
[s]"True."[e]
[s]"It's fun, actually."[e]
[s]"There's always next time."[e]

[msg MSG_163 [Chihiro]]
[s][bup 25 164 65535 0]S-Sorry... I-I didn't mean to ruin[n]your day off.[n][w][e]
[s]Next time, I'll-- Oh! I don't mean to[n]assume...[n][w][e]

[msg MSG_164 [ ]]
[s]> Chihiro seems to be distracted.[n][w][e]
[s]> Your relationship seems to be stuck[n]in a rut.[n][w][e]

[msg MSG_165 [Chihiro]]
[s][bup 25 162 65535 0]I-I'm glad to hear that... I thought[n]I was the only one.[n][w][e]
[s]But from now on, I'm going to come[n]here alone. When I'm with you, I want[n]to have time to talk.[n][w][e]

[msg MSG_166 [ ]]
[s][f 5 13 0 15 25]> Chihiro is blushing.[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_167 [Chihiro]]
[s][bup 25 162 65535 0]Th-Then, um...! Does that mean...!?[n][w][e]
[s][bup 25 161 65535 0]S-Sorry. I'm getting ahead of myself.[n][w][e]

[msg MSG_168 [ ]]
[s][f 5 13 0 30 25]> Chihiro seems excited.[n][w][e]
[s]> You understand her a lot better now.[n][w][e]

[msg MSG_169 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_156_02]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_157_02 [Chihiro]]
[s][bup 25 161 65535 0]Phew... Nobody bought that[n]collection of illustrations...[n][w][e]
[s][bup 25 164 65535 0]But...[n][w][e]

[msg MSG_158_02]
[s]> Chihiro looks scared.[n][w][e]

[msg MSG_159_02 [Chihiro]]
[s][bup 25 164 65535 0]I'm worried about the missing[n]money...[n][w][e]

[msg MSG_160_02 [ ]]
[s]> Chihiro's expression darkened.[n][w][e]

[msg MSG_161_02 [Chihiro]]
[s][bup 25 164 65535 0]I hope it was just some kind of[n]mistake... [n][w][e]
[s]It's sad to think that there[n]might be a thief in our school...[n][w][e]

[sel SEL162_02 top]
[s]"There's no thief."[e]
[s]"How much was it?"[e]
[s]"Don't make accusations."[e]

[msg MSG_163_02 [Chihiro]]
[s][bup 25 161 65535 0]...N-No, you're right.[n]There couldn't be.[n][w][e]
[s]I should follow your example more,[n][f 4 2]-san...[n][w][e]

[msg MSG_164_02 [ ]]
[s][f 5 13 0 30 25]> Chihiro seems impressed.[n][w][e]
[s]> Today, you two became a lot[n]closer...[n][w][e]

[msg MSG_165_02 [Chihiro]]
[s][bup 25 164 65535 0]Does that really matter,[n][f 4 2]-san?[n][w][e]
[s]I know this is not your problem,[n]but please try to take it[n]seriously...[n][w][e]

[msg MSG_166_02 [ ]]
[s]> Chihiro seems upset.[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut...[n][w][e]

[msg MSG_167_02 [Chihiro]]
[s][bup 25 164 65535 0]It might sound like I'm trying to[n]find someone to blame, but that's[n]not the case...[n][w][e]
[s][bup 25 161 65535 0]I was just thinking out loud.[n]It's not like I really believe[n]someone intentionally stole it.[n][w][e]

[msg MSG_168_02 [ ]]
[s][f 5 13 0 15 25]> Chihiro nodded her head firmly.[n][w][e]
[s]> Today, you learned something new[n]about her...[n][w][e]

[msg MSG_169_02 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_170]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_171 [Kazushi]]
[s][bup 30 102 65535 0]Dude... you know how to dress[n]to impress.[n][w][e]

[msg MSG_172]
[s]> Kazushi seems to be checking out[n]your clothes.[n][w][e]

[msg MSG_173 [Kazushi]]
[s][bup 30 101 65535 0]I wanna get some new threads,[n]but I can't waste time on that[n]now.[n][w][e]
[s]I just wear my warm up suits on[n]the weekend. It puts me in the[n]right mindset, too.[n][w][e]

[msg MSG_174 [ ]]
[s]> Kazushi seems proud of himself.[n][w][e]

[msg MSG_175 [Kazushi]]
[s][bup 30 102 65535 0]I'm ready to go, 24/7, ya know?[n]It's called "dedication," man.[n][w][e]

[sel SEL176 top]
[s]"That's crazy."[e]
[s]"Whatever."[e]
[s]"Aren't you hot in that?"[e]

[msg MSG_177 [Kazushi]]
[s][bup 30 102 65535 0]Of course it is, dude. I even[n]train in my dreams...[n][w][e]
[s]I'll do whatever it takes to win.[n][w][e]

[msg MSG_178 [ ]]
[s][f 5 13 0 30 30]> Kazushi seems to be having fun.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_179 [Kazushi]]
[s][bup 30 101 65535 0]Dude, don't get cocky just because[n]you beat me once...[n][w][e]
[s]You better watch out, cuz next time[n]you're goin' down![n][w][e]

[msg MSG_180 [ ]]
[s][f 5 13 0 15 30]> Kazushi seems to be having fun.[n][w][e]
[s]> Today, you learned something new[n]about him...[n][w][e]

[msg MSG_181 [Kazushi]]
[s][bup 30 101 65535 0]Yuko asked me the same thing.[n][w][e]
[s]Man, I thought as a guy you'd[n]understand... but I guess not.[n][w][e]

[msg MSG_182 [ ]]
[s]> Kazushi seems disappointed.[n][w][e]
[s]> Your friendship seems to be[n]stuck in a rut...[n][w][e]

[msg MSG_183 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_170170]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_171170 [Kazushi]]
[s][bup 30 101 65535 0]Sorry, but I need your help[n]again...[n][w][e]

[msg MSG_1722323]
[s]> Kazushi seems to be feeling[n]guilty.[n][w][e]

[msg MSG_1732323 [Kazushi]]
[s][bup 30 101 65535 0]I'm going to my sister's house[n]today, and I wanna get something[n]for my nephew...[n][w][e]
[s]But, I'm not sure what to get him.[n]I thought you could come along and[n]help me pick something out.[n][w][e]

[msg MSG_1742323 [ ]]
[s]> Kazushi seems kind of[n]embarrassed.[n][w][e]

[msg MSG_1752323 [Kazushi]]
[s][bup 30 101 65535 0]What would be good for a 5-year[n]old kid who's injured his leg...?[n][w][e]
[s]Any ideas?[n][w][e]

[sel SEL1762323 top]
[s]"Running shoes."[e]
[s]"A game."[e]
[s]"Clothes."[e]

[msg MSG_1772323 [Kazushi]]
[s][bup 30 103 65535 0]Dude, I just told you...[n]His leg is injured.[n][w][e]
[s]What the hell's wrong with you?[n]Maybe it was a mistake to ask[n]for your help.[n][w][e]

[msg MSG_1782323 [ ]]
[s]> Kazushi seems annoyed.[n][w][e]
[s]> Your friendship seems to be[n]stuck in a rut...[n][w][e]

[msg MSG_1792323 [Kazushi]]
[s][bup 30 102 65535 0]That makes sense... That way,[n]he won't be bored at home.[n][w][e]
[s]But, games cost a lot of money...[n]Ah, what the heck... He's my[n]nephew, after all.[n][w][e]

[msg MSG_1802323 [ ]]
[s][f 5 13 0 30 30]> Kazushi seems to be having[n]a great time.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1812323 [Kazushi]]
[s][bup 30 104 65535 0]So, we're gonna go to the kid's[n]section, just the two of us...?[n][w][e]
[s]Isn't that kinda weird, man?[n]...Ah, what the heck. It's for[n]my nephew's sake.[n][w][e]

[msg MSG_1822323 [ ]]
[s][f 5 13 0 15 30]> Kazushi seems flustered.[n][w][e]
[s]> Today, you learned something new[n]about him...[n][w][e]

[msg MSG_1832323 [ ]]
[s]> You decide to go shopping with[n]Kazushi and then go back to the[n]dorm.[n][w][e]

[msg MSG_241]
[s]> Iwatodai strip mall,[n]Beef Bowl Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Keisuke.[n][w][e]

[msg MSG_242 [Keisuke]]
[s][bup 23 161 65535 0]I've seen this before on a commercial,[n]but it looks so good in person![n][w][e]

[msg MSG_243]
[s]> Keisuke seems excited.[n][w][e]

[msg MSG_244 [Keisuke]]
[s][bup 23 162 65535 0][f 6 1 1 0 23 11]That was the first time I ever ate[n]a beef bowl! I didn't expect it to[n]taste that good![n][w][e]

[msg MSG_245 [ ]]
[s]> Keisuke is even more excited.[n][w][e]

[msg MSG_246 [Keisuke]]
[s][bup 23 161 65535 0]My parents always told me I should never[n]put anything over rice...[n][w][e]
[s]Their rules are so annoying...[n]We would never have beef bowls at home.[n][w][e]

[sel SEL247 top]
[s]"Your first and last time."[e]
[s]"Let's eat here again."[e]
[s]"Maybe you should ask them."[e]

[msg MSG_248 [Keisuke]]
[s][bup 23 161 65535 0]O-Oh no...! I'll never be able to eat[n]a beef bowl ever again?[n][w][e]
[s]If I'd known that, I'd have eaten it[n]more slowly...[n][w][e]
[s][bup 23 163 65535 0]Wait a second... I can just come here[n]again if I want another beef bowl![n]Don't scare me like that.[n][w][e]

[msg MSG_249 [ ]]
[s]> Keisuke seems a little annoyed.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_250 [Keisuke]]
[s][bup 23 162 65535 0]Yeah! Let's come here again![n][w][e]
[s]Just give me a call! Anytime![n][w][e]

[msg MSG_251 [ ]]
[s][f 5 13 0 30 23]> Keisuke seems excited.[n][w][e]
[s]> Your friendship has grown stronger.[n][w][e]

[msg MSG_252 [Keisuke]]
[s][bup 23 162 65535 0]I could ask our maid to make it for me.[n]But, she'd have to keep it a secret...[n]and no one could see me eating it...[n][w][e]
[s]That seems like a lot of sneaking[n]around just to eat a beef bowl...[n][w][e]

[msg MSG_253 [ ]]
[s][f 5 13 0 15 23]> Keisuke seems to be thinking.[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_254 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_241_02]
[s]> Iwatodai strip mall,[n]Sweet Shop...[n][w][e]
[s]> You're having a good time[n]hanging out with Keisuke.[n][w][e]

[msg MSG_242_02 [Keisuke]]
[s][bup 23 162 65535 0]It may be a bit much to say that[n]I feel a sense of national pride[n]when I eat Japanese sweets, huh?[n][w][e]

[msg MSG_243_02]
[s]> Keisuke seems embarrassed.[n][w][e]

[msg MSG_244_02 [Keisuke]]
[s][bup 23 161 65535 0]Well, I decided that I'm going to[n]study overseas...[n][w][e]
[s]So that means I won't be seeing you[n]anymore...[n][w][e]

[msg MSG_245_02 [ ]]
[s]> Keisuke is looking out into the[n]distance.[n][w][e]

[msg MSG_246_02 [Keisuke]]
[s][bup 23 161 65535 0]O-Oh, I didn't mean it that way,[n]it's just...[n][w][e]
[s]I've always been jealous of guys[n]who have brothers... You know,[n]since I don't have any...[n][w][e]
[s]So... would... would you mind[n]calling me... Brother...?[n][w][e]

[sel SEL247_02 top]
[s]"How about Kid Brother?"[e]
[s]"But, you're my senpai."[e]
[s]"Okay, Brother."[e]

[msg MSG_248_02 [Keisuke]]
[s][bup 23 161 65535 0]K-Kid? But, I'm older than you...[n][w][e]
[s]Well, I guess I'm not very reliable,[n]so I can see why you would think of[n]me like that...[n][w][e]

[msg MSG_249_02 [ ]]
[s]> Keisuke seems depressed.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_250_02 [Keisuke]]
[s][bup 23 161 65535 0]Th-That's true, but...[n][w][e]
[s]*sigh* I guess I should express[n]myself more clearly. Well, at least I[n]learned something before I left...[n][w][e]

[msg MSG_251_02 [ ]]
[s][f 5 13 0 15 23]> Keisuke is nodding to himself.[n][w][e]
[s]> You learned a little more about[n]him today...[n][w][e]

[msg MSG_252_02 [Keisuke]]
[s][bup 23 161 65535 0]Brother... Oh, I love how that[n]sounds...[n][w][e]
[s][bup 23 162 65535 0]H-Hey, [f 4 2]-kun,[n]can you say it again?[n][w][e]

[msg MSG_253_02 [ ]]
[s][f 5 13 0 30 23]> Keisuke seems really happy.[n][w][e]
[s]> Your relationship with him has[n]grown dramatically...[n][w][e]

[msg MSG_254_02 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to[n]the dorm.[n][w][e]

[msg MSG_326]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time hanging[n]out with Bebe.[n][w][e]

[msg MSG_327 [Bebe]]
[s][bup 34 161 65535 0]I like zis place... I feel a little[n]better now...[n][w][e]
[s]......[n][w][e]
[s]ハァ…[n]*sigh*[n][w][e]

[msg MSG_328]
[s]> It seems like Bebe has no energy.[n][w][e]

[msg MSG_329 [Bebe]]
[s][bup 34 163 65535 0]I always used to call my aunt on ze[n]weekend and 'olidays...[n][w][e]
[s]If she was still alive, I would call[n]'er today...[n][w][e]

[msg MSG_330 [ ]]
[s]> Bebe seems shocked by the death of[n]his aunt.[n][w][e]

[msg MSG_331 [Bebe]]
[s][bup 34 161 65535 0]I zink zat I miss my 'ome...[n][w][e]

[sel SEL332 top]
[s]"Are you gonna go back?"[e]
[s]"Stay in Japan."[e]
[s]"What about the funeral?"[e]

[msg MSG_334 [Bebe]]
[s][bup 34 163 65535 0]Zat eez not what I want.[n][w][e]
[s]I 'ave a bad feeling zat I will not be[n]able to come back if I go...[n][w][e]

[msg MSG_339 [ ]]
[s]> Bebe seems sad.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_336 [Bebe]]
[s][bup 34 162 65535 0]I would love to do zat![n][w][e]
[s]I 'ave a bad feeling zat I will not be[n]able to come back if I go...[n][w][e]

[msg MSG_337 [ ]]
[s][f 5 13 0 30 34]> Bebe seems deeply touched.[n][w][e]
[s]> Your friendship has grown stronger.[n][w][e]

[msg MSG_338 [Bebe]]
[s][bup 34 162 65535 0]Oh, you are zinking about my aunt![n]Zank you so much! Arigato![n][w][e]
[s]I want to go to ze funeral, but...[n]I can't...[n][w][e]
[s]I 'ave a bad feeling zat I will not be[n]able to come back if I do...[n][w][e]

[msg MSG_335 [ ]]
[s][f 5 13 0 15 34]> Bebe seems deeply touched.[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_340 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_326_02]
[s]> Iwatodai strip mall,[n]Sweet Shop...[n][w][e]
[s]> You're having fun hanging out[n]with Bebe.[n][w][e]

[msg MSG_327_02 [Bebe]]
[s][bup 34 162 65535 0][f 6 1 1 0 34 11]Oishii! Zat was delicious! [n][w][e]

[msg MSG_328_02]
[s]> Bebe seems happy...[n][w][e]

[msg MSG_329_02 [Bebe]]
[s][bup 34 161 65535 0]Japan eez ze only place where you[n]can taste ze true beauty of sugar![n][w][e]

[msg MSG_330_02 [ ]]
[s]> Bebe seems to love Japanese[n]desserts.[n][w][e]

[msg MSG_331_02 [Bebe]]
[s][bup 34 161 65535 0]Azuki eez so good![n][w][e]
[s]What eez it made of? It looks[n]like insect eggs...[n][w][e]

[sel SEL332_02 top]
[s]"I don't know."[e]
[s]"It IS bug eggs."[e]
[s]"It's beans."[e]

[msg MSG_334_02 [Bebe]]
[s][bup 34 163 65535 0]So, you don't know eizer,[n][f 4 2]-sama...?[n][w][e]
[s]Zat eez a big problem! It eez[n]a mystery...[n][w][e]

[msg MSG_335_02 [ ]]
[s]> Bebe seems puzzled.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_338_02 [Bebe]]
[s][bup 34 163 65535 0]Hontou!? I was right!?[n][w][e]
[s][bup 34 162 65535 0]I have learned somezing new about[n]Nihon![n][w][e]

[msg MSG_339_02 [ ]]
[s][f 5 13 0 15 34]> Bebe seems happy...[n][w][e]
[s]> You understand him a little[n]better now...[n][w][e]

[msg MSG_336_02 [Bebe]]
[s][bup 34 162 65535 0]Oh! I didn't know zat zere eez[n]a bean zat eez small and red![n][w][e]
[s]I have learned somezing new about[n]Nihon![n][w][e]

[msg MSG_337_02 [ ]]
[s][f 5 13 0 30 34]> Bebe seems happy.[n][w][e]
[s]> Your friendship has grown[n]dramatically...[n][w][e]

[msg MSG_340_02 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to[n]the dorm.[n][w][e]

[msg MSG_326_03]
[s]> Iwatodai strip mall,[n]Beef Bowl Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Bebe.[n][w][e]

[msg MSG_327_03 [Bebe]]
[s][bup 34 162 65535 0]Umiushi Bowl... Zat was delicious![n]Oishii![n][w][e]

[msg MSG_328_03]
[s]> Bebe seems satisfied.[n][w][e]

[msg MSG_329_03 [Bebe]]
[s][bup 34 162 65535 0][f 6 1 1 0 34 11]Zat kind of meal goes well wiz rice![n][w][e]

[msg MSG_330_03 [ ]]
[s]> Bebe seems interested in Japanese[n]cuisine.[n][w][e]

[msg MSG_331_03 [Bebe]]
[s][bup 34 161 65535 0]What do you like to eat wiz rice,[n][f 4 2]-sama?[n][w][e]

[sel SEL332_03 top]
[s]"I don't eat rice."[e]
[s]"Sushi."[e]
[s]"Curry."[e]

[msg MSG_336_03 [Bebe]]
[s][bup 34 163 65535 0]Honto!? Really!? Zat eez a shame.[n]'ow can you be Japanese and not eat[n]rice?[n][w][e]

[msg MSG_337_03 [ ]]
[s]> Bebe seems a little angry.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_334_03 [Bebe]]
[s][bup 34 162 65535 0]Sou desu ne! Zat's right! If you are[n]Japanese, you must eat sushi![n][w][e]

[msg MSG_339_03 [ ]]
[s][f 5 13 0 30 34]> Bebe seems pleased.[n][w][e]
[s]> Your friendship has grown stronger.[n][w][e]

[msg MSG_338_03 [Bebe]]
[s][bup 34 162 65535 0]Zat eez an excellent dish![n][w][e]
[s]But I zink sushi is ze best. If you[n]are Japanese, you must eat sushi![n][w][e]

[msg MSG_335_03 [ ]]
[s][f 5 13 0 15 34]> Bebe seems pleased.[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_340_03 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg SYS_000 [ ]]
[s]> You recall that you have something[n]you can give as a present...[n][w][e]

[sel SYS_SEL_000 top]
[s]Give a present[e]
[s]Don't give a present[e]

[msg SYS_001 [ ]]
[s]> What kind of present should you give?[n][w][e]

[sel SYS_SEL_001 top]
[s]Flowers[e]
[s]Fashion[e]
[s]Antique[e]
[s]Other[e]
[s]Never mind[e]

[sel SYS_SEL_001F top]
[s]Handmade sweets[e]
[s]Handmade goods[e]
[s]Antique[e]
[s]Other[e]
[s]Never mind[e]

[msg SYS_002 [ ]]
[s]> You don't have that type of[n]item.[n][w][e]

[msg SYS_003 [ ]]
[s]> Which item will you give?[n][w][e]

[sel SYS_SEL_CATE_01 top]
[s]Rose Bouquet[e]
[s]Red Pine Bonsai[e]
[s]Mini Cactus[e]
[s]Glass Vase[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_02 top]
[s]Perfume[e]
[s]Brand Wallet[e]
[s]Brand Watch[e]
[s]Brand Purse[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_03 top]
[s]Teddy Bear[e]
[s]Japanese Doll[e]
[s]Kaleidoscope[e]
[s]Goggle-eyed Idol[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_04 top]
[s]Jack Frost Doll[e]
[s]Book Cover[e]
[s]Lucky Charm[e]
[s]Ganesha Bank[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_01F top]
[s]Chocolate Truffle[e]
[s]Sweet Fries[e]
[s]Sugar Cookie[e]
[s]Banana Cupcake[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_02F top]
[s]Japanese Strap[e]
[s]Knit Rabbit[e]
[s]Felt Bag[e]
[s]Hand-knitted Scarf[e]
[s]Never mind[e]

[msg MSG_PRE_60 [Yukari]]
[s][bup 2 1 65535 0]...This is for me?[n][w][e]
[s]Um... Thanks...[n][w][e]
[s][f 1 5] [n]> Yukari doesn't seem to like[n]your present very much.[n][w][e]

[msg MSG_PRE_61 [Yukari]]
[s][bup 2 2 65535 0]I can have this!?[n][w][e]
[s]Wow, thanks![n][w][e]
[s]That's really nice of you![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 2]> Yukari seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_62 [Yukari]]
[s][bup 2 1 65535 0]You... took the time to pick this out[n]for me?[n][w][e]
[s]Thanks, I really wanted something like[n]this! That's so nice of you![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 2]> Yukari seems to absolutely love[n]the gift.[n][w][e]

[msg MSG_PRE_63 [Yukari]]
[s][bup 2 1 65535 0]Don't tell me... You made this!?[n][w][e]
[s][bup 2 2 65535 0]Hey, can I try it?[n][w][e]
[s]......[n][w][e]
[s]Yep, this is delicious![n][w][e]
[s]Thank you so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 2]> Yukari seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_64 [Yukari]]
[s][bup 2 1 65535 0]Don't tell me... You made this!?[n][w][e]
[s]Wow, this is amazing...[n][w][e]
[s][bup 2 2 65535 0]Hey, can I try it?[n][w][e]
[s]......[n][w][e]
[s]Yep, this is delicious! Amazing...[n]You're like a professional chef![n][w][e]
[s]Aww, it's already all gone...[n]Can you make me some more?[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 2]> Yukari seems to absolutely love[n]the gift.[n][w][e]

[msg MSG_PRE_65 [Yukari]]
[s][bup 2 1 65535 0]Don't tell me... You made this!?[n][w][e]
[s][bup 2 2 65535 0]Wow, it's so cute. Thank you so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 2]> Yukari seems to absolutely love[n]the gift.[n][w][e]

[msg MSG_PRE_70 [Fuuka]]
[s][bup 6 1 65535 0]Th-Thank you...[n][w][e]
[s]But you really shouldn't have...[n][w][e]
[s][f 1 5] [n]> Fuuka doesn't seem to like[n]your present very much.[n][w][e]

[msg MSG_PRE_71 [Fuuka]]
[s][bup 6 2 65535 0]...This is for me?[n][w][e]
[s]You seem to know my tastes.[n][w][e]
[s]...Thank you very much.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 6]> Fuuka seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_72 [Fuuka]]
[s][bup 6 5 65535 0]Um...[n][w][e]
[s]Um, this is for me?[n]Really...?[n][w][e]
[s]......[n][w][e]
[s]Oh, sorry...[n][w][e]
[s][bup 6 7 65535 0]I'm just surprised. I mean,[n]I've never received something[n]so wonderful before...[n][w][e]
[s]Thank you very much.[n]I'll cherish it forever![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 6]> Fuuka seems to absolutely love[n]your present.[n][w][e]

[msg MSG_PRE_73 [Fuuka]]
[s][bup 6 5 65535 0]Oh, this... Is this what you made in the[n]cooking club? I can have this?[n][w][e]
[s][bup 6 2 65535 0]......[n][w][e]
[s]Mmhm, it's delicious. I hope I can[n]make something this good someday...[n][w][e]
[s]...Thanks. I'll keep trying my best too.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 6]> Fuuka seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_74 [Fuuka]]
[s][bup 6 5 65535 0]Oh, this... Is this what you made in the[n]cooking club? I can have this?[n][w][e]
[s][bup 6 2 65535 0]......[n][w][e]
[s]Mmhm, it's delicious. I hope I can[n]make something this good someday...[n][w][e]
[s]...Thanks. I'll keep trying my best too.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 6]> Fuuka seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_75 [Fuuka]]
[s][bup 6 5 65535 0]Huh? This is hand-made, right?[n]Are you sure I can have this?[n][w][e]
[s][bup 6 2 65535 0]It's so cute...[n][w][e]
[s]I really admire the way you can do all[n]this, [f 4 2]-chan.[n][w][e]
[s]Thank you very much. I'll cherish[n]it forever![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 6]> Fuuka seems to absolutely love[n]your present.[n][w][e]

[msg MSG_PRE_80 [Mitsuru]]
[s][bup 4 1 65535 0]Is this for me?[n][w][e]
[s]...Well, I was taught that it's[n]bad manners not to accept a gift[n]from someone.[n][w][e]
[s]Thanks, I appreciate it.[n][w][e]
[s][f 1 5] [n]> Mitsuru doesn't seem to like[n]your present very much.[n][w][e]

[msg MSG_PRE_81 [Mitsuru]]
[s][bup 4 2 65535 0]Hm? For me?[n][w][e]
[s]Ah... an excellent choice.[n][w][e]
[s]But, more importantly,[n]I appreciate your thoughtfulness.[n]Thank you, [f 4 1].[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 4]> Mitsuru seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_82 [Mitsuru]]
[s][bup 4 1 65535 0]This is for me?[n][w][e]
[s]......[n][w][e]
[s][bup 4 7 65535 0]...I'm impressed with your choice.[n][w][e]
[s]I had no idea you knew me so well.[n][w][e]
[s]Thank you... It's been a long time[n]since I've received a present that[n]has resonated with me like this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 4]> Mitsuru seems to be delighted[n]with the gift.[n][w][e]

[msg MSG_PRE_83 [Mitsuru]]
[s][bup 4 1 65535 0]Did you make this...?[n][w][e]
[s]......[n][w][e]
[s][bup 4 2 65535 0]This is delicious.[n][w][e]
[s]Its flavor is simple, yet warm...[n]Just like its creator.[n][w][e]
[s]Thank you for giving this to me.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 4]> Mitsuru seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_84 [Mitsuru]]
[s][bup 4 1 65535 0]Did you make this...?[n][w][e]
[s]......[n][w][e]
[s][bup 4 2 65535 0]This is delicious.[n][w][e]
[s]Your skills are a match for a patissier[n]at a fine hotel.[n][w][e]
[s]You are indeed skilled... Thank you[n]for giving this to me.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 4]> Mitsuru seems to be delighted[n]with the gift.[n][w][e]

[msg MSG_PRE_85 [Mitsuru]]
[s][bup 4 1 65535 0]This... Did you make it?[n][w][e]
[s][bup 4 2 65535 0]You are strong, but with a feminine[n]side as well... Quite an enigma.[n][w][e]
[s]D-Does... this look good on me?[n][w][e]
[s]...Thank you. I'll treasure this for[n]a long time to come.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 4]> Mitsuru seems to be delighted[n]with the gift.[n][w][e]

[msg MSG_PRE_100 [Yuko]]
[s][bup 31 161 65535 0]Hmmm? What's this?[n][w][e]
[s]...Uhhh.[n][w][e]
[s]Thanks, I guess.[n][w][e]
[s][f 1 5] [n]> It doesn't seem like the right[n]present for Yuko.[n][w][e]

[msg MSG_PRE_101 [Yuko]]
[s][bup 31 162 65535 0]Hm, this is for me?[n][w][e]
[s]Wow, it's so nice! Thanks![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 31]> Yuko seems to like your present.[n][w][e]

[msg MSG_PRE_102 [Yuko]]
[s][bup 31 162 65535 0]Hmmm? What's this?[n][w][e]
[s]...Is this really for me!?[n][w][e]
[s][bup 31 167 65535 0]Are you sure...?[n][w][e]
[s]...Thank you SO much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 31]> Yuko seems delighted with[n]the gift.[n][w][e]

[msg MSG_PRE_110 [Chihiro]]
[s][bup 25 161 65535 0]Um... Th-This is for me...?[n][w][e]
[s]...Oh, um... I... I...[n][w][e]
[s]Um, th-thank you...[n][w][e]
[s]It's the thought that counts.[n][w][e]
[s][f 1 5] [n]> Chihiro doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_111 [Chihiro]]
[s][bup 25 162 65535 0]Huh? For me?[n][w][e]
[s]W-Wow...[n][w][e]
[s]Um... Can I really have this?[n][w][e]
[s]Thank you![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 25]> Chihiro seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_112 [Chihiro]]
[s][bup 25 161 65535 0]Huh? For me?[n][w][e]
[s][bup 25 167 65535 0]W-Wow... Really?[n][w][e]
[s]What a lovely gift...[n][w][e]
[s]Thank you so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 25]> Chihiro seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_120 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s][bup 5 1 65535 0]Uhh... Thanks![n][w][e]
[s][f 1 5] [n]> Junpei doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_121 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Whoa, I can have this!?[n]Awesome, thanks![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 5]> Junpei seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_122 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Wait, WHOA, seriously!?[n]This is really awesome![n][w][e]
[s]Oh man, thanks so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 5]> Junpei seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_123 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Wait, WHOA, seriously!?[n]This is handmade, isn't it!?[n][w][e]
[s]Thanks for the food![n][w][e]
[s]*munch munch*[n][w][e]
[s]Ooh, this is pretty good! Man, nothing[n]is better than a snack a girl made[n]just for me![n][w][e]
[s]Thanks![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 5]> Junpei seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_124 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Wait, WHOA, seriously!?[n]This is handmade, isn't it?[n]It looks so good![n][w][e]
[s]Thanks for the food![n][w][e]
[s]*munch munch*[n][w][e]
[s]Oh man, this is delicious![n]It's like a party for my tongue![n][w][e]
[s]Thanks! I wouldn't mind if you made[n]me something again sometime![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 5]> Junpei seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_125 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Wait, WHOA, seriously!?[n]This is handmade, isn't it?[n]Seriously? I can have it?[n][w][e]
[s]I'm so stoked! Thanks so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 5]> Junpei seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_130 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s]Oh... Um, thanks.[n][w][e]
[s][f 1 5] [n]> Saori doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_131 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow, this is so fantastic...[n]Are you sure I can have this...?[n][w][e]
[s]Thank you so much. I appreciate this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 41]> Saori seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_132 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow...[n][w][e]
[s]Oh, I'm sorry. I was just so surprised[n]that I didn't know what to say.[n][w][e]
[s]Are you sure I can have something[n]so nice...?[n][w][e]
[s]I don't know how to thank you...[n][w][e]
[s]Thank you so much. I'll make sure to[n]cherish this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 41]> Saori seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_133 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow, sweets! It looks so delicious...[n]You made this, right?[n][w][e]
[s]I'll take it home and savor it.[n][w][e]
[s]Haha, I'm looking forward to that[n]later... Thanks.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 41]> Saori seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_134 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow, sweets! It looks so delicious...[n]You made this, right?[n][w][e]
[s]I love sweets like these! I'll take[n]it home and savor it.[n][w][e]
[s]Haha, I'm looking forward to that[n]later... Thanks.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 41]> Saori seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_135 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow... This is fantastic![n]You made this, no?[n][w][e]
[s]It's so cute... I adore this kind[n]of thing.[n][w][e]
[s]Thank you... I'll cherish it forever.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 41]> Saori seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_140 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s]Oh... Well, I accept.[n]Thanks.[n][w][e]
[s][f 1 5] [n]> Rio doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_141 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s][bup 29 162 0 0]Wow, this is nice.[n]Thank you very much![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 29]> Rio seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_142 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s]Let's see here...[n][w][e]
[s][bup 29 162 0 0]Whoa, what is this!? WOW![n][w][e]
[s]It's so cute! I can really have this?[n][w][e]
[s]Thanks! I love it![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 29]> Rio seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_143 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s][bup 29 162 0 0]Wow, this looks delicious![n]Is it handmade? Can I eat it?[n][w][e]
[s]Thanks for the food...[n][w][e]
[s]...Yep, it's tasty! That's really cool[n]that you can make sweets.[n][w][e]
[s]Thanks! I'm looking forward to tasting[n]some more someday.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 29]> Rio seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_144 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s]Let's see...[n][w][e]
[s][bup 29 162 0 0]Wow, what is this!? Is it handmade?[n]It looks so good![n][w][e]
[s]Thanks for the food![n][w][e]
[s]...Yep, it's super delicious![n]You're like a pro![n][w][e]
[s]Thanks! I'm looking forward to tasting[n]some more someday.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 29]> Rio seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_145 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s]Let's see...[n][w][e]
[s][bup 29 162 0 0]Wow, this is so cute! You made this,[n]right? That's amazing![n][w][e]
[s]Are you sure I can have something[n]like this? Isn't it a little too[n]cute for me?[n][w][e]
[s]Thanks! I love it![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 29]> Rio seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_150 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s]......[n][w][e]
[s]Th-Thank you very much.[n][w][e]
[s][f 1 5] [n]> Ken doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_151 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][bup 8 2 65535 0][f 4 2]-san... Are you sure...?[n][w][e]
[s]Thank you very much. I'll definitely[n]treasure this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 8]> Ken seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_152 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][f 4 2]-san... You're treating me[n]like a kid, aren't you?[n][w][e]
[s]......[n][w][e]
[s]Well, I'll still accept it.[n][w][e]
[s]...Thank you very much,[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 8]> Ken seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_153 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][bup 8 2 65535 0][f 4 2]-san... You cooked this,[n]didn't you?[n][w][e]
[s]Wow, thanks... Ooh, this is great![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 8]> Ken seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_154 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][bup 8 2 65535 0][f 4 2]-san... You cooked this,[n]didn't you?[n][w][e]
[s]...Is it okay if I eat this in my room?[n]It's too nice to eat right now...[n][w][e]
[s]I'm happy that you made something so[n]nice for someone like me...[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 8]> Ken seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_155 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][bup 8 2 65535 0][f 4 2]-san... You made this,[n]right?[n][w][e]
[s]It's amazing... Thank you for making[n]something so special for me.[n]It really means a lot.[n][w][e]
[s]I'll cherish it forever...[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 8]> Ken seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_160 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s]Dis... was sold at zhe school.[n]Arigato.[n][w][e]
[s][f 1 5] [n]> Bebe doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_161 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]Wow, dis iz amazing![n]Sugoi, [f 4 2]-sama![n][w][e]
[s]Merci, arigato, thank you![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 34]> Bebe seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_162 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]Hontou!? Wow, dis iz amazing![n][w][e]
[s]Merci, arigato, thank you![n][w][e]
[s]I love Japan![n]I love [f 4 2]-sama too![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 34]> Bebe seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_163 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]Wow, dis iz amazing![n][f 4 2]-sama, you made, no?[n][w][e]
[s]...C'est bon! Oishii![n]Japanese sweets are zhe best![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 34]> Bebe seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_164 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]Wow, dis iz amazing![n][f 4 2]-sama, you made, no?[n][w][e]
[s]...Excellent! Oishii![n]Diz iz my 'omeland's flavor![n][w][e]
[s][f 4 2]-sama's sweets are amazing![n][f 4 2]-sama is amazing too![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 34]> Bebe seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_165 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]You made dis at zhe club![n]You give to Bebe?[n][w][e]
[s][f 4 2]-sama... You are too[n]kind... Arigatou, daisuki![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 34]> Bebe seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_170 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s]......[n][w][e]
[s]This is for me? Well... Thanks.[n][w][e]
[s][f 1 5] [n]> Akihiko doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_171 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s][bup 7 2 65535 0]Whoa, this is different. Thanks.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 7]> Akihiko seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_172 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s][bup 7 2 65535 0]...Are you sure I can have this?[n][w][e]
[s]Thanks... It's really great.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 7]> Akihiko seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_173 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s]......[n][w][e]
[s]It looks sweet...[n][w][e]
[s][bup 7 2 65535 0]Hey, I'll eat it. I mean, you made[n]it for me, right?[n][w][e]
[s]...Mmhm, that's good. Thanks for[n]taking the time to make this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 7]> Akihiko seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_174 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s][bup 7 2 65535 0]...How'd you know I liked this?[n][w][e]
[s]Mmhm, delicious. Man, that flavor...[n][w][e]
[s]I used to love these when I was a kid.[n][w][e]
[s]Thanks...[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 7]> Akihiko seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_175 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s][bup 7 2 65535 0]This is... for me? This is a bit...[n]cute for me, don't you think?[n][w][e]
[s]Haha, well, you made it, so I'll[n]take it.[n][w][e]
[s]...There's nothing wrong with a gift[n]like this, after all.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 7]> Akihiko seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_180 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]...What is this?[n][w][e]
[s]Uhh, well... Thanks, I guess.[n][w][e]
[s][f 1 5] [n]> Shinjiro doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_181 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]......[n][w][e]
[s][bup 9 162 0 0]Why'd you give this to me?[n][w][e]
[s]......[n][w][e]
[s]I-I ain't giving it back.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 9]> Shinjiro seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_182 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]......[n][w][e]
[s][bup 9 162 0 0]Why'd you give this to me?[n][w][e]
[s]......[n][w][e]
[s]I-I ain't giving it back.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 9]> Shinjiro seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_183 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]......[n][w][e]
[s][bup 9 162 0 0]Why'd you give this to me?[n][w][e]
[s]......[n][w][e]
[s]I-I ain't giving it back.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 9]> Shinjiro seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_184 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]...You sure?[n]You made this, right?[n][w][e]
[s]......[n][w][e]
[s][bup 9 162 0 0]...It's delicious.[n][w][e]
[s]I can tell you made it just by tasting[n]it. You're pretty good at this...[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 9]> Shinjiro seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_185 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]......[n][w][e]
[s]You sure? You must have put a lot of[n]time into this, right?[n][w][e]
[s]I got no right to accept something[n]like this...[n][w][e]
[s]......[n][w][e]
[s]...Thanks. I mean that.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 9]> Shinjiro seems to really love[n]the present.[n][w][e]

[msg MSG_500F]
[s]> Iwatodai strip mall, in front of the[n]Sweet Shop...[n][w][e]

[msg MSG_501F [Junpei]]
[s][bup 5 1 65535 0]I usually don't eat sweet stuff, but I[n]get a craving for it from time to time.[n][w][e]
[s]The cafe the other day was the same too,[n]but it's too embarrassing to come here[n]with other guys...[n][w][e]
[s][bup 5 2 65535 0][f 6 1 1 0 5 11]Anyways, let's hurry up and go in![n][w][e]

[msg MSG_502F]
[s]> Junpei is happily looking over the[n]store's menu...[n][w][e]

[msg MSG_503F [Junpei]]
[s][bup 5 2 65535 0]Oh, I forgot to tell you. Today's[n]my treat![n][w][e]
[s]Junpei Iori's in a giving mood![n]You lucked out![n][w][e]

[msg MSG_504F [ ]]
[s]> Junpei is acting triumphant for[n]some reason...[n][w][e]

[msg MSG_505F [Junpei]]
[s][bup 5 2 65535 0]Oh, there's no need to be modest,[n]either.[n][w][e]
[s]I had... a little windfall, you might[n]say, so I'm actually rich for once![n][w][e]

[sel SEL_506F top]
[s]"Win big at pachinko?" +2[e]
[s]"Did you win the lottery?" +3[e]
[s]"Did you find a wallet?"[e]

[msg MSG_507F [Junpei]]
[s][bup 5 2 65535 0]Bingo! Man, it was insane! I hit the[n]jackpot...[n][w][e]
[s][bup 5 5 65535 0]...Like that would ever happen![n]Besides, I'm too young to go into[n]a pachinko parlor![n][w][e]
[s][bup 5 2 65535 0]But I wanna give it a try once I'm[n]old enough.[n][w][e]
[s]I get a bad feeling that I'd lose all[n]my money in no time, though... Haha...[n][w][e]

[msg MSG_508F [ ]]
[s][f 5 13 0 15 5]> Junpei is shrugging...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_509F [Junpei]]
[s][bup 5 2 65535 0]Ooh, bingo![n][w][e]
[s]I bought a scratch lotto card, purely[n]on a whim, and I won![n][w][e]
[s]Well, I won 3,000 yen, anyway. Still,[n]isn't that awesome?[n][w][e]
[s]I'm sharing my good luck with ya.[n]See? Wasn't it a good thing that you[n]came along today?[n][w][e]

[msg MSG_510F [ ]]
[s][f 5 13 0 30 0]> Junpei seems really happy...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_511F [Junpei]]
[s][bup 5 5 65535 0]You think that I pocketed it?[n][w][e]
[s]No no, when I find wallets, I always[n]take 'em to the nearest police box![n][w][e]
[s][bup 5 4 65535 0]Wow, seriously? Do I seem like a guy[n]who'd use someone else's money...?[n][w][e]

[msg MSG_512F [ ]]
[s]> You made Junpei very depressed.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_513F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_600F]
[s]> Iwatodai strip mall,[n]Beef Bowl Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Junpei.[n][w][e]

[msg MSG_601F [Junpei]]
[s][bup 5 2 65535 0]Ahh, that was good... Food in my belly[n]and a smile on my face![n][w][e]
[s][f 6 1 1 0 5 11]The best way to eat a beef bowl's gotta[n]be with having it with extra sauce and[n]extra onions![n][w][e]
[s]They work so well with the steaming[n]rice... Man, there's definitely an art[n]to a good beef bowl.[n][w][e]

[msg MSG_602F]
[s]> Junpei is talking passionately about[n]beef bowls...[n][w][e]

[msg MSG_603F [Junpei]]
[s][bup 5 1 65535 0]When I was bummed out or annoyed back[n]in the day, I used to go eat beef bowls[n]by myself a lot.[n][w][e]
[s]On days like that, I'd go all out and[n]add an egg, tons of ginger...[n][w][e]
[s][bup 5 2 65535 0]Oh, I always asked for extra large, too.[n]I'd down all of it at once.[n][w][e]

[msg MSG_604F [ ]]
[s]> Junpei is talking excitedly.[n][w][e]

[msg MSG_605F [Junpei]]
[s][bup 5 5 65535 0]Uhh, that reminds me... Sorry I brought[n]up some weird stuff last time.[n][w][e]
[s][bup 5 8 65535 0]All that stuff about parents and things...[n]I kinda hope you're not worried...[n][w][e]

[sel SEL_606F top]
[s]"Not at all."[e]
[s]"I can't help but be."[e]
[s]"I already forgot it."[e]

[msg MSG_607F [Junpei]]
[s][bup 5 5 65535 0]Oh, seriously? That's good.[n][w][e]
[s]I mean, I felt bad that I might've made[n]you worry.[n][w][e]
[s][bup 5 2 65535 0]...Anyways, we just had some great beef[n]bowls, so let's stop talking about it.[n]Yeah.[n][w][e]

[msg MSG_608F [ ]]
[s][f 5 13 0 15 0]> Junpei is laughing...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_609F [Junpei]]
[s][bup 5 4 65535 0]Uhh... Well, now I feel bad for telling[n]you. Seriously, don't worry about it![n][w][e]
[s]Then again, saying stuff like that'll[n]make you even more anxious...[n][w][e]
[s]Umm...[n][w][e]

[msg MSG_610F [ ]]
[s]> Junpei is scratching his head,[n]apparently troubled...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_611F [Junpei]]
[s][bup 5 5 65535 0]...Huh? Seriously!?[n][w][e]
[s][bup 5 2 65535 0]Ohh, are you like me that way? You can[n]forget all your troubles in a good[n]beef bowl?[n][w][e]
[s]Alright, then from today forward, let's[n]form a "Beef Bowl Alliance"![n][w][e]
[s]The only requirement is that we go eat[n]beef bowls. Simple, huh![n][w][e]

[msg MSG_612F [ ]]
[s][f 5 13 0 30 0]> Junpei is laughing happily...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_613F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_700F]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time hanging[n]out with Junpei.[n][w][e]

[msg MSG_701F [Junpei]]
[s][bup 5 4 65535 0]*sigh*[n][w][e]
[s][f 6 1 1 0 5 9]We came all this way and I couldn't[n]even read one manga that I wanted[n]to read...[n][w][e]
[s]Seriously, who was holding onto all[n]the volumes in that series!?[n][w][e]

[msg MSG_702F]
[s]> Junpei is a little angry...[n][w][e]

[msg MSG_703F [Junpei]]
[s][bup 5 4 65535 0]Since they didn't have that, I forced[n]myself to read through some of that[n]shoujo manga.[n][w][e]
[s]You know the ones that're popular with[n]girls now? I was curious what they'd[n]be like.[n][w][e]
[s]But I gave up in half an hour. Reading[n]those things wore me out...[n][w][e]

[msg MSG_704F [ ]]
[s]> Junpei seems fed up...[n][w][e]

[msg MSG_705F [Junpei]]
[s][bup 5 5 65535 0]All the guys in those manga are either[n]really good-looking, really rich, or[n]really smart.[n][w][e]
[s]I mean, yeah, it's a manga, I know[n]it's gotta be like that.[n][w][e]
[s][bup 5 4 65535 0]But is that really the only kind of guy[n]girls dream about?[n][w][e]

[sel SEL_706F top]
[s]"Manga isn't reality."[e]
[s]"Of course!"[e]
[s]"I've never read those."[e]

[msg MSG_707F [Junpei]]
[s][bup 5 5 65535 0]Oh, really?[n][w][e]
[s][bup 5 1 65535 0]Oh... Okay, I think I get it.[n][w][e]
[s]The girls are all into it because it's[n]something they can't get in real life,[n]right?[n][w][e]
[s]...Then again, we've got Personas, so[n]our lives are kinda like manga, too.[n][w][e]
[s][bup 5 2 65535 0]Whoa, when I think about it that way,[n]it's pretty exciting![n][w][e]

[msg MSG_708F [ ]]
[s][f 5 13 0 30 0]> Junpei is getting excited...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_709F [Junpei]]
[s][bup 5 5 65535 0]Whoa, so it's true!?[n][w][e]
[s]H-Hey, I hate to be the one to tell[n]you this, but there aren't any guys[n]like that in reality.[n][w][e]
[s][bup 5 1 65535 0]Oh, but... I guess Akihiko-senpai kinda[n]fits the bill... He's a little different,[n]though.[n][w][e]
[s][bup 5 2 65535 0]I've said it before, but maybe you really[n]should try going for Akihiko-senpai.[n][w][e]

[msg MSG_710F [ ]]
[s][f 5 13 0 15 0]> Junpei is kidding around...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_711F [Junpei]]
[s][bup 5 5 65535 0]Huh? Seriously? Don't all girls read[n]that stuff, though?[n][w][e]
[s]I guess you're an oddball...[n][w][e]

[msg MSG_712F [ ]]
[s]> Junpei is surprised...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_713F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_800F]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_801F [Junpei]]
[s][bup 5 1 65535 0]I didn't notice that this area gets[n]pretty busy during holidays.[n][w][e]
[s]I never really had much business here[n]besides the restaurants and manga cafe.[n][w][e]

[msg MSG_802F]
[s]> Junpei is looking around, seemingly[n]intrigued...[n][w][e]

[msg MSG_803F [Junpei]]
[s][bup 5 1 65535 0]Development seems to be moving forward[n]around here too these days.[n][w][e]
[s]Doesn't it surprise you to see new[n]buildings pop up suddenly?[n][w][e]
[s]This area's probably gonna go on[n]changing, too...[n][w][e]

[msg MSG_804F [ ]]
[s]> Junpei seems a little sad...[n][w][e]

[msg MSG_805F [Junpei]]
[s][bup 5 2 65535 0]But you know, our memories of having[n]fun here with our friends will last[n]forever.[n][w][e]
[s]I don't know how to put it, but...[n]I think it's really important to have[n]memories of your friends.[n][w][e]
[s]It's something I've been thinking[n]about more lately.[n][w][e]
[s]...Aw man, am I sounding like something[n]out of a shonen manga?[n][w][e]

[sel SEL_806F top]
[s]"Yep." +2[e]
[s]"I think it's wonderful." +3[e]
[s]"I didn't hear a thing."[e]

[msg MSG_807F [Junpei]]
[s][bup 5 5 65535 0]Yikes, an absolute "yes"!? Man, you[n]really go for the throat.[n][w][e]
[s]But... maybe me embarrassing myself[n]with stuff like that will be one of[n]our good memories...?[n][w][e]
[s]Uhh, dammit... Now I'm really starting[n]to get embarrassed.[n][w][e]

[msg MSG_808F [ ]]
[s][f 5 13 0 15 0]> Junpei is scratching his head.[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_809F [Junpei]]
[s][bup 5 5 65535 0]Ooh, so you actually like sappy stuff[n]like that?[n][w][e]
[s][bup 5 2 65535 0]...Then I'm gonna keep going.[n][w][e]
[s]The reason I can say stuff like this out[n]loud is because I realized how important[n]friends are.[n][w][e]
[s]That's why I gotta make as many memories[n]I can with you![n][w][e]
[s]Alright, let's start by eating some[n]hot takoyaki![n][w][e]

[msg MSG_810F [ ]]
[s][f 5 13 0 30 0]> Junpei is laughing in embarrassment...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_811F [Junpei]]
[s][bup 5 5 65535 0]C'mon, listen! Listen to me! I said[n]something pretty cool![n][w][e]
[s]Well, that's fine too. It's better if[n]I just put on a defiant act anyways![n][w][e]

[msg MSG_812F [ ]]
[s]> Junpei is embarrased and angry at the[n]same time.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_813F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_900F]
[s]> Iwatodai Strip Mall, Hagakure Ramen...[n][w][e]

[msg MSG_901F [Rio]]
[s][bup 29 161 0 0]I saw ramen on TV and got this sudden[n]urge to have some.[n][w][e]

[msg MSG_902F]
[s]> Rio is shrugging...[n][w][e]

[msg MSG_903F [Rio]]
[s][bup 29 161 0 0]I've never come here alone before, so I[n]was a little hesitant.[n][w][e]
[s]I come here sometimes with a guy[n]friend... Friend? Anyway, there's always[n]someone else.[n][w][e]

[msg MSG_904F [ ]]
[s]> Rio seems somewhat apologetic...[n][w][e]

[msg MSG_905F [Rio]]
[s][bup 29 161 0 0]I couldn't get a hold of him today...[n]Sorry to call you up on your day off[n]like this.[n][w][e]

[sel SEL_906F top]
[s]"Don't worry about it."[e]
[s]"Fine, but... ramen?"[e]
[s]"I'm glad you asked me."[e]

[msg MSG_907F [Rio]]
[s][bup 29 162 0 0]Really? Cool.[n][w][e]
[s]Then, you wanna come again after club[n]lets out? It's got so many calories[n]that it's perfect for after practice.[n][w][e]

[msg MSG_908F [ ]]
[s][f 5 13 0 15 0]> Rio is laughing happily...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_909F [Rio]]
[s][bup 29 161 0 0]Oh... You're right. Calling you out[n]for ramen on your day off wasn't such[n]a bright idea, huh?[n][w][e]
[s]...I'm sorry.[n][w][e]

[msg MSG_910F [ ]]
[s]> Rio looks downhearted...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_911F [Rio]]
[s][bup 29 162 0 0]Do you have a thing for ramen, too?[n][w][e]
[s]It's no fun eating here alone, so thanks[n]for coming with me.[n][w][e]

[msg MSG_912F [ ]]
[s][f 5 13 0 30 22]> Rio seems really happy.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_913F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1000F]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_1001F [Rio]]
[s][bup 29 162 0 0][f 6 1 1 0 29 11]I'm glad I was able to buy some nice[n]T-shirts.[n][w][e]
[s]We sweat a lot during practice, so I[n]never have enough.[n][w][e]

[msg MSG_1002F]
[s]> Rio seems satisfied...[n][w][e]

[msg MSG_1003F [Rio]]
[s][bup 29 161 0 0]...By the way, are short skirts popular[n]right now?[n][w][e]
[s]Everyone's wearing frilly ones for[n]some reason.[n][w][e]

[msg MSG_1004F [ ]]
[s]> Rio seems curious...[n][w][e]

[msg MSG_1005F [Rio]]
[s][bup 29 161 0 0]You look good in skirts too,[n][f 4 2].[n][w][e]
[s]But when you run around in them, don't[n]you get nervous that someone might see[n]your underwear?[n][w][e]

[sel SEL_1006F top]
[s]"Yeah, sometimes."[e]
[s]"I never thought about it."[e]
[s]"I don't really care."[e]

[msg MSG_1007F [Rio]]
[s][bup 29 162 0 0]Oh, so you worry about that too.[n][w][e]
[s]I even get worried with our uniforms.[n]Some people make it really short, too.[n][w][e]

[msg MSG_1008F [ ]]
[s][f 5 13 0 15 0]> Rio is nodding...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_1009F [Rio]]
[s][bup 29 161 0 0]Huh? Really?[n][w][e]
[s]I wonder if I'm the only one who gets[n]worried about girls that wear short[n]skirts...[n][w][e]
[s]I keep thinking, stop showing off stuff[n]I don't want to see! Oh, but... I don't[n]mean you, of course![n][w][e]

[msg MSG_1010F [ ]]
[s]> Rio is flustered...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_1011F [Rio]]
[s][bup 29 161 0 0]Huh? Really?[n][w][e]
[s]Wow... You're pretty amazing...[n]I'm a little impressed.[n][w][e]

[msg MSG_1012F [ ]]
[s][f 5 13 0 30 0]> Rio is nodding vigorously...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1013F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1100F]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_1101F [Rio]]
[s][bup 29 161 0 0]H-Hey, [f 4 2]...[n][w][e]
[s]There's something I want to ask you...[n][w][e]

[msg MSG_1102F]
[s]> Rio seems nervous...[n][w][e]

[msg MSG_1103F [Rio]]
[s][bup 29 161 0 0]Um... Don't laugh, okay?[n][w][e]
[s]How... do you act more like a girl?[n][w][e]

[msg MSG_1104F [ ]]
[s]> Rio is blushing a little...[n][w][e]

[msg MSG_1105F [Rio]]
[s][bup 29 161 0 0]Well... Um...[n][w][e]
[s][f 6 1 1 0 29 17]I-I guess something like Ms. Kanou...[n]Trying to be more like a girl's, um...[n][w][e]
[s]I don't know how to go about it...[n][w][e]

[sel SEL_1106F top]
[s]"Start with your clothes."[e]
[s]"Body language is key."[e]
[s]"Adults rely on scents."[e]

[msg MSG_1107F [Rio]]
[s][bup 29 162 0 0]I-I see. You mean... frilly clothes?[n]Will those look good on me...?[n][w][e]
[s]What should I do? That's so not my[n]thing...[n][w][e]
[s]...Can you choose some for me?[n][w][e]

[msg MSG_1108F [ ]]
[s][f 5 13 0 30 0]> You sense Rio's determination...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1109F [Rio]]
[s][bup 29 161 0 0]Huh...? I can't do that...[n][w][e]
[s]I really hate girls that try and act[n]all cutesy around guys...[n][w][e]
[s]Is that the only way to be more like[n]a girl...?[n][w][e]
[s]I gotta respect those girls, then...[n][w][e]

[msg MSG_1110F [ ]]
[s][f 5 13 0 15 0]> Rio is at a loss...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_1111F [Rio]]
[s][bup 29 161 0 0]I-Is that so? I think I can do that.[n][w][e]
[s]They sell perfumes at the pharmacy[n]and I can try changing my shampoo...[n][w][e]
[s]Oh, but I sweat so much at practice![n]Do I smell then? How am I supposed[n]to rely on scents that way...!?[n][w][e]

[msg MSG_1112F [ ]]
[s][f 5 13 0 15 0]> Rio is flustered...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_1113F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1200F]
[s]> Iwatodai Strip Mall, Hagakure Ramen...[n][w][e]

[msg MSG_1201F [Rio]]
[s][bup 29 162 0 0]Ahh...[n][w][e]
[s][f 6 1 1 0 29 6]The special at Hagakure tastes great[n]whenever you have it![n][w][e]

[msg MSG_1202F]
[s]> Rio is eating the ramen contentedly...[n][w][e]

[msg MSG_1203F [Rio]]
[s][bup 29 162 0 0]Kenji's a big fan of Hagakure too, so[n]every now and then he takes me along[n]with him.[n][w][e]
[s]That guy's a total ramen geek.[n]He goes on and on about ramen![n][w][e]

[msg MSG_1204F [ ]]
[s]> Rio is laughing...[n][w][e]

[msg MSG_1205F [Rio]]
[s][bup 29 161 0 0]To tell the truth... I haven't really[n]spoken to Kenji since then.[n][w][e]
[s]Kenji's pretty dumb, so he doesn't[n]notice at all, but I feel so awkward[n]around him...[n][w][e]
[s]...Do you think I'll eventually be[n]able to talk to him like before?[n][w][e]

[sel SEL_1206F top]
[s]"Definitely."[e]
[s]"It depends on you."[e]
[s]"That might be hard."[e]

[msg MSG_1207F [Rio]]
[s][bup 29 162 0 0]...Yeah, you're right.[n][w][e]
[s]It's odd, but hearing you say that[n]is a relief.[n][w][e]

[msg MSG_1208F [ ]]
[s][f 5 13 0 15 0]> You sense gratitude from Rio...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_1209F [Rio]]
[s][bup 29 162 0 0]I see... Yeah, you're right.[n][w][e]
[s]Nothing will change unless I'm willing[n]to change.[n][w][e]
[s]I'll try my best to talk to Kenji the[n]next time I see him around.[n][w][e]

[msg MSG_1210F [ ]]
[s][f 5 13 0 30 0]> Rio seems to be motivated...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1211F [Rio]]
[s][bup 29 161 0 0]...I see.[n][w][e]
[s]......[n][w][e]

[msg MSG_1212F [ ]]
[s]> Rio looks sad...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_1213F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1300F]
[s]> Iwatodai Strip Mall,[n]"Wild-duck Burger"...[n][w][e]

[msg MSG_1301F [Rio]]
[s][bup 29 161 0 0]I come here a lot after practice, but[n]it feels different coming here on a day[n]when there's no school.[n][w][e]

[msg MSG_1302F]
[s]> Rio seems to be having fun...[n][w][e]

[msg MSG_1303F [Rio]]
[s][bup 29 161 0 0]That reminds me, everyone's been asking[n]me lately if I wanted to take part in[n]a group date...[n][w][e]
[s]I've never gone on a group date before,[n]so I don't know what to do.[n][w][e]

[msg MSG_1304F [ ]]
[s]> Rio seems somewhat troubled...[n][w][e]

[msg MSG_1305F [Rio]]
[s][bup 29 161 0 0]What kind of things do people do on[n]a group date?[n][w][e]

[sel SEL_1306F top]
[s]"King's game!"[e]
[s]"You just chat."[e]
[s]"I've never gone myself."[e]

[msg MSG_1307F [Rio]]
[s][bup 29 161 0 0]King's...?[n][w][e]
[s]You get to become a king? Wow,[n]that's amazing.[n][w][e]

[msg MSG_1308F [ ]]
[s][f 5 13 0 15 0]> Rio has an astonished look on[n]her face...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_1309F [Rio]]
[s][bup 29 161 0 0]Oh... Really? If that's the case, then[n]I might not mind going...[n][w][e]
[s]Talking with people's actually gotten[n]more fun for me lately.[n][w][e]
[s]After I spilled my guts to the rest of[n]the club, I understand them better[n]now too.[n][w][e]

[msg MSG_1310F [ ]]
[s][f 5 13 0 30 0]> Rio is nodding deeply...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1311F [Rio]]
[s][bup 29 162 0 0]Oh, is that so?[n][w][e]
[s]Well, if I have to go sometime, then[n]I'm dragging you with me![n][w][e]
[s]I'm too scared to go by myself![n][w][e]

[msg MSG_1312F [ ]]
[s][f 5 13 0 15 22]> Rio is laughing...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_1313F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1400F]
[s]> Iwatodai Strip Mall,[n]"Wild-duck Burger"...[n][w][e]

[msg MSG_1401F [Saori]]
[s][bup 41 161 0 0]I'm sorry to ask you out so sudden.[n]I really wanted to try coming here.[n][w][e]
[s][f 6 1 1 0 41 11]I snuck out. *chuckle* It was rather[n]exciting.[n][w][e]

[msg MSG_1402F]
[s]> Saori is smiling...[n][w][e]

[msg MSG_1403F [Saori]]
[s][bup 41 161 0 0]I came to places like these fairly[n]often until about middle school.[n][w][e]
[s]I'd study with my friends there[n]before exams.[n][w][e]

[msg MSG_1404F [ ]]
[s]> Saori seems to be reminiscing...[n][w][e]

[msg MSG_1405F [Saori]]
[s][bup 41 162 0 0]Oh... Sorry. I didn't inconvenience[n]you today, I hope?[n][w][e]

[sel SEL_1406F top]
[s]"Why?"[e]
[s]"Nope, not at all."[e]
[s]"I was bored anyways!"[e]

[msg MSG_1407F [Saori]]
[s][bup 41 162 0 0]I mean, I think I'm boring to be[n]around...[n][w][e]
[s]If only I could come up with something[n]interesting to talk about.[n][w][e]

[msg MSG_1408F [ ]]
[s]> Saori's smile is somewhat troubled...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_1409F [Saori]]
[s][bup 41 162 0 0]...Really?[n][w][e]
[s]*chuckle* Thanks. You're always so[n]nice, [f 4 2]-chan.[n][w][e]
[s]I'm glad we could talk like this...[n][w][e]

[msg MSG_1410F [ ]]
[s][f 5 13 0 30 0]> Saori seems to be having fun.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1411F [Saori]]
[s][bup 41 162 0 0]Is that so? Then I must've been lucky.[n][w][e]
[s]I should wish for you to have more days[n]when you're bored.[n][w][e]

[msg MSG_1412F [ ]]
[s][f 5 13 0 15 0]> Saori is smiling...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_1413F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1600F]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_1601F [Saori]]
[s][bup 41 162 65535 0]Your clothes are so cute,[n][f 4 2]-chan.[n][w][e]
[s]They're... very feminine? You look[n]wonderful in them.[n][w][e]

[msg MSG_1602F]
[s]> Saori is smiling...[n][w][e]

[msg MSG_1603F [Saori]]
[s][bup 41 162 65535 0]I think you'd look good even in the kind[n]of elegant dress that princesses wear.[n][w][e]
[s]I really adore things like that.[n][w][e]
[s]It sounds childish, but dreaming about[n]a handsome prince rescuing you...[n][w][e]
[s]Isn't that something all girls do?[n][w][e]

[msg MSG_1604F [ ]]
[s]> Saori is laughing somewhat sadly...[n][w][e]

[msg MSG_1605F [Saori]]
[s][bup 41 162 65535 0]...Have you already found your prince,[n][f 4 2]-chan?[n][w][e]

[sel SEL_1606F top]
[s]"Yep."[e]
[s]"Nope."[e]
[s]"Well..."[e]

[msg MSG_1607F [Saori]]
[s][bup 41 162 65535 0]My! Really? He must be one fantastic[n]prince.[n][w][e]
[s][bup 41 161 65535 0]......[n][w][e]
[s]...[f 4 2]-chan, um...[n][w][e]
[s]......[n][w][e]
[s]It might be better if you don't tell[n]anyone about the prince you've fallen[n]in love with.[n][w][e]
[s]You never know who'll try and break up[n]your relationship.[n][w][e]

[msg MSG_1608F [ ]]
[s][f 5 13 0 30 0]> Saori opened up to you soberly...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1609F [Saori]]
[s][bup 41 162 65535 0]Then I'm sure you'll meet one soon.[n]I bet that he'll be a fine prince.[n][w][e]

[msg MSG_1610F [ ]]
[s][f 5 13 0 15 0]> Saori is smiling...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_1611F [Saori]]
[s][bup 41 162 65535 0]Oh, I'm sorry. I shouldn't be poking my[n]nose around.[n][w][e]

[msg MSG_1612F [ ]]
[s]> Saori is smiling hesitantly...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_1613F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1700F]
[s]> Iwatodai Station...[n][w][e]
[s]> You went out to buy groceries[n]with Ken...[n][w][e]
[s]> Your arms are full with the bags.[n][w][e]

[msg MSG_1701F [Ken]]
[s][bup 8 2 65535 0]I'm surprised you can find the same[n]thing for cheaper just by going down[n]a different road.[n][w][e]

[msg MSG_1702F]
[s]> Ken seems to be having fun...[n][w][e]

[msg MSG_1703F [Ken]]
[s][bup 8 2 65535 0]I've seen on TV how housewives ride their[n]bikes as far as neighboring cities just[n]to save one yen...[n][w][e]
[s]But I think I kind of understand that[n]now. I was excited when I found a cheaper[n]store, too.[n][w][e]

[msg MSG_1704F [ ]]
[s]> Ken is laughing a little...[n][w][e]

[msg MSG_1705F [Ken]]
[s][bup 8 2 65535 0]Oh, [f 4 2]-san. I'll take the bags[n]in your right hand.[n][w][e]

[sel SEL_1706F top]
[s]"You don't have to."[e]
[s]"I can hold it myself."[e]
[s]"Thanks, please do."[e]

[msg MSG_1707F [Ken]]
[s][bup 8 1 65535 0]I'm not straining myself...[n][w][e]
[s]I mean, I'm not that big yet, but I[n]can at least hold the ones you're[n]carrying![n][w][e]

[msg MSG_1708F [ ]]
[s][f 5 13 0 15 0]> Ken is a little angry...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_1709F [Ken]]
[s][bup 8 1 65535 0]Oh, I'm sorry... It's none of my[n]business, huh...?[n][w][e]

[msg MSG_1710F [ ]]
[s]> Ken fell silent...[n][w][e]
[s]> Your relationdship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_1711F [Ken]]
[s][bup 8 2 65535 0]Yes, please leave it to me![n][w][e]
[s]When I was measured the other day at[n]school, I was a little taller![n][w][e]
[s]It might be because I've been eating[n]my meals regularly with you.[n][w][e]

[msg MSG_1712F [ ]]
[s][f 5 13 0 30 0]> Ken seems happy...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1713F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1800F]
[s]> Iwatodai Strip Mall,[n]Wild-duck Burger...[n][w][e]

[msg MSG_1801F [Ken]]
[s][bup 8 1 65535 0]I used to eat things like these all[n]the time.[n][w][e]
[s]I still eat it once in a while, but it[n]tastes kinda dull...[n][w][e]

[msg MSG_1802F]
[s]> Ken is munching on fries...[n][w][e]

[msg MSG_1803F [Ken]]
[s][bup 8 1 65535 0]There's so many high school students[n]around. This place seems full after[n]school, too.[n][w][e]
[s]I even see them at karaoke and CD shops.[n][w][e]

[msg MSG_1804F [ ]]
[s]> Ken is looking around...[n][w][e]

[msg MSG_1805F [Ken]]
[s][bup 8 1 65535 0]I wonder what my life will be like[n]when I'm in high school...[n][w][e]
[s]So much is going on already that[n]I can't even imagine what a high[n]school me would be like...[n][w][e]

[sel SEL_1806F top]
[s]"It'll come quickly."[e]
[s]"You'll be handsome."[e]
[s]"An ordinary high schooler."[e]

[msg MSG_1807F [Ken]]
[s][bup 8 4 65535 0]You think so...?[n][w][e]
[s]I mean, I feel like there's a huge gap[n]between you and me.[n][w][e]
[s]I hope I can catch up with you quick...[n][w][e]

[msg MSG_1808F [ ]]
[s]> Ken seems somewhat sad...[n][w][e]
[s]> Your relationship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_1809F [Ken]]
[s][bup 8 5 65535 0]C-C'mon, don't tease me like that![n][w][e]
[s]...It would be nice if that were[n]true, though.[n][w][e]

[msg MSG_1810F [ ]]
[s][f 5 13 0 30 0]> Ken doesn't seem to be wholly adverse[n]to the idea...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_1811F [Ken]]
[s][bup 8 1 65535 0]An ordinary high schooler...[n][w][e]
[s]I wonder what an ordinary student is[n]like. Does that mean it's not good[n]or bad?[n][w][e]
[s]But I usually hear that being ordinary[n]is the best... Hmm...[n][w][e]

[msg MSG_1812F [ ]]
[s][f 5 13 0 15 0]> Ken is lost in thought...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_1813F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_1900F [ ]]
[s]> Iwatodai Strip Mall, Hagakure Ramen...[n][w][e]

[msg MSG_1901F [Akihiko]]
[s][bup 7 4 65535 0]*sigh* What am I supposed to do...?[n][w][e]

[msg MSG_1902F]
[s]> Akihiko is sighing with a tired look[n]on his face...[n][w][e]
[s]> Could something have happened...?[n][w][e]

[msg MSG_1903F [Akihiko]]
[s][bup 7 1 65535 0]Oh... Sorry. I shouldn't be like this[n]after I called you out here.[n][w][e]
[s]There's just something bothering me[n]right now...[n][w][e]

[msg MSG_1904F [ ]]
[s]> You asked what was bothering him...[n][w][e]

[msg MSG_1905F [Akihiko]]
[s][bup 7 1 65535 0]The other day, a junior girl called me[n]up and asked if I'd date her.[n][w][e]
[s]I turned her down... but ever since[n]then, she keeps bringing me letters[n]and gifts...[n][w][e]
[s][bup 7 4 65535 0][f 6 1 1 0 7 9]*sigh* I could just ignore her, but[n]I'd feel terrible.[n][w][e]
[s]What in the world do I have to say to[n]get her to stop...?[n][w][e]

[sel SEL_1906F top]
[s]"I'm not interested in you."[e]
[s]"I have a girlfriend."[e]
[s]"Beat me, and I'll date you."[e]

[msg MSG_1907F [Akihiko]]
[s][bup 7 1 65535 0]I've tried telling her that already.[n]But she doesn't understand at all...[n][w][e]
[s]If she says she still has a right to[n]give me gifts, I can't force them back[n]at her...[n][w][e]
[s]It seems like she's going to try and[n]wait it out... but honestly, it's such[n]a pain...[n][w][e]
[s][bup 7 4 65535 0]And why am I telling you this...?[n][w][e]

[msg MSG_1908F [ ]]
[s]> Akihiko seems to be troubled...[n][w][e]
[s]> Your relationship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_1909F [Akihiko]]
[s][bup 7 1 65535 0]...Well, that would be the easiest way,[n]but I don't feel comfortable lying[n]like that...[n][w][e]
[s][bup 7 2 65535 0]If she presses me to prove it, maybe[n]I'll have you play that part for me,[n]haha...[n][w][e]

[msg MSG_1910F [ ]]
[s][f 5 13 0 15 0]> Akihiko is shrugging...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_1911F [Akihiko]]
[s][bup 7 1 65535 0]I see... So I should challenge her[n]instead. There's no way she'd actually[n]agree to a fight.[n][w][e]
[s][bup 7 2 65535 0]That's a good idea. I'll remember that[n]for next time.[n][w][e]
[s][bup 7 1 65535 0]...Wait, but what if she doesn't play[n]fair? Like, what if she poisons my[n]lunch...?[n][w][e]

[msg MSG_1912F [ ]]
[s][f 5 13 0 15 0]> Akihiko is lost in thought...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_1913F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_2000F]
[s]> Iwatodai Strip Mall,[n]Wild-duck Burger...[n][w][e]

[msg MSG_2001F [Akihiko]]
[s][bup 7 2 65535 0]By the way...[n][w][e]
[s]Did you know there's a plan to build[n]a big pool around here?[n][w][e]

[msg MSG_2002F]
[s]> Akihiko seems happy...[n][w][e]

[msg MSG_2003F [Akihiko]]
[s][bup 7 1 65535 0]Swimming is highly effective aerobic[n]exercise. It's good for your health, too.[n][w][e]
[s]Stuff like jogging and cycling are[n]good aerobic exercises too, but...[n][w][e]

[msg MSG_2004F [ ]]
[s]> Akihiko is talking passionately about[n]exercising...[n][w][e]

[msg MSG_2005F [Akihiko]]
[s][bup 7 2 65535 0]Hey, do you want to go swimming with[n]me when the pool opens?[n][w][e]

[sel SEL_2006F top]
[s]"No thanks."[e]
[s]"I look forward to it."[e]
[s]"I'll wear a cute swimsuit."[e]

[msg MSG_2007F [Akihiko]]
[s][bup 7 2 65535 0]What? Don't tell me you can't swim...[n][w][e]
[s]If you're not good at swimming, I'd be[n]glad to teach you.[n][w][e]
[s]You won't get better without a lot[n]of practice.[n][w][e]
[s]Don't worry, I'll make sure to hammer[n]the basics into you.[n][w][e]

[msg MSG_2008F [ ]]
[s]> Akihiko's gone into Spartan mode...[n][w][e]
[s]> Your relationship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_2009F [Akihiko]]
[s][bup 7 2 65535 0]Well, there's no knowing if the plan's[n]for real or not yet.[n][w][e]
[s]Still, I look forward to going with you.[n][w][e]

[msg MSG_2010F [ ]]
[s][f 5 13 0 15 0]> Akihiko is laughing...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_2011F [Akihiko]]
[s][bup 7 1 65535 0]...Huh?[n][w][e]
[s]...I-It's okay, normal's fine. Your[n]swimsuit can be normal.[n][w][e]
[s]Um... Not that I don't want to see you[n]in something like that! On the contrary,[n]I'd be happy--[n][w][e]
[s][bup 7 3 65535 0]...No, what am I saying!?[n][w][e]
[s]Uh... How should I say this... I feel[n]like I wouldn't know where to look...[n][w][e]
[s]...H-Hey, don't laugh![n][w][e]

[msg MSG_2012F [ ]]
[s][f 5 13 0 30 0]> Akihiko is in a tizzy...[n][w][e]
[s]> Today, your relationship has grown[n]stronger...[n][w][e]

[msg MSG_2013F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_2100F]
[s]> Iwatodai strip mall,[n]Beef Bowl Shop...[n][w][e]

[msg MSG_2101F [Akihiko]]
[s][bup 7 2 65535 0]Isn't getting beef bowls on your days[n]off great?[n][w][e]
[s]I prefer this to going to a cafe.[n][w][e]

[msg MSG_2102F]
[s]> Akihiko is laughing...[n][w][e]

[msg MSG_2103F [Akihiko]]
[s][bup 7 2 65535 0]The only other restaurants I know of[n]are fast food places and ramen...[n][w][e]
[s]...Though that's nothing to brag about[n]when I keep telling people how important[n]their health is.[n][w][e]

[msg MSG_2104F [ ]]
[s]> Akihiko is shrugging...[n][w][e]

[msg MSG_2105F [Akihiko]]
[s][bup 7 1 65535 0]Maybe I'd be different if I could cook[n]like Shinji...[n][w][e]
[s]Seriously, I wish he had taught me a[n]few recipes.[n][w][e]
[s]......[n][w][e]
[s][bup 7 2 65535 0]...Oh, but come to think of it, he did[n]teach me one.[n][w][e]
[s]"A delicious way of eating cup ramen"...[n]Do you know what you're supposed to do?[n][w][e]

[sel SEL_2106F top]
[s]"Put an egg in."[e]
[s]"Put milk in."[e]
[s]"I don't want to know."[e]

[msg MSG_2107F [Akihiko]]
[s][bup 7 2 65535 0]Haha, that's definitely one way.[n][w][e]
[s]But there's a way to make it taste[n]even better. Listen to this...[n][w][e]
[s][bup 7 1 65535 0]You heat up sesame oil and put it in.[n][w][e]
[s][bup 7 2 65535 0]...What's with that look? That's all[n]there is to it.[n][w][e]
[s]You can't put the oil in while it's[n]still cold. Shinji'd get angry if you[n]did that.[n][w][e]
[s]Though I really don't think it makes[n]that much of a difference...[n][w][e]

[msg MSG_2108F [ ]]
[s][f 5 13 0 30 0]> Akihiko is laughing and having fun...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_2109F [Akihiko]]
[s][bup 7 2 65535 0]Milk!? I've never heard of that trick...[n][w][e]
[s]Wouldn't the noodles stay hard even[n]after three minutes if you use milk?[n][w][e]
[s]...But would that make it taste good[n]too? I definitely need to try that...[n][w][e]

[msg MSG_2110F [ ]]
[s][f 5 13 0 15 0]> Akihiko is thinking seriously...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_2111F [Akihiko]]
[s][bup 7 1 65535 0]I see... Well, I guess you wouldn't[n]eat stuff like cup ramen.[n][w][e]
[s]Junpei's always eating it, so I kind of[n]assumed you might like it too...[n][w][e]

[msg MSG_2112F [ ]]
[s]> Akihiko is giving a forced laugh...[n][w][e]
[s]> Your relationship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_2113F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_2200F [ ]]
[s]> Naganaki Shrine...[n][w][e]

[msg MSG_2201F [Akihiko]]
[s][bup 7 2 65535 0]It's a nice day out.[n][w][e]
[s]This place is quiet even on holidays,[n]so it's soothing...[n][w][e]

[msg MSG_2202F]
[s]> Akihiko seems to be very relaxed...[n][w][e]

[msg MSG_2203F [Akihiko]]
[s][bup 7 2 65535 0]That reminds me, when I was a kid,[n]I used to go to a shrine pretty often...[n][w][e]
[s]Shinji found a kitten at the shrine[n]that had been left in a box.[n][w][e]
[s]It was really weak, but we brought it[n]food every day.[n][w][e]
[s]Eventually, the kitten got better and[n]became rather attached to us...[n][w][e]

[msg MSG_2204F [ ]]
[s]> Akihiko is looking off into the[n]distance while speaking...[n][w][e]

[msg MSG_2205F [Akihiko]]
[s][bup 7 1 65535 0]But one day, that kitten suddenly[n]disappeared.[n][w][e]
[s]We kept imagining the worst, like maybe[n]it had been attacked by crows...[n][w][e]
[s]Eventually, we found that cat with an[n]old woman who had been taking care of it.[n][w][e]
[s]It looked so peaceful that even we[n]weren't sure for a moment if it really[n]was the same cat...[n][w][e]
[s]When I saw its face... I don't know how[n]to describe how I felt then.[n][w][e]

[sel SEL_2206F top]
[s]"Were you happy?"[e]
[s]"Were you sad?"[e]
[s]"Were you proud?"[e]

[msg MSG_2207F [Akihiko]]
[s][bup 7 2 65535 0]Yeah, of course I was happy.[n][w][e]
[s]I looked for it every day, thinking it[n]might be dead somewhere...[n][w][e]
[s][bup 7 1 65535 0]But, I don't know how to put it...[n]I didn't only feel happy.[n][w][e]
[s]I also felt sad that we weren't able to[n]take care of it, and annoyed that a[n]stranger took it from us...[n][w][e]
[s][bup 7 2 65535 0]But most of all, I felt a little bit[n]accomplished that I was able to protect[n]a life...[n][w][e]
[s]I think back to what I felt that day[n]from time to time, to tell myself there[n]are still things that even I can do...[n][w][e]

[msg MSG_2208F [ ]]
[s][f 5 13 0 15 0]> Akihiko is wearing a smile...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_2209F [Akihiko]]
[s][bup 7 2 65535 0]True, I did feel a little sad...[n][w][e]
[s]I felt sad that we weren't able to[n]take care of it, and annoyed that a[n]stranger took it from us...[n][w][e]
[s]But most of all, I felt a little bit[n]accomplished that I was able to protect[n]a life...[n][w][e]
[s]I think back to what I felt that day[n]from time to time, to tell myself there[n]are still things that even I can do...[n][w][e]

[msg MSG_2210F [ ]]
[s][f 5 13 0 15 0]> Akihiko is wearing a smile...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_2211F [Akihiko]]
[s][bup 7 2 65535 0]...Yeah, I think I was proud even more[n]than I was happy.[n][w][e]
[s]It was a feeling of accomplishment,[n]that even though I was just a kid,[n]I had saved a life.[n][w][e]
[s]......[n][w][e]
[s]...Which reminds me, I think of that[n]kitten from back then when I look at[n]you sometimes.[n][w][e]
[s]You eat a lot and you seem so happy[n]all the time.[n][w][e]
[s]And... just like that kitten, I always[n]have to keep an eye on you.[n][w][e]

[msg MSG_2212F [ ]]
[s][f 5 13 0 30 0]> Akihiko is smililng gently...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_2213F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_2300F [ ]]
[s]> Naganaki Shrine...[n][w][e]

[msg MSG_2301F [Akihiko]]
[s][bup 7 2 65535 0]It's a nice day out.[n][w][e]
[s]This place is quiet even on holidays,[n]so it's soothing...[n][w][e]

[msg MSG_2302F]
[s]> Akihiko seems to be very relaxed...[n][w][e]

[msg MSG_2303F [Akihiko]]
[s][bup 7 2 65535 0]Well, we came all this way, why don't[n]we pay a visit to the shrine while[n]we're here?[n][w][e]
[s]...C'mon, it's this way.[n][w][e]

[msg MSG_2304F [ ]]
[s]> Akihiko took your hand and led you[n]to the offertory box...[n][w][e]
[s]> ......[n][w][e]
[s]> You paid a visit to the shrine with[n]Akihiko...[n][w][e]

[msg MSG_2305F [Akihiko]]
[s][bup 7 2 65535 0]I wonder how many times I've made wishes[n]like this here...[n][w][e]
[s]To tell the truth, I don't really like[n]praying for things to come true.[n][w][e]
[s]I've always thought that if you want[n]something done, it's better to do it[n]yourself.[n][w][e]
[s]But... there are times when even I[n]rely on a god to help me out.[n][w][e]
[s]...By the way, what did you wish for?[n][w][e]

[sel SEL_2306F top]
[s]"It's a secret."[e]
[s]"A future with you."[e]
[s]"What about you?"[e]

[msg MSG_2307F [Akihiko]]
[s][bup 7 2 65535 0]What, is it something you can't even[n]tell me about?[n][w][e]
[s]You don't get men, don't you? It's our[n]nature to try and find anything that's[n]hidden from us.[n][w][e]
[s]Watch, I'll have you confessing before[n]we get back to the dorm. Better be[n]ready![n][w][e]

[msg MSG_2308F [ ]]
[s][f 5 13 0 15 0]> Akihiko is laughing happily...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_2309F [Akihiko]]
[s][bup 7 2 65535 0]...Haha. You're such an idiot.[n][w][e]
[s]You don't have to ask God for something[n]like that. I can make that happen all[n]on my own.[n][w][e]
[s][bup 7 1 65535 0]...I promise. You don't need to believe[n]in a god... just believe in me.[n][w][e]
[s]......[n][w][e]
[s][bup 7 2 65535 0]I won't take anything but "yes" for[n]an answer.[n][w][e]

[msg MSG_2310F [ ]]
[s][f 5 13 0 30 0]> Akihiko is laughing happily...[n][w][e]
[s]> Today, your relationhip has grown[n]stronger...[n][w][e]

[msg MSG_2311F [Akihiko]]
[s][bup 7 1 65535 0]...Hm? Can't you tell?[n][w][e]
[s]I thought you'd be able to guess.[n][w][e]
[s][bup 7 2 65535 0]...Too bad, time's up.[n][w][e]
[s]As punishment, let's have you grant[n]me my wish.[n][w][e]

[msg MSG_2312F [ ]]
[s][f 5 13 0 15 0]> Akihiko is laughing happily...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_2313F [ ]]
[s]> It's starting to get dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_84_F]
[s]> Iwatodai strip mall,[n]Sweet Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Yukari.[n][w][e]

[msg MSG_85_F [Yukari]]
[s][bup 2 2 65535 0]Mmmm... That was sooo good![n][w][e]
[s][f 6 1 1 0 2 6]Nothing beats strawberry rice cake[n]with red beans![n][w][e]

[msg MSG_88_F]
[s]> Yukari seems to be enjoying her[n]day off...[n][w][e]

[msg MSG_89_F [Yukari]]
[s][bup 2 1 65535 0]I like all types of sweets, but[n]strawberry rice cake is still[n]the best.[n][w][e]

[msg MSG_90_F [ ]]
[s]> Yukari is nodding seriously...[n][w][e]

[msg MSG_91_F [Yukari]]
[s][bup 2 2 65535 0]Hey, don't you think the person who[n]invented strawberry rice cake is[n]a genius?[n][w][e]

[sel SEL092F top]
[s]"Definitely."[e]
[s]"Aren't you exaggerating?"[e]
[s]"Banana ones are better."[e]

[msg MSG_93_F [Yukari]]
[s][bup 2 2 65535 0]That pink skin makes it look like it's[n]saying, "Eat me"![n][w][e]
[s]I just love the outer skin![n][w][e]

[msg MSG_94_F [ ]]
[s][f 5 13 0 15 0]> Yukari seems happy...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_95_F [Yukari]]
[s][bup 2 5 65535 0]Huh? That's not true. I mean, it's[n]rice cakes and strawberries! Two great[n]tastes that go great together![n][w][e]
[s]If I was Mr. Nobel, I bet I'd give the[n]inventory one of my prizes for it.[n][w][e]

[msg MSG_96_F [ ]]
[s][f 5 13 0 15 0]> Yukari is desperately trying to[n]explain herself...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_97_F [Yukari]]
[s][bup 2 5 65535 0]Ooh, do you like that kind? That soft[n]texture bananas have is great too.[n][w][e]
[s]But banana rice cakes have a yellow[n]skin. The pink skin on the strawberry[n]ones gets me salivating more.[n][w][e]
[s]Then again, a girl in class told me[n]that there's banana rice cakes at this[n]one store people are lining up for...[n][w][e]

[msg MSG_98_F [ ]]
[s][f 5 13 0 30 0]> Yukari's excitement won't stop.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_99_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_84_02_F]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time hanging[n]out with Yukari.[n][w][e]

[msg MSG_85_02_F [Yukari]]
[s][bup 2 5 65535 0][f 6 1 1 0 2 1]Wow, it's already getting dark out...[n][w][e]
[s]I didn't realize we were in there so[n]long.[n][w][e]

[msg MSG_88_02_F]
[s]> Yukari seems to be enjoying herself.[n][w][e]

[msg MSG_89_02_F [Yukari]]
[s][bup 2 2 65535 0]I read through all the shoujo manga I[n]used to collect.[n][w][e]
[s]Do you ever get the sudden urge to read[n]pure romances sometimes?[n][w][e]
[s]The last one I was reading is about a[n]girl who has an unrequited love for[n]a boy in another class...[n][w][e]

[msg MSG_90_02_F [ ]]
[s]> Yukari is exuberantely relating the[n]manga's story to you...[n][w][e]

[msg MSG_91_02_F [Yukari]]
[s][bup 2 5 65535 0]...Huh? Why do you seem so bored?[n]Do you not like romance manga?[n][w][e]

[sel SEL092_02F top]
[s]"I love them."[e]
[s]"I read them sometimes."[e]
[s]"I'll never read them."[e]

[msg MSG_93_02_F [Yukari]]
[s][bup 2 2 65535 0]Whew, I'm glad to hear that.[n][w][e]
[s]In real life, there's no way an eloquent[n]boy like him would exist, and the girl[n]was so nice it seemed fake...[n][w][e]
[s]Still, though, it makes me feel better[n]in the end.[n][w][e]

[msg MSG_94_02_F [ ]]
[s][f 5 13 0 30 0]> Yukari seems to be having a lot of fun...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_95_02_F [Yukari]]
[s][bup 2 2 65535 0]Oh, really?[n][w][e]
[s]It's important to get a little bit of[n]that pureness back once in a while,[n]I guess.[n][w][e]

[msg MSG_96_02_F [ ]]
[s][f 5 13 0 15 0]> Yukari is nodding...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_97_02_F [Yukari]]
[s][bup 2 5 65535 0]Huh? Really?[n][w][e]
[s]Wow, I didn't know there were girls like[n]that. So what do you read, then? Shonen[n]stuff?[n][w][e]
[s][bup 2 2 65535 0]Aren't those ones just nonsense with[n]one fight after another?[n][w][e]
[s]They focus so much on the training and[n]getting stronger that the setup from[n]the beginning ends up getting lost.[n][w][e]
[s][bup 2 7 65535 0]...Well, I still don't hate them,[n]even with that.[n][w][e]

[msg MSG_98_02_F [ ]]
[s][f 5 13 0 15 0]> Yukari seems a little embarrassed...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_99_02_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_100_F]
[s]> Iwatodai strip mall,[n]Sweet Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Fuuka.[n][w][e]

[msg MSG_101_F [Fuuka]]
[s][bup 6 2 65535 0]That anmitsu tasted wonderful. It had[n]just the right amount of sweetness to[n]put a smile on my face.[n][w][e]

[msg MSG_102_F]
[s]> Fuuka seems to be enjoying her[n]day off...[n][w][e]

[msg MSG_103_F [Fuuka]]
[s][bup 6 4 65535 0]I've felt wonderful for a while...[n][w][e]

[msg MSG_104_F [ ]]
[s]> Fuuka is thinking hard...[n][w][e]

[msg MSG_105_F [Fuuka]]
[s][bup 6 1 65535 0]About anmitsu's black color... do you[n]think they use charcoal to color it?[n][w][e]

[sel SEL106F top]
[s]"That's right."[e]
[s]"It's from red beans."[e]
[s]"It's the soy sauce."[e]

[msg MSG_107_F [Fuuka]]
[s][bup 6 2 65535 0]Oh, so it's true then.[n][w][e]
[s]Strange that it's so sweet when there's[n]charcoal in it. I wonder if they use[n]a lot of sugar.[n][w][e]
[s]People say sugar makes you fat,[n]but it actually has some health[n]benefits...[n][w][e]
[s]In fact, glucose is like fuel[n]for your brain.[n][w][e]
[s]It's like when you get hungry[n]because you've been using your[n]mind all day...[n][w][e]
[s]The glucose in your body is being[n]used up and your blood sugar is low.[n][w][e]
[s]And, did you know...[n][w][e]

[msg MSG_108_F [ ]]
[s][f 5 13 0 30 0]> Fuuka started talking passionately...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_109_F [Fuuka]]
[s][bup 6 5 65535 0]The coloring is from red beans!?[n][w][e]
[s][bup 6 1 65535 0]So that's it... I'm surprised it gets[n]that black so beautifully even without[n]the charcoal...[n][w][e]

[msg MSG_110_F [ ]]
[s][f 5 13 0 15 0]> Fuuka is impressed...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_111_F [Fuuka]]
[s][bup 6 5 65535 0]Soy sauce!?[n][w][e]
[s][bup 6 1 65535 0]But, wouldn't it taste saltier if you[n]put that much soy sauce in for coloring?[n][w][e]
[s]No, it's gotta be charcoal. Let's try[n]making some next time, [f 4 2]-chan.[n][w][e]

[msg MSG_112_F [ ]]
[s][f 5 13 0 15 0]> Fuuka seems to be convinced...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_113_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_100_02_F]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_101_02_F [Fuuka]]
[s][bup 6 2 65535 0]What a beautiful day![n][w][e]
[s]I'm surprised there are so many[n]people here today...[n][w][e]
[s]I thought only Port Island got this[n]crowded.[n][w][e]

[msg MSG_102_02_F]
[s]> Fuuka seems to be enjoying her[n]day off...[n][w][e]

[msg MSG_103_02_F [Fuuka]]
[s][bup 6 1 65535 0]You know, I've only been coming here[n]since I moved into the dorms,[n]but I really like it.[n][w][e]

[msg MSG_104_02_F [ ]]
[s]> Fuuka is looking around...[n][w][e]

[msg MSG_105_02_F [Fuuka]]
[s][bup 6 2 65535 0]What do you usually do on days off like[n]this, [f 4 2]-chan?[n][w][e]

[sel SEL106_02F top]
[s]"I stay in my room."[e]
[s]"This, pretty much."[e]
[s]"It's a secret."[e]

[msg MSG_107_02_F [Fuuka]]
[s][bup 6 2 65535 0]Oh, really? I like to spend time in[n]my room, too.[n][w][e]
[s]I sit back, read books, listen to[n]music... It's fun even if I don't go[n]out anywhere.[n][w][e]

[msg MSG_108_02_F [ ]]
[s][f 5 13 0 15 0]> Fuuka seems happy...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_109_02_F [Fuuka]]
[s][bup 6 2 65535 0]Oh, right. I imagine you have a lot[n]of friends.[n][w][e]
[s]I really enjoy going out with you too.[n][w][e]

[msg MSG_110_02_F [ ]]
[s][f 5 13 0 30 0]> Fuuka seems a little embarrassed.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_111_02_F [Fuuka]]
[s][bup 6 1 65535 0]I-I see.[n][w][e]
[s]......[n][w][e]
[s]Um, er...[n][w][e]
[s]Did I ask something that I shouldn't[n]have...?[n][w][e]

[msg MSG_112_02_F [ ]]
[s]> You made Fuuka worry about you.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_113_02_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_100_03_F]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time hanging[n]out with Fuuka.[n][w][e]

[msg MSG_101_03_F [Fuuka]]
[s][bup 6 2 65535 0][f 6 1 1 0 6 11]I finished reading all of "Steel Chef"![n]It was really fun.[n][w][e]
[s]I was curious how the series would end,[n]since it jumped magazines so suddenly.[n][w][e]

[msg MSG_102_03_F]
[s]> Fuuka seems to be enjoying her[n]day off...[n][w][e]

[msg MSG_103_03_F [Fuuka]]
[s][bup 6 2 65535 0]I especially like how the main character[n]Chef Kiraboshi holds kitchen knives in[n]both hands.[n][w][e]
[s]He's really fast at cutting vegetables[n]into tiny pieces... he can even prepare[n]four fish at once![n][w][e]

[msg MSG_104_03_F [ ]]
[s]> Fuuka is excited...[n][w][e]

[msg MSG_105_03_F [Fuuka]]
[s][bup 6 1 65535 0]...Can you prepare fish,[n][f 4 2]-chan?[n][w][e]

[sel SEL106_03F top]
[s]"I'm really good at it."[e]
[s]"I've never tried before."[e]
[s]"I'm too scared to try..."[e]

[msg MSG_107_03_F [Fuuka]]
[s][bup 6 5 65535 0]Wow, really? That's amazing,[n][f 4 2]-chan![n][w][e]
[s][bup 6 4 65535 0]I've never tried... The fish smells[n]bad enough, and those cloudy eyes...[n][w][e]
[s]It's like the fish is glaring at me,[n]saying, "Are you going to cut me up!?"[n]I lose my nerve.[n][w][e]

[msg MSG_108_03_F [ ]]
[s]> Fuuka seems down...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_109_03_F [Fuuka]]
[s][bup 6 1 65535 0]Ah... I'm glad to hear that. Well,[n]that sounds bad, but I mean...[n][w][e]
[s]If we find husbands someday...[n][w][e]
[s]Will we make bad housewives if we[n]can't prepare fish anywhere?[n][w][e]

[msg MSG_110_03_F [ ]]
[s][f 5 13 0 15 0]> Fuuka is imagining various things...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_111_03_F [Fuuka]]
[s][bup 6 2 65535 0]I-I thought so! I'm glad to hear you[n]say that...[n][w][e]
[s]Everything from the smell, the cloudy[n]eyes, and how it seems like it'll jump[n]around suddenly, scares me so much.[n][w][e]

[msg MSG_112_03_F [ ]]
[s][f 5 13 0 30 0]> Fuuka is in vigorous agreement[n]with you.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_113_03_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_114_F]
[s]> Iwatodai strip mall,[n]Beef Bowl Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Mitsuru.[n][w][e]

[msg MSG_115_F [Mitsuru]]
[s][bup 4 1 65535 0]I'm sorry for making you come to a[n]place like this on your day off.[n][w][e]
[s]I wanted to try coming here... I see[n]Akihiko eating it often enough.[n][w][e]

[msg MSG_116_F]
[s]> Mitsuru is smiling wryly...[n][w][e]

[msg MSG_117_F [Mitsuru]]
[s][bup 4 1 65535 0]But there is one thing bothering me...[n][w][e]

[msg MSG_118_F [ ]]
[s]> Mitsuru is thinking hard...[n][w][e]

[msg MSG_119_F [Mitsuru]]
[s][bup 4 1 65535 0]I feel as though we were drawing a greate[n]deal of attention upon entering the[n]restaurant until we left...[n][w][e]
[s]...Was it just my imagination?[n][w][e]

[sel SEL120F top]
[s]"You're imagining things."[e]
[s]"It's because you're hot."[e]
[s]"Girls rarely come here."[e]

[msg MSG_121_F [Mitsuru]]
[s][bup 4 1 65535 0]I-I see. If you say so...[n][w][e]

[msg MSG_122_F [ ]]
[s]> Mitsuru still seems worried.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_123_F [Mitsuru]]
[s][bup 4 7 65535 0]Wh-What're you saying!?[n][w][e]
[s]You won't gain anything with such[n]flattery.[n][w][e]

[msg MSG_124_F [ ]]
[s][f 5 13 0 15 0]> Mitsuru seems embarrassed...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_125_F [Mitsuru]]
[s][bup 4 1 65535 0]I see...[n][w][e]
[s]That's foolish... Everyone should have[n]the freedom to eat whatever they want.[n][w][e]
[s]...Still, it is a difficult dish to eat[n]without making a mess...[n][w][e]
[s]I should respect their feelings of not[n]wanting women to eat such things.[n][w][e]
[s][bup 4 2 65535 0]Thank you for telling me, [f 4 1].[n][w][e]

[msg MSG_126_F [ ]]
[s][f 5 13 0 30 0]> Mitsuru seems happy.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_127_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_114_02_F]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time hanging[n]out with Mitsuru.[n][w][e]

[msg MSG_115_02_F [Mitsuru]]
[s][bup 4 2 65535 0]I didn't realize how many different[n]types of manga there are...[n][w][e]

[msg MSG_116_02_F]
[s]> Mitsuru seems to be a little daunted...[n][w][e]

[msg MSG_117_02_F [Mitsuru]]
[s][bup 4 1 65535 0]I have a question...[n][w][e]

[msg MSG_118_02_F [ ]]
[s]> Mitsuru has a curious look on her[n]face.[n][w][e]

[msg MSG_119_02_F [Mitsuru]]
[s][bup 4 1 65535 0]Why do people go to manga cafes?[n][w][e]
[s]You can't borrow any of the books,[n]like at a library...[n][w][e]
[s]...and you have to pay admission[n]to get in.[n][w][e]
[s]Since manga aren't that expensive,[n]why don't people just buy them?[n][w][e]

[sel SEL120_02F top]
[s]"It's a nice environment."[e]
[s]"It's a little cheaper."[e]
[s]"Lack of storage space."[e]

[msg MSG_121_02_F [Mitsuru]]
[s][bup 4 2 65535 0]I see...[n][w][e]
[s]Well, they do let you eat in here,[n]and it's open late.[n][w][e]

[msg MSG_122_02_F [ ]]
[s][f 5 13 0 15 0]> Mitsuru seems to understand.[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_123_02_F [Mitsuru]]
[s][bup 4 1 65535 0]I suppose that's true.[n][w][e]
[s]But, there's something nice about[n]owning a book, especially one you[n]really love.[n][w][e]
[s][bup 4 2 65535 0]In that case, it's worth buying no[n]matter what the price.[n][w][e]

[msg MSG_124_02_F [ ]]
[s]> Mitsutu doesn't seem convinced...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_125_02_F [Mitsuru]]
[s][bup 4 2 65535 0]That's understandable.[n][w][e]
[s]From that perspective, the cafe is[n]like your own personal library.[n][w][e]
[s]Even though you can't borrow the[n]manga, you can read them whenever[n]you want.[n][w][e]
[s]That's an interesting way to look at it.[n][w][e]

[msg MSG_126_02_F [ ]]
[s][f 5 13 0 30 0]> Mitsuru seems somewhat impressed.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_127_02_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_326_F]
[s]> Iwatodai strip mall,[n]Book On...[n][w][e]
[s]> You're having a good time hanging[n]out with Bebe.[n][w][e]

[msg MSG_327_F [Bebe]]
[s][bup 34 161 65535 0]I like zis place... I feel a little[n]better now...[n][w][e]
[s]......[n][w][e]
[s]*sigh*[n][w][e]

[msg MSG_328_F]
[s]> It seems like Bebe has no energy.[n][w][e]

[msg MSG_329_F [Bebe]]
[s][bup 34 163 65535 0]I always used to call my aunt on ze[n]weekend and 'olidays...[n][w][e]
[s]If she was still alive, I would call[n]'er today...[n][w][e]

[msg MSG_330_F [ ]]
[s]> Bebe seems shocked by the death of[n]his aunt.[n][w][e]

[msg MSG_331_F [Bebe]]
[s][bup 34 161 65535 0]I zink zat I miss my 'ome...[n][w][e]

[sel SEL332F top]
[s]"You're not going back?"[e]
[s]"Stay in Japan."[e]
[s]"What about the funeral?"[e]

[msg MSG_334_F [Bebe]]
[s][bup 34 163 65535 0]Zat eez not what I want.[n][w][e]
[s]I 'ave a bad feeling zat I will not be[n]able to come back if I go...[n][w][e]

[msg MSG_339_F [ ]]
[s]> Bebe seems sad.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_336_F [Bebe]]
[s][bup 34 162 65535 0]I want to! I want to stay in Japan...[n]and stay by your side.[n][w][e]

[msg MSG_337_F [ ]]
[s][f 5 13 0 30 0]> You sense affection from Bebe...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_338_F [Bebe]]
[s][bup 34 162 65535 0]Oh, you are zinking about my aunt![n]You are so kind, [f 4 2]-sama...[n][w][e]
[s]I 'ave a bad feeling zat I will not be[n]able to come back if I go...[n][w][e]
[s]Zat eez why... I can't go back.[n][w][e]

[msg MSG_335_F [ ]]
[s][f 5 13 0 15 0]> Bebe seems deeply touched.[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_340_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_326_02_F]
[s]> Iwatodai strip mall,[n]Sweet Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Bebe.[n][w][e]

[msg MSG_327_02_F [Bebe]]
[s][bup 34 162 65535 0][f 6 1 1 0 34 11]Oishii! Zat was delicious! [n][w][e]

[msg MSG_328_02_F]
[s]> Bebe seems happy...[n][w][e]

[msg MSG_329_02_F [Bebe]]
[s][bup 34 161 65535 0]Japan eez ze only place where you[n]can taste ze true beauty of sugar![n][w][e]

[msg MSG_330_02_F [ ]]
[s]> Bebe seems to love Japanese[n]desserts.[n][w][e]

[msg MSG_331_02_F [Bebe]]
[s][bup 34 161 65535 0]Azuki eez so good![n][w][e]
[s]What eez it made of? It looks[n]like insect eggs...[n][w][e]

[sel SEL332_02F top]
[s]"I don't know."[e]
[s]"It IS bug eggs."[e]
[s]"Why would we eat that!?"[e]

[msg MSG_334_02_F [Bebe]]
[s][bup 34 162 65535 0]Oh! I didn't know zat zere eez[n]a bean zat eez small and red![n][w][e]
[s]My home country, it eez full of[n]bean dishes.[n][w][e]
[s]One day I hope to treat you to zem![n][w][e]

[msg MSG_335_02_F [ ]]
[s][f 5 13 0 30 0]> Bebe seems happy...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_338_02_F [Bebe]]
[s][bup 34 163 65535 0]Hontou!? I was right!?[n][w][e]
[s][bup 34 162 65535 0]I have learned somezing new about[n]Nihon![n][w][e]

[msg MSG_339_02_F [ ]]
[s][f 5 13 0 15 0]> Bebe seems happy...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_336_02_F [Bebe]]
[s][bup 34 163 65535 0]Whew, I am relieved to hear zat.[n][w][e]
[s]Zen, what kind of eggs are zey?[n][w][e]
[s]...Non non, don't tell me![n]It eez better if I don't know![n][w][e]

[msg MSG_337_02_F [ ]]
[s]> Bebe is trembling in fear...[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_340_02_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_326_03_F]
[s]> Iwatodai strip mall,[n]Beef Bowl Shop...[n][w][e]
[s]> You're having a good time hanging[n]out with Bebe.[n][w][e]

[msg MSG_327_03_F [Bebe]]
[s][bup 34 162 65535 0]Umiushi Bowl... Zat was delicious![n]Oishii![n][w][e]

[msg MSG_328_03_F]
[s]> Bebe seems satisfied.[n][w][e]

[msg MSG_329_03_F [Bebe]]
[s][bup 34 162 65535 0][f 6 1 1 0 34 11]Zat kind of meal goes well wiz rice![n][w][e]

[msg MSG_330_03_F [ ]]
[s]> Bebe seems interested in Japanese[n]cuisine.[n][w][e]

[msg MSG_331_03_F [Bebe]]
[s][bup 34 161 65535 0]What do you like to eat wiz rice,[n][f 4 2]-sama?[n][w][e]

[sel SEL332_03F top]
[s]"I don't eat rice."[e]
[s]"Sushi."[e]
[s]"Curry."[e]

[msg MSG_336_03_F [Bebe]]
[s][bup 34 163 65535 0]Honto!? Really!? Zat eez a shame.[n]'ow can you be Japanese and not eat[n]rice?[n][w][e]

[msg MSG_337_03_F [ ]]
[s]> Bebe seems a little angry.[n][w][e]
[s]> Your friendship seems to be stuck in[n]a rut.[n][w][e]

[msg MSG_334_03_F [Bebe]]
[s][bup 34 162 65535 0]Sou desu ne! Zat's right! If you are[n]Japanese, you must eat sushi![n][w][e]

[msg MSG_339_03_F [ ]]
[s][f 5 13 0 30 0]> Bebe seems pleased.[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_338_03_F [Bebe]]
[s][bup 34 162 65535 0]Zat eez an excellent dish![n][w][e]
[s]But I zink sushi is ze best. If you[n]are Japanese, you must eat sushi![n][w][e]

[msg MSG_335_03_F [ ]]
[s][f 5 13 0 15 0]> Bebe is talking passionately about[n]Japanese cuisine...[n][w][e]
[s]> Today, you learned something new[n]about him.[n][w][e]

[msg MSG_340_03_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_114_03]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_115_03 [Mitsuru]]
[s][bup 4 2 65535 0]How strange...[n][w][e]
[s]We aren't doing anything special,[n]yet spending time with you doesn't[n]bore me.[n][w][e]

[msg MSG_116_03]
[s]> Mitsuru seems to be enjoying her[n]day off.[n][w][e]

[msg MSG_117_03 [Mitsuru]]
[s][bup 4 7 65535 0]......[n][w][e]

[msg MSG_118_03 [ ]]
[s]> Mitsuru seems nervous.[n][w][e]

[msg MSG_119_03 [Mitsuru]]
[s][bup 4 7 65535 0]E-Er...[n][w][e]
[s]......[n][w][e]
[s][f 4 2]...[n][w][e]

[sel SEL120_03 top]
[s]"Yes?"[e]
[s]"Did you use my name?"[e]
[s]"Want to go somewhere?"[e]

[msg MSG_121_03 [Mitsuru]]
[s][bup 4 7 65535 0]...N-Nothing.[n][w][e]
[s]I just felt like calling you by[n]your name.[n][w][e]

[msg MSG_122_03 [ ]]
[s][f 5 13 0 15 0]> Mitsuru is unusually hesitant.[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_123_03 [Mitsuru]]
[s][bup 4 7 65535 0]Oh, no...[n][w][e]
[s]I-I just felt like saying your name.[n]Um... I thought that I was coming across[n]a little distant...[n][w][e]

[msg MSG_124_03 [ ]]
[s][f 5 13 0 30 0]> Mitsuru seems embarrassed...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_125_03 [Mitsuru]]
[s][bup 4 7 65535 0]Huh...? Oh no, that's not it.[n][w][e]
[s]It's nothing.[n][w][e]
[s]I just... felt like saying your name.[n][w][e]

[msg MSG_126_03 [ ]]
[s][f 5 13 0 15 0]> Mitsuru is unusually hesitant.[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_127_03 [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_114_03_F]
[s]> Iwatodai strip mall...[n][w][e]

[msg MSG_115_03_F [Mitsuru]]
[s][bup 4 2 65535 0]How odd...[n][w][e]
[s]We aren't doing anything special,[n]yet spending time with you doesn't[n]bore me.[n][w][e]

[msg MSG_116_03_F]
[s]> Mitsuru seems to be enjoying[n]herself.[n][w][e]

[msg MSG_117_03_F [Mitsuru]]
[s][bup 4 1 65535 0]I thought until now that I'd always be[n]my "true self"...[n][w][e]
[s]Oh, er, what I mean by that is...[n]How should I explain this...?[n][w][e]

[msg MSG_118_03_F [ ]]
[s]> Mitsuru is, for once, at a loss[n]for words.[n][w][e]

[msg MSG_119_03_F [Mitsuru]]
[s][bup 4 1 65535 0]I never paid the timid, cowardly side[n]of myself any heed.[n][w][e]
[s]Meeting everyone's expectations and[n]performing my duties... I thought that[n]was all there was to me.[n][w][e]
[s][bup 4 2 65535 0]*chuckle* I am such a fool...[n][w][e]

[sel SEL120_03_F top]
[s]"That's not true."[e]
[s]"Glad you realized it!"[e]
[s]"Everyone's that way."[e]

[msg MSG_121_03_F [Mitsuru]]
[s][bup 4 2 65535 0]...Thank you.[n][w][e]
[s]My own weakness, that I never cared to[n]admit... I feel as though I can come[n]to accept it now.[n][w][e]
[s]It's all thanks to you...[n][w][e]

[msg MSG_122_03_F [ ]]
[s][f 5 13 0 15 0]> Mitsuru is smiling...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_123_03_F [Mitsuru]]
[s][bup 4 2 65535 0]*chuckle*[n][w][e]
[s]I see. If you say so, then that's how[n]I feel as well...[n][w][e]
[s]My own weakness, that I never cared to[n]admit... I feel as though I can come[n]to accept it now.[n][w][e]
[s]It's all thanks to you...[n][w][e]

[msg MSG_124_03_F [ ]]
[s][f 5 13 0 30 0]> Mitsuru is smiling...[n][w][e]
[s]> Today, your friendship has grown[n]stronger...[n][w][e]

[msg MSG_125_03_F [Mitsuru]]
[s][bup 4 2 65535 0]I see... You're right. There's nothing[n]unique about what I'm going through.[n][w][e]
[s]*chuckle* I learn so much from you.[n][w][e]
[s]My own weakness, that I never cared to[n]admit... I feel as though I can come[n]to accept it now.[n][w][e]
[s]It's all thanks to you...[n][w][e]

[msg MSG_126_03_F [ ]]
[s][f 5 13 0 15 0]> Mitsuru is smililng...[n][w][e]
[s]> Today, you learned something new[n]about her.[n][w][e]

[msg MSG_127_03_F [ ]]
[s]> It's getting dark out.[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

