[sel LABORATORY_SEL top]
[s]Enter[e]
[s]Never mind[e]

[msg FIRE_EXIT]
[s]> The emergency exit is locked.[n][w][e]

[msg FIRE_EXIT_OPERATION]
[s]> The emergency exit is unlocked.[n][w][e]
[s]> It must be Junpei's doing.[n][w][e]

[msg FIRE_EXIT_OPERATION_YUKA [Yukari]]
[s][bup 2 201 0 0]That idiot, Junpei...[n][w][e]
[s]This is practically breaking and[n]entering.[n][w][e]

[msg BROADCASTING_ROOM]
[s]> It's the PA room.[n][w][e]

[msg HEAR_STRANGE_BGM]
[s]> You hear bizarre music playing[n]inside.[n][w][e]

[msg STRANGE_BGM [Male Student's Voice]]
[s]What the heck...!?[n][w][e]
[s]..."Gekkoukan Boogie"?[n][w][e]
[s]Why does the school have music like[n]this...?[n][w][e]
[s]...Must be a teacher's theme song or[n]something.[n][w][e]
[s]...Crazy. *chuckle*[n][w][e]

[msg BROADCASTING_ROOM_INTO_O]
[s]> Would you like to enter?[n][w][e]

[msg BROADCASTING_ROOM_INTO [Male Student]]
[s]Sorry, you have to have permission to[n]be in--[n][w][e]
[s]Huh? This music?[n][w][e]
[s]I have no idea what it's for, but it[n]says "Gekkoukan Boogie" on it.[n][w][e]
[s]Huh? You want it? ...Are you[n]serious!?[n][w][e]
[s]Sure, you can have it. We don't have[n]any use for it, anyway... Here...[n][w][e]
[s]Now, get out of here, before you get[n]me in trouble.[n][w][e]

[msg GET_CD]
[s]> Obtained [f 2 5 3 13 0].[n][w][e]

[msg ROOM_2E]
[s]> It's Class E's homeroom.[n][w][e]

[msg SEITOKAI_TEST]
[s]This is the student council room.[n]There are no students inside.[n][w][e]

[msg STOP_TO_ROOFTOP [Yukari]]
[s][bup 2 201 0 0]*sigh* Can we look for the keys,[n]already?[n][w][e]

[msg STOP_TO_ROOFTOP_SANADA [Akihiko]]
[s][bup 7 201 0 0]Hey, that leads to the rooftop.[n]We're going the wrong way.[n][w][e]

[msg STOP_TO_ROUNDABOUT_WAY [Yukari]]
[s][bup 2 201 0 0]The others will search that way.[n][w][e]
[s]We're s'posed to go to the office,[n]remember?[n][w][e]

[msg STOP_TO_CLASSROOM [Yukari]]
[s][bup 2 201 0 0]Hey, what are we doing back in the[n]classroom? Can we get to the office[n]already!?[n][w][e]

[msg STOP_TO_CLASSROOM_SANADA [Akihiko]]
[s][bup 7 203 0 0]Hey, where are you going!?[n]Let's hurry up and go to the[n]Faculty Office![n][w][e]

[msg DONOTUSE_MESSAGE]
[s]このメッセージは謁です。[n]亥わないように。[n][w][e]

[sel YESNO_SEL top]
[s]Yes[e]
[s]No[e]

[sel INTO_SEL top]
[s]Enter[e]
[s]Don't enter[e]

[sel BUKATU_NYUUBU_SEL top]
[s]Join the club[e]
[s]Observe[e]
[s]Leave[e]

[sel SCHOOL_SHOTCUTSEL top]
[s]1F, Main Lobby[e]
[s]1F, Faculty Office Hallway[e]
[s]1F, Laboratory Hallway[e]
[s]1F, Corridor[e]
[s]1F, Gym Hallway[e]
[s]2F, Classroom Hallway[e]
[s]Classroom[e]
[s]Rooftop[e]
[s]Entranceway[e]
[s]Town Map[e]
[s]Cancel[e]

[msg ZOKUSEI_KAKUNIN]
[s]> [f 2 4 1] Social Link[n]rank [clr 2][f 2 4 4][clr 0].[n][w][e]
[s]> The Arcana is [f 2 4 2].[n][f 2 4 3][w][e]
[s]> You can see the powers of the[n][f 2 4 2] Persona...[n][w][e]

[msg PER_KOE]
[s][f 2 4 1], Level [f 2 4 0][n] [n]Available skills:[n]  [f 2 4 2][n]  [f 2 4 3][n]  [f 2 4 4][n][w][e]

[msg ZOKUSEI_NOTYET]
[s]> It seems further power lies hidden...[n][w][e]

[msg ZOKUSEI_NOMORE]
[s]> No further power is available.[n][w][e]

[msg MSG_DOUZOKUSEI [ ]]
[s][f 4 7 0 0 0]> Since you have the [f 2 4 2][n]Persona, "[clr 1][f 2 4 5][clr 0]", you might[n]be able to become even closer...[n][w][e]

[msg FLD_ORDER]
[s]Where do you want to go?[n][w][e]

[msg STOP_2F [Yukari]]
[s][bup 2 201 0 0]C'mon, hurry! Before the Dark Hour[n]comes![n][w][e]

[msg STOP_2F_SANADA [Akihiko]]
[s][bup 7 201 0 0]The Dark Hour's going to come if we[n]don't hurry. There's no time to waste![n][w][e]

[msg TOILET_MENS]
[s]> It's the men's room.[n][w][e]

[msg TOILET_OUT]
[s]> You relieved yourself.[n][w][e]

[msg TOILET_MENS_STOP [Yukari]]
[s][bup 2 203 0 0]Can't you hold it!?[n][w][e]
[s]...Fine! But hurry up, okay!?[n][w][e]

[msg TOILET_MENS_STOP_PART2 [Yukari]]
[s][bup 2 203 0 0]Huh? Again!?[n][w][e]
[s]...You're doing this on purpose,[n]aren't you!?[n][w][e]

[msg TOILET_MENS_STOP_SANADA [Akihiko]]
[s][bup 7 203 0 0]Hey, where are you going!? We need to[n]hurry up and go to the Faculty Office![n][w][e]

[msg TOILET_NORMAL_TO_BEST]
[s]> Your condition has become[n]"[clr 2]Great[clr 0]."[n][w][e]

[msg TOILET_TIRED_TO_NORMAL]
[s]> Your condition has become[n]"[clr 2]Good[clr 0]."[n][w][e]

[msg TOILET_COLD_TO_TIRED]
[s]> Your condition has become[n]"[clr 2]Tired[clr 0]."[n][w][e]

[msg TOILET_BEST]
[s]> Your body is in excellent condition.[n][w][e]

[msg TOILET_GOOD]
[s]> Your body is in average condition.[n][w][e]

[msg TOILET_BAD]
[s]> You are not feeling so well.[n][w][e]

[msg TOILET_WOMENS]
[s]> It's the women's room.[n][w][e]

[msg TOILET_WOMENS_STOP [Yukari]]
[s][bup 2 203 0 0]Hey! Where do you think you're going!?[n][w][e]

[msg TOILET_WOMENS_OUT]
[s]> Your mind wanders as you wash[n]your hands...[n][w][e]

[msg TOIRE_TESTKIKAN]
[s]> You recall that you have exams coming[n]up soon.[n][w][e]
[s]> It seems that Mitsuru will reward you[n]if you do well on them...[n][w][e]

[msg TOIRE_TUUHAN]
[s]> You recall that there's a TV shopping[n]program that shows on Sunday afternoons...[n][w][e]
[s]> What product could they be offering[n]next...?[n][w][e]

[msg TOIRE_UNDOUBU]
[s]> You vaguely recall that one of your[n]clubs meets today...[n][w][e]
[s]> What should you do after school...?[n][w][e]

[msg TOIRE_IINKAI]
[s]> You vaguely recall that your school[n]committee meets today...[n][w][e]
[s]> What should you do after school...?[n][w][e]

[msg TOIRE_HIROU]
[s]> Your body feels tired...[n][w][e]
[s]> You might feel better if you go to[n]bed early or spend time in a store[n]where you can relax...[n][w][e]

[msg TOIRE_GAKURYOKU]
[s]> You feel like you could still be[n]better academically...[n][w][e]
[s]> It seems that there are people who[n]you can't become acquainted with unless[n]your Academics are high enough...[n][w][e]
[s]> You wonder if you should study more...[n][w][e]

[msg TOIRE_MIRYOKU]
[s]> You feel like you could still be[n]more charming than you are now...[n][w][e]
[s]> It seems that there are people who[n]you can't become acquainted with unless[n]your Charm is high enough...[n][w][e]
[s]> Is there anywhere you can go to[n]increase your Charm...?[n][w][e]

[msg TOIRE_YUUKI]
[s]> You feel like you can still become[n]more courageous...[n][w][e]
[s]> It seems that there are people who[n]you can't become acquainted with unless[n]your Courage is high enough...[n][w][e]
[s]> Is there anywhere you can go to[n]increase your Courage...?[n][w][e]

[msg TOIRE_CARD]
[s]> You recall that you left a skill[n]card at Naganaki Shrine...[n][w][e]
[s]> When will it be ready...?[n][w][e]

[msg TOIRE_ZEKKOU_DUNGEON]
[s]> You feel amazingly well today...[n][w][e]
[s]> You feel that you'll be able to[n]fight wonderfully...[n][w][e]

[msg TOIRE_IRAI]
[s]> You wonder if there are any requests[n]you could accept in the Velvet Room...[n][w][e]

[msg TOIRE_SISSOU]
[s]> You recall that there's someone[n]trapped in Tartarus.[n][w][e]
[s]> You need to go rescue them as soon[n]as possible...[n][w][e]

[msg TOIRE_NOMESSAGE]
[s]> What should you do today...?[n][w][e]

[msg TOIRE_OPERATION]
[s]> You need to hurry and go to the[n]faculty office...[n][w][e]

[msg SCR_MSG_SIKENMAE_NG]
[s]> It's locked. You wonder if it's[n]because of exams...[n][w][e]

[msg SCR_MSG_ENDING_NG]
[s]> It's locked.[n][w][e]

[msg SCR_MSG_TAIIN_COMMU_NG]
[s]> No one is here today.[n][w][e]

[msg SCR_MSG_SEITOKAI_01]
[s]> This is the Student Council Room.[n][w][e]

[msg SCR_MSG_SEITOKAI_02]
[s]> Would you like to spend some time[n]after school in the Student Council[n]Room?[n][w][e]

[sel SEITOKAI_COMMU_SEL top]
[s]Attend Student Council[e]
[s]Check Social Link rank[e]
[s]Do nothing[e]

[msg SCR_MSG_SEITOKAI_SURU]
[s][f 5 13 0 10 0]> You have decided to spend some time[n]after school in the Student Council Room.[n][w][e]

[msg SEITOKAI_KYOKA_ARI]
[s]> You have permission to join Student[n]Council. Would you like to enter the[n]room and introduce yourself?[n][w][e]

[msg SEITOKAI_KYOKA_NASI]
[s]> You are not yet a member of[n]Student Council.[n][w][e]
[s]> You must speak to [clr 2]Ms. Toriumi[clr 0] [n]to join.[n][w][e]

[msg STUDENT_COUNCIL]
[s]> The room is locked.[n][w][e]

[msg STUDENT_COUNCIL_02]
[s]> Will you enter?[n][w][e]

[msg STUDENT_COUNCIL_03]
[s]> The door is locked.[n][w][e]
[s]> There's a note that says, "Meetings:[n][clr 2]Mon[clr 0], [clr 2]Wed[clr 0], [clr 2]Fri[clr 0]."[n][w][e]

[msg SCR_MSG_DOUKOUKAI_01]
[s]> This is the Home Economics Room.[n][w][e]

[msg SCR_MSG_DOUKOUKAI_02 [ ]]
[s]> The club meets today.[n][w][e]
[s]> Should you spend time after school[n]at the club...?[n][w][e]

[msg SCR_MSG_KATEIKA_02 [ ]]
[s]> The cooking club meets today.[n][w][e]
[s]> Should you spend time after school[n]at the cooking club...?[n][w][e]

[sel DOUKOUKAI_COMMU_SEL top]
[s]Enter the Home Ec Room[e]
[s]Check Social Link rank[e]
[s]Do nothing[e]

[sel KATEIKA_COMMU_SEL top]
[s]Spend time at the cooking club[e]
[s]Check Social Link rank[e]
[s]Do nothing[e]

[msg SCR_MSG_DOUKOUKAI_SURU]
[s][f 5 13 0 10 0]> You have decided to spend some time[n]in the Home Economics Room.[n][w][e]

[msg SCR_MSG_KATEIKA_SURU]
[s][f 5 13 0 10 0]> You have decided to spend some time[n]at the cooking club.[n][w][e]

[msg SCR_MSG_DOUKOU_MADA [ ]]
[s]> There's a note on the door.[n][w][e]
[s]> It appears to be a mixture of[n]Japanese and some other language.[n][w][e]
[s]> ......[n][w][e]
[s]> In order for you to understand it,[n]you need to improve your Academics.[n][w][e]
[s]> You must be at least [clr 2]Average[clr 0].[n][w][e]

[msg SCR_MSG_DOUKOU_KAIKIN [ ]]
[s]> There's a note on the door.[n][w][e]
[s]> Considering your academic ability,[n]you are easily able to translate it.[n][w][e]
[s]> ......[n][w][e]
[s]> It says: "Join Fashion Club![n]Meetings are [clr 2]Tues[clr 0], [clr 2]Wed[clr 0], [clr 2]Fri[clr 0]."[n][w][e]

[msg SCR_MSG_DOUKOU_KAIKIN_02 [ ]]
[s]> Would you like to enter?[n][w][e]

[sel DOUKOU_KAIKIN_SEL top]
[s]Enter[e]
[s]Don't enter[e]

[msg SCR_MSG_KATEIKA_NG]
[s]> There's a note on the door.[n][w][e]
[s]> Considering your academic ability,[n]you are easily able to translate it.[n][w][e]
[s]> ......[n][w][e]
[s]> It says: "You never came. Sorry,[n]I am gone now."[n][w][e]

[msg SCR_MSG_DOUKOU_KATUDOU_N [ ]]
[s]> There's a note that says, "Meetings[n]are [clr 2]Tues[clr 0], [clr 2]Wed[clr 0], [clr 2]Fri[clr 0]."[n][w][e]

[msg SCR_MSG_DOUKOUKAI_RVS]
[s]> There's a note that says, "Meeting[n]canceled due to depression."[n][w][e]

[msg SCR_MSG_DOUKOUKAI_MAX]
[s]> There's a note that says, "I am[n]taking a trip. Please wait for me!"[n][w][e]

[msg SCR_MSG_TAIIKUKAI_02 [ ]]
[s]> Would you like to attend [f 5 3 0][n]practice after school?[n][w][e]

[sel TAIIKUKAI_COMMU_SEL top]
[s]Go to [f 5 3 0] practice[e]
[s]Check Social Link rank[e]
[s]Do nothing[e]

[msg SCR_MSG_TAIIKUKAI_SURU]
[s][f 5 13 0 10 0]> You have decided to go to [f 5 3 0][n]practice.[n][w][e]

[msg SCR_MSG_TAIIKUKAI_NG [ ]]
[s]> There's a note that says, "Practices[n]are [clr 2]Mon[clr 0], [clr 2]Tues[clr 0], [clr 2]Thurs[clr 0], [clr 2]Fri[clr 0]."[n][w][e]

[msg SCR_MSG_TAIIKUKAI_NG_F [ ]]
[s]> There's a note that says, "Practices[n]are [clr 2]Mon[clr 0], [clr 2]Wed[clr 0], [clr 2]Fri[clr 0]."[n][w][e]

[msg SCR_MSG_GROUND_HAIRU]
[s]> This door leads outside to the[n]practice field.[n][w][e]

[msg SCR_MSG_GROUND_1ST]
[s]> This door leads outside to where[n]the Track Team is practicing.[n][w][e]
[s]> There's a note that says,[n]"Track Team - recruiting new members![n]No slowpokes, please!"[n][w][e]
[s]> Would you like to join?[n][w][e]

[msg SCR_MSG_GROUND_KENGAKU]
[s]> This door leads outside to where[n]the Track Team is practicing.[n][w][e]
[s]> Would you like to observe?[n][w][e]

[msg SCR_MSG_GROUND_NYUUBU_NG]
[s]> This door leads outside to where[n]the Track Team is practicing.[n][w][e]
[s]> There's a note that says, "Sorry,[n]but the Track Team is no longer[n]recruiting new members."[n][w][e]

[msg SCR_MSG_TENNIS_HAIRU]
[s]> It's the door to the field.[n][w][e]

[msg SCR_MSG_TENNIS_1ST]
[s]> The girls' tennis club seems to be[n]using the field to practice.[n][w][e]
[s]> A note on the door reads,[n]"Girls' Tennis Club seeks new members![n]No experience necessary!"[n][w][e]
[s]> Would you like to join?[n][w][e]

[msg SCR_MSG_TENNIS_KENGAKU]
[s]> The girls' tennis club seems to be[n]using the field to practice.[n][w][e]
[s]> Would you like to observe?[n][w][e]

[msg SCR_MSG_TENNIS_NYUUBU_NG]
[s]> The girls' tennis club seems to be[n]using the field to practice.[n][w][e]
[s]> A note on the door reads,[n]"Sorry, the girls' tennis club is no[n]longer recruiting new members."[n][w][e]

[msg SCR_MSG_TAIKUKAN_HAIRU]
[s]> It's the door to the gym.[n][w][e]

[msg SCR_MSG_TAIKUKAN_1ST]
[s]> The Kendo Team seems to be using[n]the gym.[n][w][e]
[s]> There's a note that says,[n]"Kendo Team - recruiting new members![n]Fight like a samurai!"[n][w][e]
[s]> Would you like to join?[n][w][e]

[msg SCR_MSG_TAIKUKAN_KENGAKU]
[s]> The Kendo Team seems to be using[n]the gym.[n][w][e]
[s]> Would you like to observe?[n][w][e]

[msg SCR_MSG_TAIKUKAN_NYUUBU_]
[s]> The Kendo Team seems to be using[n]the gym.[n][w][e]
[s]> There's a note that says, "Sorry,[n]but the Kendo Team is no longer[n]recruiting new members."[n][w][e]

[msg SCR_MSG_VOLLEY_HAIRU]
[s]> It's the door to the gym.[n][w][e]

[msg SCR_MSG_VOLLEY_1ST]
[s]> The girls' volleyball club seems[n]to be using the gym.[n][w][e]
[s]> A note on the door reads,[n]"Girls' volleyball is now seeking new[n]members! Newbies welcome! Come on in!"[n][w][e]
[s]> Would you like to join?[n][w][e]

[msg SCR_MSG_VOLLEY_KENGAKU]
[s]> The girls' volleyball club seems[n]to be using the gym.[n][w][e]
[s]> Would you like to observe?[n][w][e]

[msg SCR_MSG_VOLLEY_NYUUBU_NG]
[s]> The girls' volleyball club seems[n]to be using the gym.[n][w][e]
[s]> A note on the door reads,[n]"The girls' volleyball club is no longer[n]recruiting. Sorry!"[n][w][e]

[msg SCR_MSG_POOL_HAIRU]
[s]> The door leads to the swimming pool.[n][w][e]

[msg SCR_MSG_POOL_1ST]
[s]> The Swim Team seems to be using[n]the pool.[n][w][e]
[s]> There's a note that says,[n]"Swim Team - recruiting new members![n]Can you swim like a dolphin?"[n][w][e]
[s]> Would you like to join?[n][w][e]

[msg SCR_MSG_POOL_KENGAKU]
[s]> The Swim Team seems to be using[n]the pool.[n][w][e]
[s]> Would you like to observe?[n][w][e]

[msg SCR_MSG_POOL_NYUUBU_NG]
[s]> The Swim Team seems to be using[n]the pool.[n][w][e]
[s]> There's a note that says, "Sorry,[n]but the Swim Team is no longer[n]recruiting new members."[n][w][e]

[msg SCR_MSG_POOL_NYUUBU_NG_G]
[s]> The Swim Team seems to be using[n]the pool.[n][w][e]
[s]> ......[n][w][e]
[s]> It seems that this school only has[n]a men's swim team...[n][w][e]

[msg SCR_MSG_KAKINOKI_MADA [ ]]
[s]> A small tree is growing here.[n][w][e]
[s]> You wonder what kind of tree it is.[n][w][e]

[msg SCR_MSG_KAKINOKI_KIITA [ ]]
[s]> A small tree is growing here.[n][w][e]
[s]> It must be the persimmon tree that[n]the old couple at the bookstore was[n]talking about.[n][w][e]

[msg SCR_MSG_KAKINOKI_GET [ ]]
[s]> ......[n][w][e]
[s]> You found a leaf on the ground.[n][w][e]
[s]> Obtained [f 4 4 3 0 1565].[n][w][e]

[msg SCR_MSG_KAKINOKI_AFTER [ ]]
[s]> A small tree is growing here.[n][w][e]
[s]> It seems to have special meaning for[n]the old couple at the bookstore.[n][w][e]

[msg SCR_MSG_ANSITU_HAIRU]
[s]> This room is for the Photography[n]Club.[n][w][e]

[msg SCR_MSG_ANSITU_1ST]
[s]> It seems to be the dark room for[n]the Photography Club.[n][w][e]
[s]> There's a note that says,[n]"Photography Club - new members[n]welcome! Picture yourself here!"[n][w][e]
[s]> Would you like to join?[n][w][e]

[msg SCR_MSG_ANSITU_KENGAKU]
[s]> It seems to be the dark room for[n]the Photography Club.[n][w][e]
[s]> Would you like to observe the club?[n][w][e]

[msg SCR_MSG_ANSITU_NYUUBU_NG]
[s]> It seems to be the dark room for[n]the Photography Club.[n][w][e]
[s]> There's a note that says, "Sorry,[n]but the Photography Club is no longer[n]accepting new members."[n][w][e]

[msg SCR_MSG_BUNKABU_02 [ ]]
[s]> Would you like to attend[n][f 5 3 1]?[n][w][e]

[sel BUNKABU_COMMU_SEL top]
[s]Attend [f 5 3 1][e]
[s]Check Social Link rank[e]
[s]Do nothing[e]

[msg SCR_MSG_BUNKABU_SURU]
[s][f 5 13 0 10 0]> You have decided to spend some time[n]after school at [f 5 3 1] Club.[n][w][e]

[msg SCR_MSG_BUNKABU_NG [ ]]
[s]> There's a note that says, "Meetings:[n][clr 2]Tues[clr 0], [clr 2]Wed[clr 0], [clr 2]Thur[clr 0]."[n][w][e]

[msg SCR_MSG_KANGEN_HAIRU]
[s]> It's the music room.[n][w][e]

[msg SCR_MSG_KANGEN_1ST]
[s]> It seems to be the room where the[n]Music Club meets.[n][w][e]
[s]> There's a note that says,[n]"Music Club - new members welcome![n]Classical music is our forte!"[n][w][e]
[s]> Would you like to join?[n][w][e]

[msg SCR_MSG_KANGEN_KENGAKU]
[s]> It seems to be the room where the[n]Music Club meets.[n][w][e]
[s]> Would you like to observe the club?[n][w][e]

[msg SCR_MSG_KANGEN_NYUUBU_NG]
[s]> It seems to be the room where the[n]Music Club meets.[n][w][e]
[s]> There's a note that says, "Sorry,[n]but the Music Club is no longer[n]accepting new members."[n][w][e]

[msg SCR_MSG_BIJUTU_HAIRU]
[s]> It's the art room.[n][w][e]

[msg SCR_MSG_BIJITU_1ST]
[s]> It seems to be the room where the[n]Art Club meets.[n][w][e]
[s]> There's a note that says,[n]"Art Club - new members welcome![n]Paint the world with color!"[n][w][e]
[s]> Would you like to join?[n][w][e]

[msg SCR_MSG_BIJUTU_KENGAKU]
[s]> It seems to be the room where the[n]Art Club meets.[n][w][e]
[s]> Would you like to observe the club?[n][w][e]

[msg SCR_MSG_BIJUTU_NYUUBU_NG]
[s]> It seems to be the room where the[n]Art Club meets.[n][w][e]
[s]> There's a note that says, "Sorry,[n]but the Art Club is no longer[n]accepting new members."[n][w][e]

[msg SCR_MSG_SHOKUIN_NG [ ]]
[s]> It's the Faculty Office.[n][w][e]
[s]> It wouldn't be wise to enter without[n]a good reason.[n][w][e]

[msg SCR_MSG_MARCH_NETCOMMU [ ]]
[s]> It's the Faculty Office.[n][w][e]
[s]> ...You can hear Ms. Toriumi's[n]voice from within.[n][w][e]
[s]> Go inside?[n][w][e]

[sel MARCH_NETCOMMU_SEL top]
[s]Enter[e]
[s]Don't enter[e]

[msg SCR_MSG_TOSHOSITU_HAIRU]
[s]> It's the library.[n][w][e]

[msg SCR_MSG_TOSHOSITU_HAIRU0]
[s]> Would you like to study here?[n][w][e]

[sel TOSHO_JISHUU_SEL top]
[s]Study before going home[e]
[s]Never mind[e]

[msg PARAM_MAX_NG]
[s]> Your Academics are already ranked[n]highly.[n][w][e]

[msg MARCH_TOSHO_MAX]
[s]> You remember how you and Saori worked[n]together as members of the library[n]committee here...[n][w][e]

[msg MARCH_TOSHO_MAX_AFTER]
[s]> There is no need to come here[n]anymore...[n][w][e]

[msg TOSHO_COMMU_01]
[s]> The library committee members meet[n]today.[n][w][e]

[msg TOSHO_COMMU_02 [ ]]
[s]> Should you perform your duties as a[n]member of the library committee...?[n][w][e]

[sel TOSHO_COMMU_SEL top]
[s]Perform library committee duties[e]
[s]Check Social Link rank[e]
[s]Never mind[e]

[msg TOSHO_COMMU_SURU]
[s][f 5 13 0 10 0]> You decided to help the library[n]committee after school today.[n][w][e]

[msg SCR_MSG_HOKEN [ ]]
[s]> It's the nurse's office.[n][w][e]

[msg SCR_MSG_HOKEN_NG [ ]]
[s]> You've already taken your medicine[n]today.[n][w][e]

[msg SCR_MSG_HOKEN_HOSHU_NG [ ]]
[s]> You've already had your lesson[n]for today...[n][w][e]

[msg SCR_MSG_HOKEN_HOSHU [ ]]
[s]> Though you're feeling fine,[n]you might be able to take some[n]health lessons.[n][w][e]

[sel HOKEN_HOSHU_SEL top]
[s]Go in for a lesson[e]
[s]Go in for no reason[e]
[s]Do nothing[e]

[msg MARCH_HOKEN_MAX]
[s]> You remember how you and Saori worked[n]together as members of the school health[n]committee here...[n][w][e]

[msg MARCH_HOKEN_MAX_AFTER]
[s]> There is no need to come here[n]anymore...[n][w][e]

[msg HOKEN_COMMU_01]
[s]> The health committee meets today.[n][w][e]

[msg HOKEN_COMMU_02 [ ]]
[s]> Should you perform your duties as a[n]member of the health committee...?[n][w][e]

[sel HOKEN_COMMU_SEL top]
[s]Perform health committee duties[e]
[s]Check Social Link rank[e]
[s]Never mind[e]

[msg HOKEN_COMMU_SURU]
[s][f 5 13 0 10 0]> You decided to help the health[n]committee after school today.[n][w][e]

[msg HOKEN_HIROU]
[s]> You aren't feeling well today.[n][w][e]

[msg shortcut_test]
[s]You are currently in area[n][f 2 4 0].[n][w][e]

[msg RankupReady]
[s]> You feel your relationship with [f 2 4 7] is[n]going to become closer soon...[n][w][e]

