[msg MSG_000 [ ]]
[s]> Port Island Station, florist...[n][w][e]
[s]> The store is filled with[n]beautiful flowers.[n][w][e]

[msg MSG_001 [Yukari]]
[s][bup 2 1 65535 2]Hmm... Lilies are too overpowering,[n]and roses aren't really my thing...[n][w][e]
[s]Maybe gerberas...?[n][w][e]

[msg MSG_002 [ ]]
[s]> Yukari is trying to decide[n]which flowers to buy.[n][w][e]

[msg MSG_003 [Yukari]]
[s][bup 2 2 65535 2]Oh, sorry.[n][w][e]
[s]I'm looking at flowers for my room.[n][w][e]

[msg MSG_004 [Yukari]]
[s][bup 2 2 65535 2]Hey, I think I'm gonna go with[n]gerberas, but which color should[n]I get?[n][w][e]

[sel SEL005 top]
[s]"Pink's cute."+3[e]
[s]"White."[e]
[s]"Bright red."[e]
[s]"What's a gerbera?"[e]

[msg MSG_006 [Yukari]]
[s][bup 2 2 65535 2][f 6 1 1 0 2 7]You think so too? I love pink.[n][w][e]
[s]I guess we have the same taste,[n]huh...[n][w][e]
[s][f 5 13 0 15 0][f 1 5] [n]> Yukari seems pleased.[n][w][e]

[msg MSG_007 [Yukari]]
[s][bup 2 2 65535 2]Then, it's decided: I'll get 'em.[n][w][e]

[msg MSG_008 [Yukari]]
[s][bup 2 1 65535 2]White? Isn't that kinda boring?[n][w][e]
[s][f 5 13 0 0 0][f 1 5] [n]> Yukari seems disappointed.[n][w][e]

[msg MSG_009 [Yukari]]
[s][bup 2 4 65535 2]Bright red? Won't that stand out[n]too much?[n][w][e]
[s][f 5 13 0 0 0][f 1 5] [n]> Yukari seems disappointed.[n][w][e]

[msg MSG_010 [Yukari]]
[s][bup 2 5 65535 2]Are you serious?[n][w][e]
[s][bup 2 4 65535 2][f 6 1 1 0 2 9]C'mon, you should know this kinda[n]stuff.[n][w][e]
[s][f 5 13 0 0 0][f 1 5] [n]> Yukari seems disappointed.[n][w][e]

[msg MSG_011 [Yukari]]
[s][bup 2 1 65535 2][n][w][e]

[msg MSG_012 [Yukari]]
[s][bup 2 1 65535 2]Hmm... But, just gerberas might be[n]a little plain...[n][w][e]

[msg MSG_013 [Yukari]]
[s][bup 2 1 65535 2]What other flowers do you think[n]would look nice?[n][w][e]

[msg MSG_014 [Yukari]]
[s][bup 2 2 65535 2]...Oh, you've never seen my room,[n]have you? Well, what good are you?[n][w][e]

[sel SEL015 top]
[s]"That's messed up." +3[e]
[s]"Then, invite me in."[e]

[msg MSG_016 [Yukari]]
[s][bup 2 2 65535 2][f 6 1 1 0 2 11]*giggle* But it's the truth.[n][w][e]
[s][f 5 13 0 5 0][f 1 5] [n]> Yukari seems to be having fun.[n][w][e]

[msg MSG_017 [Yukari]]
[s][bup 2 2 65535 2]You wish![n][w][e]
[s][f 6 1 1 0 2 11]*giggle* You're as bad as Junpei.[n][w][e]
[s][f 1 5] [n][f 5 13 0 0 0]> Yukari has rejected you.[n][w][e]

[msg MSG_018 [Yukari]]
[s][bup 2 1 65535 2]Actually, any flowers would be[n]fine if they were from you,[n][f 4 2]-kun.[n][w][e]

[msg MSG_019 [Yukari]]
[s][bup 2 2 65535 2][f 6 1 1 0 2 11]...Psych! *giggle*[n][w][e]

[msg MSG_020 [ ]]
[s]> Yukari seems to be full of laughter[n]today.[n][w][e]
[s]> The bond between you is growing...[n][w][e]

[msg MSG_021 [ ]]
[s]> Yukari seems quite relaxed talking[n]to you.[n][w][e]
[s]> However, you're still just friends.[n][w][e]

[msg MSG_022 [Yukari]]
[s][bup 2 5 65535 2]Wow, look at the time.[n][w][e]
[s][bup 2 1 65535 2]...Hmmm, what should I get...?[n]I'm actually pretty indecisive, y'know.[n][w][e]
[s]Hmmm... Ranunculuses aren't bad either...[n][w][e]

[msg MSG_023 [ ]]
[s]> After hanging out with Yukari, you[n]decided to return to the dorm...[n][w][e]

[msg MSG_024 [ ]]
[s]Your Social Links will grow stronger[n]as you spend time with your friends.[n][w][e]
[s]Depending on your rank, you will[n]receive bonus EXP when you fuse[n]Personas.[n][w][e]
[s]You may discover new Social Links[n]while strengthening your existing[n]ones.[n][w][e]
[s]Establish as many Social Links as[n]you can, and level them up to become[n]powerful![n][w][e]

