[msg MSG_14]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_15 [Kenji]]
[s][bup 22 161 65535 0]I acted like an idiot...[n][w][e]

[msg MSG_16]
[s]> Kenji seems to be regretting[n]what he did in the past...[n][w][e]

[msg MSG_17 [Kenji]]
[s][bup 22 161 65535 0]A-About that...[n][w][e]

[msg MSG_18 [ ]]
[s]> Kenji seems nervous...[n][w][e]

[msg MSG_19 [Kenji]]
[s][bup 22 163 65535 0]Can you just forget about it?[n][w][e]

[sel SEL020 top]
[s]"Sure."[e]
[s]"No can do."[e]
[s]"Forget about what?"[e]

[msg MSG_21 [Kenji]]
[s][bup 22 162 65535 0]Thanks, man! You're so understanding![n][w][e]
[s][bup 22 163 65535 0]Thinking about how I acted makes[n]me want to scream, dude.[n][w][e]
[s]...I'm not totally over it yet,[n]but... I'm trying, dude![n][w][e]

[msg MSG_22 [ ]]
[s][f 5 13 0 30 22]> Kenji seems relieved...[n][w][e]
[s]> You became a lot closer to him[n]today...[n][w][e]

[msg MSG_23 [Kenji]]
[s][bup 22 163 65535 0]Ugh...[n][w][e]
[s]I-I'm so embarrassed...[n][w][e]
[s]...Not cool, huh, dude...?[n][w][e]

[msg MSG_24 [ ]]
[s]> Kenji is forcing a smile...[n][w][e]
[s]> Your friendship seems to be stuck[n]in a rut...[n][w][e]

[msg MSG_25 [Kenji]]
[s][bup 22 162 65535 0]Oh, that's okay! It's nothing,[n]really... If you don't remember,[n]don't worry about it![n][w][e]
[s]This conversation ends here![n][w][e]

[msg MSG_26 [ ]]
[s][f 5 13 0 15 22]> Kenji seems relieved...[n][w][e]
[s]> You learned something new about[n]Kenji today...[n][w][e]

[msg MSG_27 [ ]]
[s]> It's getting dark out...[n][w][e]
[s]> You decided to go back to the dorm.[n][w][e]

[msg MSG_84]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_85 [Yukari]]
[s][bup 2 2 65535 0]Whew, thanks for lunch.[n][w][e]

[msg MSG_88]
[s]> Yukari seems to be enjoying[n]herself...[n][w][e]

[msg MSG_89 [Yukari]]
[s][bup 2 4 65535 0]Oh...[n][w][e]
[s]Um...[n][w][e]

[msg MSG_90 [ ]]
[s]> Yukari seems nervous...[n][w][e]

[msg MSG_91 [Yukari]]
[s][bup 2 4 65535 0]I...[n][w][e]
[s]...eat more than a normal girl, huh?[n][w][e]

[sel SEL092 top]
[s]"Yeah, even more than me!"[e]
[s]"Do you want mine, too?"[e]
[s]"It's a healthy appetite."[e]

[msg MSG_95 [Yukari]]
[s][bup 2 4 65535 0]S-Sorry, I can't help it.[n]I get hungry after practice![n][w][e]
[s]......[n][w][e]
[s]...I bet if I gain weight,[n]you won't like me anymore...[n][w][e]
[s]Um, I'm not hungry anymore. Thanks.[n][w][e]

[msg MSG_96 [ ]]
[s]> Yukari seems anxious...[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_97 [Yukari]]
[s][bup 2 4 65535 0]Well, to be honest, I do, but...[n][w][e]
[s]*sigh* ...I wish I didn't have[n]to worry about where the extra[n]calories are gonna go.[n][w][e]
[s][bup 2 2 65535 0]I guess there's no use fighting it;[n]I'll eat some of yours. Thanks.[n][w][e]

[msg MSG_98 [ ]]
[s][f 5 13 0 15 2]> Yukari seems happy.[n][w][e]
[s]> Today, you learned something new[n]about her...[n][w][e]

[msg MSG_93 [Yukari]]
[s][bup 2 2 65535 0]R-Really?[n][w][e]
[s][bup 2 4 65535 0]...Hey, what's with that smirk?[n][w][e]
[s][bup 2 2 65535 0]"A healthy appetite," huh...[n]*giggle*[n][w][e]

[msg MSG_94 [ ]]
[s][f 5 13 0 30 2]> Yukari seems happy.[n][w][e]
[s]> Today, you two became a lot[n]closer.[n][w][e]

[msg MSG_99 [ ]]
[s]> It's getting dark out...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_100]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_101 [Fuuka]]
[s][bup 6 2 65535 0]This place is really nice.[n][w][e]
[s]The food is cheap and nutritious...[n][w][e]
[s]And the atmosphere is great.[n][w][e]
[s]I really like coming here![n][w][e]

[msg MSG_102]
[s]> Fuuka seems to be enjoying[n]herself...[n][w][e]

[msg MSG_103 [Fuuka]]
[s][bup 6 2 65535 0][f 4 2]-kun, there's something[n]I've been meaning to ask you...[n][w][e]

[msg MSG_104 [ ]]
[s]> Fuuka is looking at you with[n]interest.[n][w][e]

[msg MSG_105 [Fuuka]]
[s][bup 6 2 65535 0]Which do you like better,[n]Japanese food or American food?[n][w][e]

[sel SEL106 top]
[s]"Japanese food."[e]
[s]"American food."[e]
[s]"Food is food."[e]

[msg MSG_107 [Fuuka]]
[s][bup 6 2 65535 0]Oh, really?[n][w][e]
[s]I'm glad to hear that. I like[n]Japanese food better too.[n][w][e]
[s][bup 6 1 65535 0]Hmmm... I think I'll start with[n]white rice and miso soup...[n][w][e]
[s]I'm going to try to recreate[n]the food they make here...[n][w][e]
[s][bup 6 2 65535 0]...I can't wait![n][w][e]

[msg MSG_108 [ ]]
[s][f 5 13 0 30 6]> Fuuka seems excited.[n][w][e]
[s]> Today, you two became a lot[n]closer.[n][w][e]

[msg MSG_109 [Fuuka]]
[s][bup 6 1 65535 0]Oh, really?[n][w][e]
[s]Hm, there are so many different[n]types of American food...[n][w][e]
[s]And, I'll have to get used to[n]cooking with vegetable oil...[n][w][e]
[s]But, I can't wait to try![n][w][e]

[msg MSG_110 [ ]]
[s][f 5 13 0 15 6]> Fuuka seems excited.[n][w][e]
[s]> You learned something new about[n]her today...[n][w][e]

[msg MSG_111 [Fuuka]]
[s][bup 6 1 65535 0]Oh, really?[n][w][e]
[s]So, you don't have a favorite[n]type of food?[n][w][e]
[s][bup 6 4 65535 0]Hmmm... That's going to make things[n]difficult...[n][w][e]

[msg MSG_112 [ ]]
[s]> Fuuka seems a little disappointed.[n][w][e]
[s]> Your relationship with her seems[n]to be stuck in a rut...[n][w][e]

[msg MSG_113 [ ]]
[s]> It's getting dark out...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_114]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_115 [Mitsuru]]
[s][bup 4 7 65535 0]......[n][w][e]
[s]The food here is delicious.[n][w][e]

[msg MSG_116]
[s]> Mitsuru seems to be enjoying[n]herself.[n][w][e]

[msg MSG_117 [Mitsuru]]
[s][bup 4 7 65535 0]Um, I want to ask you something...[n][w][e]
[s]A-And, I'd like you to answer[n]honestly...[n][w][e]

[msg MSG_118 [ ]]
[s]> Mitsuru is acting unusually[n]demure...[n][w][e]

[msg MSG_119 [Mitsuru]]
[s][bup 4 7 65535 0][f 4 1]...[n][w][e]
[s]Are you interested in anyone...?[n][w][e]

[sel SEL120 top]
[s]"Yes, I am."[e]
[s]"No, I'm not."[e]
[s]"Yeah, you!"[e]

[msg MSG_121 [Mitsuru]]
[s][bup 4 2 65535 0]I see...[n][w][e]
[s]But, I...[n][w][e]
[s]O-Oh never mind... Please forget[n]I said anything.[n][w][e]

[msg MSG_122 [ ]]
[s]> Mitsuru seems a little sad...[n][w][e]
[s]> Your relationship with her seems[n]to be stuck in a rut...[n][w][e]

[msg MSG_123 [Mitsuru]]
[s][bup 4 2 65535 0]I see...[n][w][e]
[s]So, I have a chance...[n][w][e]
[s]O-Oh, um... please just forget[n]I said anything.[n][w][e]

[msg MSG_124 [ ]]
[s][f 5 13 0 15 4]> Mitsuru is talking to herself...[n][w][e]
[s]> You learned something new about[n]her today...[n][w][e]

[msg MSG_125 [Mitsuru]]
[s][bup 4 7 65535 0]......![n][w][e]
[s]A-Are you trying to kill me!?[n]You almost gave me a heart attack...[n][w][e]
[s]Y-You're just joking, right...?[n][w][e]

[msg MSG_126 [ ]]
[s][f 5 13 0 30 4]> Mitsuru seems confused.[n][w][e]
[s]> Today, you two became a lot[n]closer.[n][w][e]

[msg MSG_127 [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_142]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_143 [Yuko]]
[s][bup 31 162 65535 0]I'm sorry about pushing you into[n]being a coach.[n][w][e]

[msg MSG_144]
[s]> Yuko seems genuinely sorry.[n][w][e]

[msg MSG_145 [Yuko]]
[s][bup 31 162 65535 0]Today is my treat. Eat as much as[n]you want.[n][w][e]

[msg MSG_146 [ ]]
[s]> Yuko seems lost in thought.[n][w][e]

[msg MSG_147 [Yuko]]
[s][bup 31 161 65535 0]Ya know, I've been thinking...[n]I may have been a little hasty,[n]agreeing to coach those kids.[n][w][e]
[s]What do you think? Am I ready?[n][w][e]

[sel SEL148 top]
[s]"You're too hasty."[e]
[s]"You're too nice."[e]
[s]"You're very responsible."[e]

[msg MSG_149 [Yuko]]
[s][bup 31 164 65535 0]So, you think so too?[n][w][e]
[s]My friend said the same thing...[n][w][e]
[s]But, I can't break my promise to[n]those kids. I guess I better do[n]some reading...[n][w][e]

[msg MSG_150 [ ]]
[s]> Yuko seems depressed.[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_151 [Yuko]]
[s][bup 31 162 65535 0]Th-That's not true.[n][w][e]
[s]I'm just not very good at saying[n]"no" to people.[n][w][e]
[s]That's why everybody on the team[n]takes advantage of me.[n][w][e]

[msg MSG_152 [ ]]
[s][f 5 13 0 15 31]> Yuko is smiling.[n][w][e]
[s]> Today, you learned something new[n]about her...[n][w][e]

[msg MSG_153 [Yuko]]
[s][bup 31 162 65535 0]That makes me feel a lot better.[n][w][e]
[s]I'm gonna read up on racing and[n]help those kids win![n][w][e]

[msg MSG_154 [ ]]
[s][f 5 13 0 30 31]> Yuko seems happy.[n][w][e]
[s]> Today, you two became a lot[n]closer.[n][w][e]

[msg MSG_155 [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_170]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_171 [Kazushi]]
[s][bup 30 102 65535 0]Wouldn't it be funny if all the[n]problems with my knee turned out[n]to be just growing pains?[n][w][e]

[msg MSG_172]
[s]> Kazushi tried to make a joke.[n][w][e]

[msg MSG_173 [Kazushi]]
[s][bup 30 104 65535 0]But, I don't wanna get any more[n]muscular than this. It's not like[n]I'm trying out for pro wrestling.[n][w][e]

[msg MSG_174 [ ]]
[s]> Kazushi seems to be thinking.[n][w][e]

[msg MSG_175 [Kazushi]]
[s][bup 30 102 65535 0]Oh, you can have my rice if you[n]want...[n][w][e]
[s]I'm trying to cut down on carbs.[n][w][e]

[sel SEL176 top]
[s]"Want bread instead?"[e]
[s]"Are you on a diet?"[e]
[s]"Are you sick?"[e]

[msg MSG_177 [Kazushi]]
[s][bup 30 102 65535 0]Very funny.[n][w][e]
[s]Why don't we order some noodles[n]and potatoes too?[n][w][e]

[msg MSG_178 [ ]]
[s][f 5 13 0 15 30]> It seems like Kazushi is having[n]fun.[n][w][e]
[s]> Today, you learned something new[n]about him...[n][w][e]

[msg MSG_179 [Kazushi]]
[s][bup 30 102 65535 0]Yeah. These days, I'm getting[n]kinda fat, so I need to watch[n]what I eat.[n][w][e]
[s]It'll take everything I've got[n]for me to win at regionals...[n][w][e]

[msg MSG_180 [ ]]
[s][f 5 13 0 30 31]> Kazushi has opened up to you.[n][w][e]
[s]> Today, your friendship grew[n]stronger...[n][w][e]

[msg MSG_181 [Kazushi]]
[s][bup 30 103 65535 0]Dude, do you think I'm some kinda[n]wuss?[n][w][e]
[s]My body is in perfect condition,[n]except for my knee...[n][w][e]

[msg MSG_182 [ ]]
[s]> Kazushi seems annoyed.[n][w][e]
[s]> Your friendship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_183 [ ]]
[s]> It's getting dark out...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_184]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_185 [Kazushi]]
[s][bup 30 103 65535 0]I don't believe in taking days off[n]from practice. That's B.S.[n][w][e]
[s]That's why I can't tell anyone on[n]the team about my knee...[n][w][e]

[msg MSG_186]
[s]> Kazushi looks depressed...[n][w][e]

[msg MSG_187 [Kazushi]]
[s][bup 30 104 65535 0]I've been doing [f 5 3 0] since[n]I was in middle school, and now[n]they're telling me to stop?[n][w][e]

[msg MSG_188 [ ]]
[s]> Kazushi's face darkened.[n][w][e]

[msg MSG_189 [Kazushi]]
[s][bup 30 101 65535 0]Dude, if this keeps up, I'll[n]probably turn into one of those[n]freaks on the news...[n][w][e]
[s]...You know, with Apathy Syndrome?[n][w][e]

[sel SEL190 top]
[s]"I doubt it."[e]
[s]"You're worrying me."[e]
[s]"Hang in there."[e]

[msg MSG_191 [Kazushi]]
[s][bup 30 103 65535 0]Thanks for your "concern," man.[n][w][e]
[s]I'll have you know, I'm not as[n]tough as I look.[n][w][e]

[msg MSG_192 [ ]]
[s]> It seems Kazushi is in a bad[n]mood.[n][w][e]
[s]> Your friendship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_193 [Kazushi]]
[s][bup 30 102 65535 0]I know, but I can't stop[n]practicing. I have to hide it,[n]somehow...[n][w][e]
[s]But, I'm glad you're looking out[n]for me.[n][w][e]

[msg MSG_194 [ ]]
[s][f 5 13 0 30 30]> Kazushi seems happy.[n][w][e]
[s]> You understand him a little better[n]now...[n][w][e]

[msg MSG_195 [Kazushi]]
[s][bup 30 101 65535 0]Even if it's painful, I have to[n]try and hide it...[n][w][e]
[s]I can't imagine NOT being on the[n]team, so I have to suck it up.[n][w][e]

[msg MSG_196 [ ]]
[s][f 5 13 0 15 30]> Kazushi's expression looks[n]serious.[n][w][e]
[s]> Today, you learned something new[n]about him...[n][w][e]

[msg MSG_197 [ ]]
[s]> It's getting dark out...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_198]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_199 [Kazushi]]
[s][bup 30 104 65535 0]Dude, my knee just keeps getting[n]worse...[n][w][e]

[msg MSG_200]
[s]> Kazushi looks depressed...[n][w][e]

[msg MSG_201 [Kazushi]]
[s][bup 30 104 65535 0]Dude, the stairs were hell on my[n]knee...[n][w][e]

[msg MSG_202 [ ]]
[s]> Kazushi's face has darkened.[n][w][e]

[msg MSG_203 [Kazushi]]
[s][bup 30 104 65535 0]Man, I'm seriously confused.[n]I'm not sure why I'm putting[n]myself through this...[n][w][e]

[sel SEL204 top]
[s]"That's just who you are."[e]
[s]"For your nephew."[e]
[s]"You tell me."[e]

[msg MSG_205 [Kazushi]]
[s][bup 30 102 65535 0]That's true. I hate losing.[n]Could that be it...?[n][w][e]
[s]Sorry if I acted like a wimp...[n]That's not the real me. Thanks![n]I'm fine now![n][w][e]

[msg MSG_206 [ ]]
[s][f 5 13 0 30 30]> Kazushi seems appreciative of[n]your support.[n][w][e]
[s]> Your friendship is a lot stronger[n]now.[n][w][e]

[msg MSG_207 [Kazushi]]
[s][bup 30 101 65535 0]Y-Yeah! If I give up now, he might[n]not be able to walk for the rest of[n]his life...[n][w][e]
[s]His entire future depends on me...[n][w][e]

[msg MSG_208 [ ]]
[s][f 5 13 0 15 30]> Kazushi seems lost in thought.[n][w][e]
[s]> Today, you learned something new[n]about him...[n][w][e]

[msg MSG_209 [Kazushi]]
[s][bup 30 104 65535 0]Dude, don't gimme that...[n]I couldn't come up with the answer.[n]That's why I came to you...[n][w][e]
[s]We're friends, right?[n][w][e]

[msg MSG_210 [ ]]
[s]> Kazushi seems depressed.[n][w][e]
[s]> Your friendship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_211 [ ]]
[s]> It's getting dark out...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_326]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_327 [Bebe]]
[s][bup 34 162 65535 0]Oishi! Zis eez delicious![n]Zat tempura was so good![n][w][e]

[msg MSG_328]
[s]> Bebe seems to be enjoying[n]the meal.[n][w][e]

[msg MSG_329 [Bebe]]
[s][bup 34 161 65535 0]Hmm, I 'ave to do somezing about[n]zis problem...[n][w][e]

[msg MSG_330 [ ]]
[s]> Bebe seems to be thinking...[n][w][e]

[msg MSG_331 [Bebe]]
[s][bup 34 161 65535 0]I don't 'ave much time to spend[n]'ere.[n][w][e]
[s]I must finish ze kimono.[n][w][e]

[sel SEL332 top]
[s]"Go finish it."[e]
[s]"It can wait."[e]
[s]"Just relax."[e]

[msg MSG_334 [Bebe]]
[s][bup 34 163 65535 0]But, I don't 'ave a sewing machine[n]at 'ome![n][w][e]
[s]Besides, a warrior must eat before[n]going into battle![n][w][e]

[msg MSG_335 [ ]]
[s]> Bebe seems to disagree with you.[n][w][e]
[s]> Your friendship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_336 [Bebe]]
[s][bup 34 162 65535 0]I will continue ze fight anozer day![n]A warrior must eat before going into[n]battle![n][w][e]

[msg MSG_337 [ ]]
[s][f 5 13 0 15 34]> Bebe seems excited...[n][w][e]
[s]> You have learned something new[n]about him...[n][w][e]

[msg MSG_338 [Bebe]]
[s][bup 34 163 65535 0]Relax, you say!?[n][w][e]
[s][bup 34 162 65535 0]Zat eez true! Rushing will not 'elp![n][w][e]

[msg MSG_339 [ ]]
[s][f 5 13 0 30 34]> Bebe seems excited...[n][w][e]
[s]> Your friendship has grown[n]dramatically.[n][w][e]

[msg MSG_340 [ ]]
[s]> It's getting dark out...[n][w][e]
[s]> You decide to go back to[n]the dorm.[n][w][e]

[msg MSG_369]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_370 [Yuko]]
[s][bup 31 161 65535 0]...You can have mine if you're[n]still hungry.[n][w][e]

[msg MSG_371]
[s]> Yuko is not eating as much as[n]usual.[n][w][e]

[msg MSG_372 [Yuko]]
[s][bup 31 162 65535 0]D-Don't worry. I'm not sick or[n]anything...[n][w][e]

[msg MSG_373 [ ]]
[s]> Yuko's face has turned red.[n][w][e]

[msg MSG_374 [Yuko]]
[s][bup 31 161 65535 0][f 4 2], you have some sauce[n]on your mouth.[n][w][e]

[sel SEL375 top]
[s]"Thank you."[e]
[s]"Mind your own business."[e]
[s]"Will you wipe it off?"[e]

[msg MSG_376 [Yuko]]
[s][bup 31 162 65535 0]You're welcome.[n][w][e]
[s]...Aren't ya gonna wipe it off?[n]It's bugging me. [n][w][e]

[msg MSG_378 [ ]]
[s][f 5 13 0 15 31]> Yuko seems happy.[n][w][e]
[s]> Today, you learned something new[n]about her...[n][w][e]

[msg MSG_379 [Yuko]]
[s][bup 31 164 65535 0]I guess I should...[n][w][e]
[s]I'm not even your girlfriend...[n][w][e]

[msg MSG_380 [ ]]
[s]> Yuko seems sad.[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut...[n][w][e]

[msg MSG_381 [Yuko]]
[s][bup 31 167 65535 0]You're more spoiled than you look,[n][f 4 2].[n][w][e]
[s]Okay, I'll get it for you...[n][w][e]

[msg MSG_382 [ ]]
[s][f 5 13 0 30 31]> Yuko seems embarrassed.[n][w][e]
[s]> Today, you two became a lot[n]closer.[n][w][e]

[msg MSG_383 [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg SYS_000 [ ]]
[s]> You recall that you have something[n]you can give as a present...[n][w][e]

[sel SYS_SEL_000 top]
[s]Give a present[e]
[s]Don't give a present[e]

[msg SYS_001 [ ]]
[s]> What kind of present should you give?[n][w][e]

[sel SYS_SEL_001 top]
[s]Flowers[e]
[s]Fashion[e]
[s]Antique[e]
[s]Other[e]
[s]Never mind[e]

[sel SYS_SEL_001F top]
[s]Handmade sweets[e]
[s]Handmade goods[e]
[s]Antique[e]
[s]Other[e]
[s]Never mind[e]

[msg SYS_002 [ ]]
[s]> You don't have that type of[n]item.[n][w][e]

[msg SYS_003 [ ]]
[s]> Which item will you give?[n][w][e]

[sel SYS_SEL_CATE_01 top]
[s]Rose Bouquet[e]
[s]Red Pine Bonsai[e]
[s]Mini Cactus[e]
[s]Glass Vase[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_02 top]
[s]Perfume[e]
[s]Brand Wallet[e]
[s]Brand Watch[e]
[s]Brand Purse[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_03 top]
[s]Teddy Bear[e]
[s]Japanese Doll[e]
[s]Kaleidoscope[e]
[s]Goggle-eyed Idol[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_04 top]
[s]Jack Frost Doll[e]
[s]Book Cover[e]
[s]Lucky Charm[e]
[s]Ganesha Bank[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_01F top]
[s]Chocolate Truffle[e]
[s]Sweet Fries[e]
[s]Sugar Cookie[e]
[s]Banana Cupcake[e]
[s]Never mind[e]

[sel SYS_SEL_CATE_02F top]
[s]Japanese Strap[e]
[s]Knit Rabbit[e]
[s]Felt Bag[e]
[s]Hand-knitted Scarf[e]
[s]Never mind[e]

[msg MSG_PRE_60 [Yukari]]
[s][bup 2 1 65535 0]...This is for me?[n][w][e]
[s]Um... Thanks...[n][w][e]
[s][f 1 5] [n]> Yukari doesn't seem to like[n]your present very much.[n][w][e]

[msg MSG_PRE_61 [Yukari]]
[s][bup 2 2 65535 0]I can have this!?[n][w][e]
[s]Wow, thanks![n][w][e]
[s]That's really nice of you![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 2]> Yukari seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_62 [Yukari]]
[s][bup 2 1 65535 0]You... took the time to pick this out[n]for me?[n][w][e]
[s]Thanks, I really wanted something like[n]this! That's so nice of you![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 2]> Yukari seems to absolutely love[n]the gift.[n][w][e]

[msg MSG_PRE_63 [Yukari]]
[s][bup 2 1 65535 0]Don't tell me... You made this!?[n][w][e]
[s][bup 2 2 65535 0]Hey, can I try it?[n][w][e]
[s]......[n][w][e]
[s]Yep, this is delicious![n][w][e]
[s]Thank you so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 2]> Yukari seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_64 [Yukari]]
[s][bup 2 1 65535 0]Don't tell me... You made this!?[n][w][e]
[s]Wow, this is amazing...[n][w][e]
[s][bup 2 2 65535 0]Hey, can I try it?[n][w][e]
[s]......[n][w][e]
[s]Yep, this is delicious! Amazing...[n]You're like a professional chef![n][w][e]
[s]Aww, it's already all gone...[n]Can you make me some more?[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 2]> Yukari seems to absolutely love[n]the gift.[n][w][e]

[msg MSG_PRE_65 [Yukari]]
[s][bup 2 1 65535 0]Don't tell me... You made this!?[n][w][e]
[s][bup 2 2 65535 0]Wow, it's so cute. Thank you so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 2]> Yukari seems to absolutely love[n]the gift.[n][w][e]

[msg MSG_PRE_70 [Fuuka]]
[s][bup 6 1 65535 0]Th-Thank you...[n][w][e]
[s]But you really shouldn't have...[n][w][e]
[s][f 1 5] [n]> Fuuka doesn't seem to like[n]your present very much.[n][w][e]

[msg MSG_PRE_71 [Fuuka]]
[s][bup 6 2 65535 0]...This is for me?[n][w][e]
[s]You seem to know my tastes.[n][w][e]
[s]...Thank you very much.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 6]> Fuuka seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_72 [Fuuka]]
[s][bup 6 5 65535 0]Um...[n][w][e]
[s]Um, this is for me?[n]Really...?[n][w][e]
[s]......[n][w][e]
[s]Oh, sorry...[n][w][e]
[s][bup 6 7 65535 0]I'm just surprised. I mean,[n]I've never received something[n]so wonderful before...[n][w][e]
[s]Thank you very much.[n]I'll cherish it forever![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 6]> Fuuka seems to absolutely love[n]your present.[n][w][e]

[msg MSG_PRE_73 [Fuuka]]
[s][bup 6 5 65535 0]Oh, this... Is this what you made in the[n]cooking club? I can have this?[n][w][e]
[s][bup 6 2 65535 0]......[n][w][e]
[s]Mmhm, it's delicious. I hope I can[n]make something this good someday...[n][w][e]
[s]...Thanks. I'll keep trying my best too.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 6]> Fuuka seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_74 [Fuuka]]
[s][bup 6 5 65535 0]Oh, this... Is this what you made in the[n]cooking club? I can have this?[n][w][e]
[s][bup 6 2 65535 0]......[n][w][e]
[s]Mmhm, it's delicious. I hope I can[n]make something this good someday...[n][w][e]
[s]...Thanks. I'll keep trying my best too.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 6]> Fuuka seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_75 [Fuuka]]
[s][bup 6 5 65535 0]Huh? This is hand-made, right?[n]Are you sure I can have this?[n][w][e]
[s][bup 6 2 65535 0]It's so cute...[n][w][e]
[s]I really admire the way you can do all[n]this, [f 4 2]-chan.[n][w][e]
[s]Thank you very much. I'll cherish[n]it forever![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 6]> Fuuka seems to absolutely love[n]your present.[n][w][e]

[msg MSG_PRE_80 [Mitsuru]]
[s][bup 4 1 65535 0]Is this for me?[n][w][e]
[s]...Well, I was taught that it's[n]bad manners not to accept a gift[n]from someone.[n][w][e]
[s]Thanks, I appreciate it.[n][w][e]
[s][f 1 5] [n]> Mitsuru doesn't seem to like[n]your present very much.[n][w][e]

[msg MSG_PRE_81 [Mitsuru]]
[s][bup 4 2 65535 0]Hm? For me?[n][w][e]
[s]Ah... an excellent choice.[n][w][e]
[s]But, more importantly,[n]I appreciate your thoughtfulness.[n]Thank you, [f 4 1].[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 4]> Mitsuru seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_82 [Mitsuru]]
[s][bup 4 1 65535 0]This is for me?[n][w][e]
[s]......[n][w][e]
[s][bup 4 7 65535 0]...I'm impressed with your choice.[n][w][e]
[s]I had no idea you knew me so well.[n][w][e]
[s]Thank you... It's been a long time[n]since I've received a present that[n]has resonated with me like this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 4]> Mitsuru seems to be delighted[n]with the gift.[n][w][e]

[msg MSG_PRE_83 [Mitsuru]]
[s][bup 4 1 65535 0]Did you make this...?[n][w][e]
[s]......[n][w][e]
[s][bup 4 2 65535 0]This is delicious.[n][w][e]
[s]Its flavor is simple, yet warm...[n]Just like its creator.[n][w][e]
[s]Thank you for giving this to me.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 4]> Mitsuru seems to really like[n]your present.[n][w][e]

[msg MSG_PRE_84 [Mitsuru]]
[s][bup 4 1 65535 0]Did you make this...?[n][w][e]
[s]......[n][w][e]
[s][bup 4 2 65535 0]This is delicious.[n][w][e]
[s]Your skills are a match for a patissier[n]at a fine hotel.[n][w][e]
[s]You are indeed skilled... Thank you[n]for giving this to me.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 4]> Mitsuru seems to be delighted[n]with the gift.[n][w][e]

[msg MSG_PRE_85 [Mitsuru]]
[s][bup 4 1 65535 0]This... Did you make it?[n][w][e]
[s][bup 4 2 65535 0]You are strong, but with a feminine[n]side as well... Quite an enigma.[n][w][e]
[s]D-Does... this look good on me?[n][w][e]
[s]...Thank you. I'll treasure this for[n]a long time to come.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 4]> Mitsuru seems to be delighted[n]with the gift.[n][w][e]

[msg MSG_PRE_100 [Yuko]]
[s][bup 31 161 65535 0]Hmmm? What's this?[n][w][e]
[s]...Uhhh.[n][w][e]
[s]Thanks, I guess.[n][w][e]
[s][f 1 5] [n]> It doesn't seem like the right[n]present for Yuko.[n][w][e]

[msg MSG_PRE_101 [Yuko]]
[s][bup 31 162 65535 0]Hm, this is for me?[n][w][e]
[s]Wow, it's so nice! Thanks![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 31]> Yuko seems to like your present.[n][w][e]

[msg MSG_PRE_102 [Yuko]]
[s][bup 31 162 65535 0]Hmmm? What's this?[n][w][e]
[s]...Is this really for me!?[n][w][e]
[s][bup 31 167 65535 0]Are you sure...?[n][w][e]
[s]...Thank you SO much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 31]> Yuko seems delighted with[n]the gift.[n][w][e]

[msg MSG_PRE_110 [Chihiro]]
[s][bup 25 161 65535 0]Um... Th-This is for me...?[n][w][e]
[s]...Oh, um... I... I...[n][w][e]
[s]Um, th-thank you...[n][w][e]
[s]It's the thought that counts.[n][w][e]
[s][f 1 5] [n]> Chihiro doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_111 [Chihiro]]
[s][bup 25 162 65535 0]Huh? For me?[n][w][e]
[s]W-Wow...[n][w][e]
[s]Um... Can I really have this?[n][w][e]
[s]Thank you![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 25]> Chihiro seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_112 [Chihiro]]
[s][bup 25 161 65535 0]Huh? For me?[n][w][e]
[s][bup 25 167 65535 0]W-Wow... Really?[n][w][e]
[s]What a lovely gift...[n][w][e]
[s]Thank you so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 25]> Chihiro seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_120 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s][bup 5 1 65535 0]Uhh... Thanks![n][w][e]
[s][f 1 5] [n]> Junpei doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_121 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Whoa, I can have this!?[n]Awesome, thanks![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 5]> Junpei seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_122 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Wait, WHOA, seriously!?[n]This is really awesome![n][w][e]
[s]Oh man, thanks so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 5]> Junpei seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_123 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Wait, WHOA, seriously!?[n]This is handmade, isn't it!?[n][w][e]
[s]Thanks for the food![n][w][e]
[s]*munch munch*[n][w][e]
[s]Ooh, this is pretty good! Man, nothing[n]is better than a snack a girl made[n]just for me![n][w][e]
[s]Thanks![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 5]> Junpei seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_124 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Wait, WHOA, seriously!?[n]This is handmade, isn't it?[n]It looks so good![n][w][e]
[s]Thanks for the food![n][w][e]
[s]*munch munch*[n][w][e]
[s]Oh man, this is delicious![n]It's like a party for my tongue![n][w][e]
[s]Thanks! I wouldn't mind if you made[n]me something again sometime![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 5]> Junpei seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_125 [Junpei]]
[s][bup 5 2 65535 0]What's this? Is it for me?[n][w][e]
[s]Wait, WHOA, seriously!?[n]This is handmade, isn't it?[n]Seriously? I can have it?[n][w][e]
[s]I'm so stoked! Thanks so much![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 5]> Junpei seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_130 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s]Oh... Um, thanks.[n][w][e]
[s][f 1 5] [n]> Saori doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_131 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow, this is so fantastic...[n]Are you sure I can have this...?[n][w][e]
[s]Thank you so much. I appreciate this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 41]> Saori seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_132 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow...[n][w][e]
[s]Oh, I'm sorry. I was just so surprised[n]that I didn't know what to say.[n][w][e]
[s]Are you sure I can have something[n]so nice...?[n][w][e]
[s]I don't know how to thank you...[n][w][e]
[s]Thank you so much. I'll make sure to[n]cherish this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 41]> Saori seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_133 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow, sweets! It looks so delicious...[n]You made this, right?[n][w][e]
[s]I'll take it home and savor it.[n][w][e]
[s]Haha, I'm looking forward to that[n]later... Thanks.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 41]> Saori seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_134 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow, sweets! It looks so delicious...[n]You made this, right?[n][w][e]
[s]I love sweets like these! I'll take[n]it home and savor it.[n][w][e]
[s]Haha, I'm looking forward to that[n]later... Thanks.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 41]> Saori seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_135 [Saori]]
[s][bup 41 161 65535 0]Hm? For me?[n][w][e]
[s]Can I open it?[n][w][e]
[s][bup 41 162 65535 0]Wow... This is fantastic![n]You made this, no?[n][w][e]
[s]It's so cute... I adore this kind[n]of thing.[n][w][e]
[s]Thank you... I'll cherish it forever.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 41]> Saori seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_140 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s]Oh... Well, I accept.[n]Thanks.[n][w][e]
[s][f 1 5] [n]> Rio doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_141 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s][bup 29 162 0 0]Wow, this is nice.[n]Thank you very much![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 29]> Rio seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_142 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s]Let's see here...[n][w][e]
[s][bup 29 162 0 0]Whoa, what is this!? WOW![n][w][e]
[s]It's so cute! I can really have this?[n][w][e]
[s]Thanks! I love it![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 29]> Rio seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_143 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s][bup 29 162 0 0]Wow, this looks delicious![n]Is it handmade? Can I eat it?[n][w][e]
[s]Thanks for the food...[n][w][e]
[s]...Yep, it's tasty! That's really cool[n]that you can make sweets.[n][w][e]
[s]Thanks! I'm looking forward to tasting[n]some more someday.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 29]> Rio seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_144 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s]Let's see...[n][w][e]
[s][bup 29 162 0 0]Wow, what is this!? Is it handmade?[n]It looks so good![n][w][e]
[s]Thanks for the food![n][w][e]
[s]...Yep, it's super delicious![n]You're like a pro![n][w][e]
[s]Thanks! I'm looking forward to tasting[n]some more someday.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 29]> Rio seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_145 [Rio]]
[s][bup 29 161 0 0]Huh? For me?[n][w][e]
[s]Let's see...[n][w][e]
[s][bup 29 162 0 0]Wow, this is so cute! You made this,[n]right? That's amazing![n][w][e]
[s]Are you sure I can have something[n]like this? Isn't it a little too[n]cute for me?[n][w][e]
[s]Thanks! I love it![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 29]> Rio seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_150 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s]......[n][w][e]
[s]Th-Thank you very much.[n][w][e]
[s][f 1 5] [n]> Ken doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_151 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][bup 8 2 65535 0][f 4 2]-san... Are you sure...?[n][w][e]
[s]Thank you very much. I'll definitely[n]treasure this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 8]> Ken seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_152 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][f 4 2]-san... You're treating me[n]like a kid, aren't you?[n][w][e]
[s]......[n][w][e]
[s]Well, I'll still accept it.[n][w][e]
[s]...Thank you very much,[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 8]> Ken seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_153 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][bup 8 2 65535 0][f 4 2]-san... You cooked this,[n]didn't you?[n][w][e]
[s]Wow, thanks... Ooh, this is great![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 8]> Ken seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_154 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][bup 8 2 65535 0][f 4 2]-san... You cooked this,[n]didn't you?[n][w][e]
[s]...Is it okay if I eat this in my room?[n]It's too nice to eat right now...[n][w][e]
[s]I'm happy that you made something so[n]nice for someone like me...[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 8]> Ken seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_155 [Ken]]
[s][bup 8 1 65535 0]Huh? This is for me?[n][w][e]
[s][bup 8 2 65535 0][f 4 2]-san... You made this,[n]right?[n][w][e]
[s]It's amazing... Thank you for making[n]something so special for me.[n]It really means a lot.[n][w][e]
[s]I'll cherish it forever...[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 8]> Ken seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_160 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s]Dis... was sold at zhe school.[n]Arigato.[n][w][e]
[s][f 1 5] [n]> Bebe doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_161 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]Wow, dis iz amazing![n]Sugoi, [f 4 2]-sama![n][w][e]
[s]Merci, arigato, thank you![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 34]> Bebe seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_162 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]Hontou!? Wow, dis iz amazing![n][w][e]
[s]Merci, arigato, thank you![n][w][e]
[s]I love Japan![n]I love [f 4 2]-sama too![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 34]> Bebe seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_163 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]Wow, dis iz amazing![n][f 4 2]-sama, you made, no?[n][w][e]
[s]...C'est bon! Oishii![n]Japanese sweets are zhe best![n][w][e]
[s][f 1 5] [n][f 5 13 0 10 34]> Bebe seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_164 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]Wow, dis iz amazing![n][f 4 2]-sama, you made, no?[n][w][e]
[s]...Excellent! Oishii![n]Diz iz my 'omeland's flavor![n][w][e]
[s][f 4 2]-sama's sweets are amazing![n][f 4 2]-sama is amazing too![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 34]> Bebe seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_165 [Bebe]]
[s][bup 34 161 65535 0]Nani? A present for me?[n][w][e]
[s][bup 34 162 65535 0]You made dis at zhe club![n]You give to Bebe?[n][w][e]
[s][f 4 2]-sama... You are too[n]kind... Arigatou, daisuki![n][w][e]
[s][f 1 5] [n][f 5 13 0 50 34]> Bebe seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_170 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s]......[n][w][e]
[s]This is for me? Well... Thanks.[n][w][e]
[s][f 1 5] [n]> Akihiko doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_171 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s][bup 7 2 65535 0]Whoa, this is different. Thanks.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 7]> Akihiko seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_172 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s][bup 7 2 65535 0]...Are you sure I can have this?[n][w][e]
[s]Thanks... It's really great.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 7]> Akihiko seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_173 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s]......[n][w][e]
[s]It looks sweet...[n][w][e]
[s][bup 7 2 65535 0]Hey, I'll eat it. I mean, you made[n]it for me, right?[n][w][e]
[s]...Mmhm, that's good. Thanks for[n]taking the time to make this.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 7]> Akihiko seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_174 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s][bup 7 2 65535 0]...How'd you know I liked this?[n][w][e]
[s]Mmhm, delicious. Man, that flavor...[n][w][e]
[s]I used to love these when I was a kid.[n][w][e]
[s]Thanks...[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 7]> Akihiko seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_175 [Akihiko]]
[s][bup 7 1 65535 0]...For me? What is it...?[n][w][e]
[s][bup 7 2 65535 0]This is... for me? This is a bit...[n]cute for me, don't you think?[n][w][e]
[s]Haha, well, you made it, so I'll[n]take it.[n][w][e]
[s]...There's nothing wrong with a gift[n]like this, after all.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 7]> Akihiko seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_180 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]...What is this?[n][w][e]
[s]Uhh, well... Thanks, I guess.[n][w][e]
[s][f 1 5] [n]> Shinjiro doesn't seem to like[n]the present very much.[n][w][e]

[msg MSG_PRE_181 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]......[n][w][e]
[s][bup 9 162 0 0]Why'd you give this to me?[n][w][e]
[s]......[n][w][e]
[s]I-I ain't giving it back.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 9]> Shinjiro seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_182 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]......[n][w][e]
[s][bup 9 162 0 0]Why'd you give this to me?[n][w][e]
[s]......[n][w][e]
[s]I-I ain't giving it back.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 9]> Shinjiro seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_183 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]......[n][w][e]
[s][bup 9 162 0 0]Why'd you give this to me?[n][w][e]
[s]......[n][w][e]
[s]I-I ain't giving it back.[n][w][e]
[s][f 1 5] [n][f 5 13 0 10 9]> Shinjiro seems to really like[n]the present.[n][w][e]

[msg MSG_PRE_184 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]...You sure?[n]You made this, right?[n][w][e]
[s]......[n][w][e]
[s][bup 9 162 0 0]...It's delicious.[n][w][e]
[s]I can tell you made it just by tasting[n]it. You're pretty good at this...[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 9]> Shinjiro seems to really love[n]the present.[n][w][e]

[msg MSG_PRE_185 [Shinjiro]]
[s][bup 9 161 0 0]What? That's for me?[n][w][e]
[s]......[n][w][e]
[s]You sure? You must have put a lot of[n]time into this, right?[n][w][e]
[s]I got no right to accept something[n]like this...[n][w][e]
[s]......[n][w][e]
[s]...Thanks. I mean that.[n][w][e]
[s][f 1 5] [n][f 5 13 0 50 9]> Shinjiro seems to really love[n]the present.[n][w][e]

[msg MSG_500F]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_501F [Junpei]]
[s][bup 5 2 65535 0]*sigh* That was great.[n]I can't eat anymore.[n][w][e]

[msg MSG_502F]
[s]> Junpei seems satisfied...[n][w][e]

[msg MSG_503F [Junpei]]
[s][bup 5 5 65535 0]But man, you ate a lot too. You ordered[n]the same stuff as me, right?[n][w][e]
[s]How in the world did all that fit[n]inside your thin body...?[n][w][e]

[msg MSG_504F [ ]]
[s]> Junpei is looking at you, impressed.[n][w][e]

[msg MSG_505F [Junpei]]
[s][bup 5 2 65535 0]Remember how I told you the other day[n]that there are guys that're interested[n]in you?[n][w][e]
[s]I bet they'd be shocked if they saw[n]how much you can eat.[n][w][e]

[sel SEL_506F top]
[s]"Meh, like I care." +2[e]
[s]"Maybe I should eat less..."[e]
[s]"You got a problem with that?" +3[e]

[msg MSG_507F [Junpei]]
[s][bup 5 2 65535 0]You got a point. Worrying about stuff[n]like that'll just ruin the good food[n]you're eating.[n][w][e]
[s]Also, you seem so happy when you're[n]eating. It makes me feel good watching[n]you.[n][w][e]

[msg MSG_508F [ ]]
[s][f 5 13 0 30 5]> Junpei is laughing...[n][w][e]
[s]> Your friendship is a lot stronger[n]now.[n][w][e]

[msg MSG_509F [Junpei]]
[s][bup 5 5 65535 0]Oh, no no! I didn't mean it in that[n]way![n][w][e]
[s]I mean, who cares if you gain weight?[n]Don't mind what other people say and[n]eat up.[n][w][e]
[s]...Then again, saying stuff like that[n]might make you worry even more, huh...?[n]Haha...[n][w][e]

[msg MSG_510F [ ]]
[s]> Junpei is a little troubled...[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_511F [Junpei]]
[s][bup 5 5 65535 0]None whatsoever! I've got no problems[n]with your appetite![n][w][e]
[s][bup 5 2 65535 0]I mean, you're not gonna last if you[n]don't eat well. Don't worry about[n]what other people say and keep eating![n][w][e]
[s]Why don't we buy some takoyaki on the[n]way back too?[n][w][e]

[msg MSG_512F [ ]]
[s][f 5 13 0 15 0]> Junpei seems to be having fun...[n][w][e]
[s]> You learned something new about[n]Junpei today...[n][w][e]

[msg MSG_513F [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_600F]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_601F [Rio]]
[s][bup 29 161 0 0]...Oh, sorry.[n]Are you done eating already?[n][w][e]
[s]You can have my fried shrimp if you[n]want...[n][w][e]

[msg MSG_602F]
[s]> Rio hasn't eaten much of her assorted[n]fried dish...[n][w][e]
[s]> The fried shrimp and fried oyster are[n]completely untouched...[n][w][e]

[msg MSG_603F [Rio]]
[s][bup 29 161 0 0]It just suddenly tasted really oily to[n]me...[n][w][e]
[s]I guess I'm a just little tired of[n]thinking about different things.[n][w][e]

[msg MSG_604F [ ]]
[s]> Rio doesn't seem that well...[n][w][e]

[msg MSG_605F [Rio]]
[s][bup 29 162 0 0]Sorry... I'm the one that invited[n]you here, too...[n][w][e]

[sel SEL_606F top]
[s]"Don't worry."[e]
[s]"You gotta eat, though!"[e]
[s]"Can I have the fried oyster?"[e]

[msg MSG_607F [Rio]]
[s][bup 29 162 0 0]...Thanks.[n][w][e]
[s]I feel like I can share some of your[n]vigor when I'm with you...[n][w][e]

[msg MSG_608F [ ]]
[s][f 5 13 0 15 0]> Rio is laughing...[n][w][e]
[s]> You learned something new about[n]Rio today...[n][w][e]

[msg MSG_609F [Rio]]
[s][bup 29 162 0 0]Y-Yeah.[n][w][e]
[s]You're right, I gotta eat no matter how[n]I'm feeling. Loseing my muscles would[n]only make things worse.[n][w][e]

[msg MSG_610F [ ]]
[s][f 5 13 0 15 0]> Rio started trying her best to eat[n]more...[n][w][e]
[s]> You learned something new about[n]Rio today...[n][w][e]

[msg MSG_611F [Rio]]
[s][bup 29 162 0 0]Snrk...[n]Ahahahaha![n][w][e]
[s]You're the best. I feel stupid being[n]so depressed.[n][w][e]

[msg MSG_612F [ ]]
[s][f 5 13 0 30 0]> You seem to have cheered Rio up a[n]bit...[n][w][e]
[s]> Your friendship is a lot stronger[n]now.[n][w][e]

[msg MSG_613F [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_700F [ ]]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_701F [Ken]]
[s][bup 8 1 65535 0]*munch munch*[n][w][e]
[s]*gulp*[n][w][e]

[msg MSG_702F]
[s]> Ken is eating the Calcium Meal...[n][w][e]
[s]> But it seems that he doesn't have[n]an appetite today.[n][w][e]

[msg MSG_703F [Ken]]
[s][bup 8 1 65535 0]...Oh, I'm sorry.[n][w][e]
[s]I need to eat more if I want to grow[n]bigger...[n][w][e]

[msg MSG_704F [ ]]
[s]> Ken began eating again...[n][w][e]

[msg MSG_705F [Ken]]
[s][bup 8 1 65535 0]The omlette with fried rice you made[n]before... It was really good...[n][w][e]
[s]It was so good, I ate the whole thing[n]before I even knew it... I should've[n]eaten it more slowly...[n][w][e]

[sel SEL_706F top]
[s]"I'll make it for you again."[e]
[s]"It's bad to eat that quick."[e]
[s]"Did you savor it?"[e]

[msg MSG_707F [Ken]]
[s][bup 8 2 65535 0]Huh...?[n]R-Really?[n][w][e]
[s]Then, I'll make sure to be hungry that[n]day![n][w][e]

[msg MSG_708F [ ]]
[s][f 5 13 0 30 0]> Ken seems really happy...[n][w][e]
[s]> Today, you two became a lot[n]closer.[n][w][e]

[msg MSG_709F [Ken]]
[s][bup 8 4 65535 0]Yeah... You're right...[n][w][e]
[s]The people on TV said that too.[n]I guess I gotta be more careful...[n][w][e]

[msg MSG_710F [ ]]
[s]> Ken seems embarrassed...[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_711F [Ken]]
[s][bup 8 2 65535 0]Oh... Yes, of course![n][w][e]
[s]It was so good that I couldn't stop[n]moving my spoon![n][w][e]

[msg MSG_712F [ ]]
[s][f 5 13 0 15 0]> Ken is smiling...[n][w][e]
[s]> You learned something new about[n]Ken today...[n][w][e]

[msg MSG_713F [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_800F]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]
[s]> You decided to eat the Stamina Meal[n]that Akihiko recommended...[n][w][e]

[msg MSG_801F [Akihiko]]
[s][bup 7 2 65535 0]The Stamina Meal here's pretty good.[n][w][e]
[s]It's both filling and nutritionally[n]well-balanced.[n][w][e]
[s]Eat up before it gets cold.[n][w][e]

[msg MSG_802F]
[s]> You started eating the Stamina Meal[n]with Akihiko...[n][w][e]
[s]> ......[n][w][e]
[s]> This is a lot of food...[n][w][e]
[s]> ......[n][w][e]
[s]> You somehow eat all of it...[n][w][e]

[msg MSG_803F [Akihiko]]
[s][bup 7 2 65535 0]Wow! You completely finished this, just[n]like the ramen from the other day.[n][w][e]
[s]You've got a lot of guts.[n]I admire that.[n][w][e]

[msg MSG_804F [ ]]
[s]> Akihiko seems to be impressed with[n]you...[n][w][e]

[msg MSG_805F [Akihiko]]
[s][bup 7 1 65535 0]When I see the girls in my class, some[n]of them only eat vegetables for[n]lunch...[n][w][e]
[s]Their bodies are gonna wear out and[n]they'll eventually collapse if they[n]continue eating like that.[n][w][e]
[s]Make sure you eat well. One's meals[n]are very important for their body.[n][w][e]

[sel SEL_806F top]
[s]"I understand."[e]
[s]"I don't want to get fat..."[e]
[s]"You too, Senpai."[e]

[msg MSG_807F [Akihiko]]
[s][bup 7 2 65535 0]We'll be in real trouble if you[n]go faint during a battle.[n][w][e]
[s]...I'll take you to another restaurant[n]next time.[n][w][e]

[msg MSG_808F [ ]]
[s][f 5 13 0 30 0]> Akihiko is laughing...[n][w][e]
[s]> You became a lot closer to him[n]today...[n][w][e]

[msg MSG_809F [Akihiko]]
[s][bup 7 2 65535 0]There's no way you'll gain weight with[n]all the running around and fighting[n]you have to do.[n][w][e]
[s]Besides, why would you need to get any[n]thinner than you are now?[n][w][e]

[msg MSG_810F [ ]]
[s]> Akihiko seems to be appalled...[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_811F [Akihiko]]
[s][bup 7 2 65535 0]Me? I always eat well.[n][w][e]
[s]I don't even need to lose weight before[n]bouts. Plus, I've got no reason to[n]force myself into a lower weight class.[n][w][e]

[msg MSG_812F [ ]]
[s][f 5 13 0 15 0]> Akihiko is laughing...[n][w][e]
[s]> You learned something new about[n]Akihiko today...[n][w][e]

[msg MSG_813F [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_84_F]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_85_F [Yukari]]
[s][bup 2 1 65535 0]Ack, wait a sec![n]Don't order yet![n][w][e]
[s]I haven't had fried shrimp in a while,[n]but shabu-shabu sounds good too...[n][w][e]

[msg MSG_88_F]
[s]> Yukari is having trouble deciding[n]what to order...[n][w][e]

[msg MSG_89_F [Yukari]]
[s][bup 2 4 65535 0]I usually can make a decision pretty[n]quickly, but I get stuck in a loop like[n]this once in a while...[n][w][e]

[msg MSG_90_F [ ]]
[s]> Yukari seems disappointed in[n]herself...[n][w][e]

[msg MSG_91_F [Yukari]]
[s][bup 2 4 65535 0]Hmm, what should I do?[n][w][e]
[s]I can't decide between fried shrimp or[n]shabu-shabu![n][w][e]

[sel SEL092F top]
[s]"Why don't you order both?"[e]
[s]"Wanna share with me?"[e]
[s]"I can decide for you."[e]

[msg MSG_95_F [Yukari]]
[s][bup 2 5 65535 0]Noooo! Don't you try and get me fat,[n][f 4 2]![n][w][e]
[s][bup 2 1 65535 0]Hrmm, I guess my only choice now is...[n][w][e]
[s]Eeny, meeny, miney, moe:[n]Catch a tiger by the toe...[n][w][e]
[s]......[n][w][e]
[s][bup 2 5 65535 0]Huh? Fried Horse Mackerel Meal?[n][w][e]
[s][bup 2 2 65535 0]Oh well, I'll go with that then.[n][w][e]

[msg MSG_96_F [ ]]
[s][f 5 13 0 15 2]> Yukari finally lets herself relax[n]for the first time since entering[n]the restaurant...[n][w][e]
[s]> You learned something new about[n]Yukari today...[n][w][e]

[msg MSG_97_F [Yukari]]
[s][bup 2 2 65535 0]Really!?[n][w][e]
[s]Then, I'll order the Fried Shrimp Meal,[n]and you get the Japanese Shabu-shabu[n]Meal.[n][w][e]
[s]Thanks, [f 4 2]![n][w][e]

[msg MSG_98_F [ ]]
[s][f 5 13 0 30 2]> Yukari seems happy...[n][w][e]
[s]> Your friendship is a lot stronger[n]now.[n][w][e]

[msg MSG_93_F [Yukari]]
[s][bup 2 5 65535 0]B-But how are you going to decide for[n]me? That's the most important part![n][w][e]
[s]Oh I know. Let's play rock-paper-[n]scissors. If I win, I order the Fried[n]Shrimp Meal.[n][w][e]
[s]Ack, the waitress is here already.[n]Geez, what am I gonna do...?[n][w][e]

[msg MSG_94_F [ ]]
[s]> Yukari is flustered...[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_99_F [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_100_F]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_101_F [Fuuka]]
[s][bup 6 2 65535 0]This place is so useful.[n][w][e]
[s]Not only is it relatively cheap, but[n]the balance of the ingredients is[n]well thought out, too.[n][w][e]

[msg MSG_102_F]
[s]> Fuuka seems to be enjoying her day[n]off...[n][w][e]

[msg MSG_103_F [Fuuka]]
[s][bup 6 2 65535 0]And they seem to really think about the[n]health of their customers, too.[n][w][e]
[s]This "Iron-Plentiful Meal" is really[n]good for women.[n][w][e]

[msg MSG_104_F [ ]]
[s]> Fuuka is gazing at the menu[n]curiously...[n][w][e]

[msg MSG_105_F [Fuuka]]
[s][bup 6 2 65535 0]...Well here is a surprise question[n]for you![n][w][e]
[s]What happens if your body doesn't get[n]enough iron?[n][w][e]

[sel SEL106F top]
[s]"You lose taste."[e]
[s]"You become anemic."[e]
[s]"Your bones become brittle."[e]

[msg MSG_107_F [Fuuka]]
[s][bup 6 2 65535 0]Nope, wrong answer.[n][w][e]
[s]The correct answer is, you become[n]anemic. It'll make you dizzy when[n]you stand up quickly, so be careful.[n][w][e]
[s]I think that a zinc deficiency will [n]cause you to lose taste, though...[n][w][e]
[s]My home economics teacher told me that[n]when she gave me zinc supplements[n]before.[n][w][e]
[s]...I wonder why she gave them to me,[n]though.[n][w][e]

[msg MSG_108_F [ ]]
[s][f 5 13 0 15 0]> Fuuka seems puzzled...[n][w][e]
[s]> You learned something new about[n]Fuuka today...[n][w][e]

[msg MSG_109_F [Fuuka]]
[s][bup 6 2 65535 0]Bingo, that's correct.[n][w][e]
[s]I get anemic all the time, so I try[n]hard to get enough iron in my diet.[n][w][e]
[s]You should be careful too,[n][f 4 2]-chan.[n][w][e]

[msg MSG_110_F [ ]]
[s][f 5 13 0 30 0]> Fuuka seems to be worried about[n]you...[n][w][e]
[s]> Your friendship is a lot stronger[n]now.[n][w][e]

[msg MSG_111_F [Fuuka]]
[s][bup 6 2 65535 0]Nope, wrong answer.[n][w][e]
[s]The correct answer is, you become[n]anemic. It'll make you dizzy when[n]you stand up quickly, so be careful.[n][w][e]
[s]One's bones become brittle when you[n]have osteoper... Hm? Osteoporsis...?[n][w][e]
[s][bup 6 7 65535 0]...A-Anyways, something like that.[n]I think a big cause of that is calcium[n]deficiency.[n][w][e]

[msg MSG_112_F [ ]]
[s][f 5 13 0 15 0]> Fuuka seems a little embarrassed...[n][w][e]
[s]> You learned something new about[n]Fuuka today...[n][w][e]

[msg MSG_113_F [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_114_F]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_115_F [Mitsuru]]
[s][bup 4 1 65535 0]I see, this place doesn't use expensive[n]ingredients, but the flavors are[n]balanced and pair well with each other.[n][w][e]

[msg MSG_116_F]
[s]> Mitsuru seems to be enjoying her day[n]off...[n][w][e]

[msg MSG_117_F [Mitsuru]]
[s][bup 4 2 65535 0]I've lived in this city much longer[n]than you have...[n][w][e]
[s]And yet, you always manage to teach me[n]new things about it.[n][w][e]

[msg MSG_118_F [ ]]
[s]> Mitsuru displays a wry smile...[n][w][e]

[msg MSG_119_F [Mitsuru]]
[s][bup 4 1 65535 0]Is there anything that you'd like to[n]learn from me?[n][w][e]
[s]I'll back you up with everything that[n]I know.[n][w][e]

[sel SEL120F top]
[s]How to study for the exams[e]
[s]How to ride a motorcycle[e]
[s]How to become so beautiful[e]

[msg MSG_121_F [Mitsuru]]
[s][bup 4 2 65535 0]I see. Since you're a junior, it's[n]about time that you start turning your[n]attention to them.[n][w][e]
[s]Come talk to me when you've decided[n]which college you'd like to attend.[n][w][e]
[s]It's best to gear your preparation[n]according to which college you're going[n]to try and get into, after all.[n][w][e]

[msg MSG_122_F [ ]]
[s][f 5 13 0 15 0]> Mitsuru is speaking with enthusiasm...[n][w][e]
[s]> You learned something new about[n]Mitsuru today...[n][w][e]

[msg MSG_123_F [Mitsuru]]
[s][bup 4 2 65535 0]Is that all?[n][w][e]
[s]All right, I don't mind giving you a[n]lesson any day.[n][w][e]
[s][bup 4 1 65535 0]Oh... but you'll need a license if[n]we're going to go out onto public[n]streets, though.[n][w][e]
[s]Our group has driving schools too,[n]you I can help get you set up.[n][w][e]

[msg MSG_124_F [ ]]
[s][f 5 13 0 30 0]> Mitsuru seems to be having fun...[n][w][e]
[s]> Your friendship is a lot stronger[n]now.[n][w][e]

[msg MSG_125_F [Mitsuru]]
[s][bup 4 7 65535 0]Wha--Hey, don't joke like that...[n][w][e]
[s]Seriously, you shouldn't tease those[n]older than you...[n][w][e]

[msg MSG_126_F [ ]]
[s][f 5 13 0 15 0]> Mitsuru seems embarrassed...[n][w][e]
[s]> You learned something new about[n]Mitsuru today...[n][w][e]

[msg MSG_127_F [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_326_F]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_327_F [Bebe]]
[s][bup 34 162 65535 0]Oishii! Dis fried egg is so good, zat[n]my eyes will fall out.[n][w][e]

[msg MSG_328_F]
[s]> Bebe is enjoying the meal.[n][w][e]

[msg MSG_329_F [Bebe]]
[s][bup 34 161 65535 0]Still, I feel so vexed...[n][w][e]

[msg MSG_330_F [ ]]
[s]> Bebe seems flustered for some reason.[n][w][e]

[msg MSG_331_F [Bebe]]
[s][bup 34 161 65535 0]I 'ave no time to be infatuated with[n]meals.[n][w][e]
[s]I must 'urry and complete zhe kimono.[n][w][e]

[sel SEL332F top]
[s]"Should we go work on it now?"[e]
[s]"You need to calm down..."[e]
[s]"So, why did you ask me out?"[e]

[msg MSG_334_F [Bebe]]
[s][bup 34 163 65535 0]I 'ave no sewing machine at my 'ouse![n]I must endure dis until we 'ave school[n]again...![n][w][e]
[s]Eagles don't catch flies, after all![n][w][e]

[msg MSG_335_F [ ]]
[s]> Bebe seems vexed.[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_336_F [Bebe]]
[s][bup 34 162 65535 0]...Hontou, you are right![n][w][e]
[s]More haste, less speed, is what I must[n]remember![n][w][e]

[msg MSG_337_F [ ]]
[s][f 5 13 0 15 0]> Bebe is on fire...[n][w][e]
[s]> You learned something new about[n]Bebe today...[n][w][e]

[msg MSG_338_F [Bebe]]
[s][bup 34 161 65535 0]...Gomennasai.[n][w][e]
[s]I am depending on [f 4 2]-sama[n]too much...[n][w][e]
[s][bup 34 162 65535 0]You are very yasashii to me after[n]all...[n][w][e]
[s]Gomennasai...[n][w][e]

[msg MSG_339_F [ ]]
[s][f 5 13 0 30 0]> You sense affection from Bebe...[n][w][e]
[s]> Your friendship is a lot stronger[n]now.[n][w][e]

[msg MSG_340_F [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

[msg MSG_14_2ND]
[s]> Iwatodai strip mall,[n]Wakatsu Restaurant...[n][w][e]

[msg MSG_15_2ND [Kenji]]
[s][bup 22 162 65535 0]Sorry to call you out all of a sudden.[n][w][e]
[s]My family's out today, so I felt kinda[n]lonely eating out on my own.[n][w][e]
[s]That's when your face suddenly popped[n]into my head. I remembered you eating[n]ramen like it was the best thing ever.[n][w][e]

[msg MSG_16_2ND]
[s]> Kenji is talking while eating...[n][w][e]

[msg MSG_17_2ND [Kenji]]
[s][bup 22 162 65535 0]I can't trust guys that don't enjoy[n]their meals.[n][w][e]
[s]I mean, it's fine if the food's[n]really nasty.[n][w][e]
[s]But you can't trust 'em if it tastes[n]good, but they make it seem like it[n]tastes like crap.[n][w][e]

[msg MSG_18_2ND [ ]]
[s]> Kenji is laughing...[n][w][e]

[msg MSG_19_2ND [Kenji]]
[s][bup 22 162 65535 0]By the way, are you picky about your[n]food?[n][w][e]

[sel SEL020_2ND top]
[s]"I'm a pretty picky eater." +2[e]
[s]"Not at all."[e]
[s]"I won't eat certain things." +3[e]

[msg MSG_21_2ND [Kenji]]
[s][bup 22 162 65535 0]Huh, me too.[n][w][e]
[s][bup 22 164 65535 0]I can't eat about half the things in[n]this world. I'll never be able to view[n]those things as edible.[n][w][e]
[s]Don't you feel like you'd be able to[n]eat it if a beautiful lady cooked it[n]for ya, though?[n][w][e]

[msg MSG_22_2ND [ ]]
[s][f 5 13 0 30 22]> Kenji agreed with you with intense[n]passion.[n][w][e]
[s]> Your friendship is a lot stronger[n]now.[n][w][e]

[msg MSG_23_2ND [Kenji]]
[s][bup 22 164 65535 0]Yikes, you serious? I guess that's a[n]one way for a person to live...[n][w][e]
[s]I just can't stand some stuff,[n]personally.[n][w][e]
[s]Vegetables are no different than leaves[n]on a tree. I'm not a bug, ya know...[n][w][e]

[msg MSG_24_2ND [ ]]
[s]> Kenji is sighing...[n][w][e]
[s]> Your relationship seems to be[n]stuck in a rut.[n][w][e]

[msg MSG_25_2ND [Kenji]]
[s][bup 22 162 65535 0]Oh, I totally hear ya! There are just[n]some things that make you wanna scream,[n]"This ain't food!"[n][w][e]
[s]I mean, mushrooms are nothing more[n]than fungi, right? Seafood's pushin'[n]the limits too...[n][w][e]
[s]Also, I hate stuff like ginger and[n]beefsteak plants. Why in the world[n]would you eat roots and plants?[n][w][e]

[msg MSG_26_2ND [ ]]
[s][f 5 13 0 15 22]> Kenji agreed with you.[n][w][e]
[s]> You learned something new about[n]Kenji today...[n][w][e]

[msg MSG_27_2ND [ ]]
[s]> It's getting late...[n][w][e]
[s]> You decide to go back to the dorm.[n][w][e]

