[msg KLEMMYBELOVED_CHOICE]
[s]> You can check the front and back....[n][w][e]

[sel CHOOSE_BF top]
[s]Check the front.[e]
[s]Check the back.[e]
[s]Leave.[e]

[sel CHOOSE_FRONT top]
[s]Print Club - 1,500 yen[e]
[s]Quiz Game - 3,000 yen[e]
[s]Horror House - 3,000 yen[e]
[s]Go back.[e]

[sel LOOK_BACK top]
[s]Punching Bag - 2,000 yen[e]
[s]Mole Whackers - 2,000 yen[e]
[s]Lucky Fortune - 2,000 yen[e]
[s]Go back.[e]